/* Generated by re2c 0.13.5 on Fri Mar 28 14:44:23 2014 */
#line 1 "bcplus/Configuration.r2c"

#include <string>
#include <iostream>

#ifndef BOOST_FILESYSTEM_VERSION
#define BOOST_FILESYSTEM_VERSION 3
#endif
#include <boost/filesystem.hpp>
#include <boost/iostreams/stream.hpp>
#include <boost/iostreams/device/null.hpp>

#include "babb/utils/memory.h"
#include "babb/utils/utils.h"

#include "bcplus/Configuration.h"

namespace ios = boost::iostreams;
namespace fs = boost::filesystem;

namespace bcplus {

const size_t Configuration::DEFAULT_VERB_LEVEL = Verb::STD;

Configuration::Configuration(char const* bin, char const* version)
{ 
	_verb = DEFAULT_VERB_LEVEL;
	_version = new ReferencedString(version);
	_bin_name = new ReferencedString(fs::path(bin).filename().native());
	_parse_trace = false;
}


Configuration::~Configuration()
{ /* Intentionally left blank */ }


Option::Status Configuration::load(int argc, char const** argv) {
	Option::Status ret = Option::STAT_OK;
	char const* val;
	int int_v;
	bool good;

	// Figure out who we are
	fs::path bin = argv[0];
	_bin_name = new ReferencedString(bin.filename().native());

	// parse arguments

	for (int i = 1; i < argc; i++) {
		val = NULL;

		Option::type opt = parseOption(argv[i], val);

		switch (opt) {
		case Option::SYMTAB_INPUT:
			if (fs::native(val)) {
				_symtab_in = new ReferencedPath(val);
			} else {
				ret = Option::STAT_BAD_ARG;
				std::cerr << "ERROR: \"" << val << "\" is not a valid file path." << std::endl;
			}
			break;
		case Option::SYMTAB_OUTPUT:
			if (fs::native(val)) {
				_symtab_out = new ReferencedPath(val);
			} else {
				ret = Option::STAT_BAD_ARG;
				std::cerr << "ERROR: \"" << val << "\" is not a valid file path." << std::endl;

			}
			break;

		case Option::VERBOSITY:
			good = babb::utils::fromString(val, int_v);
			if (!good || int_v < 0) {
				ret = Option::STAT_BAD_ARG;
				std::cerr << "ERROR: unknown valud provided for command line option. Expected a non-negative integer in \"" << opt <<"." << std::endl;
			} else {
				verbosity(int_v);	
			}
			break;
		case Option::PARSE_TRACE:
			if (!strcmp(val, "true")) {
				_parse_trace = true;
			} else if (!strcmp(val, "false")) {
				_parse_trace = false;
			} else {
				ret = Option::STAT_BAD_ARG;
				std::cerr << "ERROR: unknown valud provided for command line option. Expected \"true\" or \"false\" in \"" << opt <<"." << std::endl;
			}
			break;

		case Option::HELP:
			return Option::STAT_HELP;

		case Option::VERSION:
			return Option::STAT_VERSION;

		case Option::BAD:			
		default:
			ret = Option::STAT_BAD_ARG;
			std::cerr << "ERROR: Unrecognized option: \"" << argv[i] << "\"." << std::endl;
			break;
		}

	}
	return ret;
}

bool Configuration::good() {
	bool good = true;
	// TODO
	return good;
}

std::ostream& Configuration::ostream(Verb::Level v) const {
	static ios::stream<ios::null_sink> NULLSTREAM( (ios::null_sink()) );

	if (v > _verb) return NULLSTREAM;
	else if (v == Verb::ERROR || v == Verb::WARN) return std::cerr;
#ifdef NDEBUG
	else if (v > Verb::STD) return NULLSTREAM;
#endif
	else return std::cout;
}

Option::type Configuration::parseOption(char const* opt, char const*& val) {
    char const* marker;

    val = NULL;

    
#line 136 "<stdout>"
	{
		char yych;

		yych = *opt;
		switch (yych) {
		case '\n':	goto yy2;
		case '-':	goto yy3;
		default:	goto yy5;
		}
yy2:
		opt = marker;
		goto yy4;
yy3:
		yych = *(marker = ++opt);
		switch (yych) {
		case '-':	goto yy6;
		case '?':
		case 'h':	goto yy9;
		case 's':	goto yy11;
		case 'v':	goto yy7;
		default:	goto yy4;
		}
yy4:
#line 146 "bcplus/Configuration.r2c"
		{ val = NULL; return Option::BAD; }
#line 162 "<stdout>"
yy5:
		yych = *++opt;
		goto yy4;
yy6:
		yych = *++opt;
		switch (yych) {
		case 'h':	goto yy17;
		case 'p':	goto yy16;
		case 's':	goto yy14;
		case 'v':	goto yy15;
		default:	goto yy2;
		}
yy7:
		++opt;
#line 145 "bcplus/Configuration.r2c"
		{ val = NULL; return Option::VERSION; }
#line 179 "<stdout>"
yy9:
		++opt;
#line 144 "bcplus/Configuration.r2c"
		{ val = NULL; return Option::HELP; }
#line 184 "<stdout>"
yy11:
		yych = *++opt;
		switch (yych) {
		case '=':	goto yy12;
		default:	goto yy2;
		}
yy12:
		++opt;
#line 139 "bcplus/Configuration.r2c"
		{ val = opt; return Option::SYMTAB_INPUT; }
#line 195 "<stdout>"
yy14:
		yych = *++opt;
		switch (yych) {
		case 'y':	goto yy41;
		default:	goto yy2;
		}
yy15:
		yych = *++opt;
		switch (yych) {
		case 'e':	goto yy33;
		default:	goto yy2;
		}
yy16:
		yych = *++opt;
		switch (yych) {
		case 'a':	goto yy20;
		default:	goto yy2;
		}
yy17:
		yych = *++opt;
		switch (yych) {
		case 'e':	goto yy18;
		default:	goto yy2;
		}
yy18:
		yych = *++opt;
		switch (yych) {
		case 'l':	goto yy19;
		default:	goto yy2;
		}
yy19:
		yych = *++opt;
		switch (yych) {
		case 'p':	goto yy9;
		default:	goto yy2;
		}
yy20:
		yych = *++opt;
		switch (yych) {
		case 'r':	goto yy21;
		default:	goto yy2;
		}
yy21:
		yych = *++opt;
		switch (yych) {
		case 's':	goto yy22;
		default:	goto yy2;
		}
yy22:
		yych = *++opt;
		switch (yych) {
		case 'e':	goto yy23;
		default:	goto yy2;
		}
yy23:
		yych = *++opt;
		switch (yych) {
		case '-':	goto yy24;
		default:	goto yy2;
		}
yy24:
		yych = *++opt;
		switch (yych) {
		case 't':	goto yy25;
		default:	goto yy2;
		}
yy25:
		yych = *++opt;
		switch (yych) {
		case 'r':	goto yy26;
		default:	goto yy2;
		}
yy26:
		yych = *++opt;
		switch (yych) {
		case 'a':	goto yy27;
		default:	goto yy2;
		}
yy27:
		yych = *++opt;
		switch (yych) {
		case 'c':	goto yy28;
		default:	goto yy2;
		}
yy28:
		yych = *++opt;
		switch (yych) {
		case 'e':	goto yy29;
		default:	goto yy2;
		}
yy29:
		++opt;
		switch ((yych = *opt)) {
		case '=':	goto yy31;
		default:	goto yy30;
		}
yy30:
#line 143 "bcplus/Configuration.r2c"
		{ val = "true"; return Option::PARSE_TRACE; }
#line 295 "<stdout>"
yy31:
		++opt;
#line 142 "bcplus/Configuration.r2c"
		{ val = opt; return Option::PARSE_TRACE; }
#line 300 "<stdout>"
yy33:
		yych = *++opt;
		switch (yych) {
		case 'r':	goto yy34;
		default:	goto yy2;
		}
yy34:
		yych = *++opt;
		switch (yych) {
		case 'b':	goto yy36;
		case 's':	goto yy35;
		default:	goto yy2;
		}
yy35:
		yych = *++opt;
		switch (yych) {
		case 'i':	goto yy39;
		default:	goto yy2;
		}
yy36:
		yych = *++opt;
		switch (yych) {
		case '=':	goto yy37;
		default:	goto yy2;
		}
yy37:
		++opt;
#line 141 "bcplus/Configuration.r2c"
		{ val = opt; return Option::VERBOSITY; }
#line 330 "<stdout>"
yy39:
		yych = *++opt;
		switch (yych) {
		case 'o':	goto yy40;
		default:	goto yy2;
		}
yy40:
		yych = *++opt;
		switch (yych) {
		case 'n':	goto yy7;
		default:	goto yy2;
		}
yy41:
		yych = *++opt;
		switch (yych) {
		case 'm':	goto yy42;
		default:	goto yy2;
		}
yy42:
		yych = *++opt;
		switch (yych) {
		case 't':	goto yy43;
		default:	goto yy2;
		}
yy43:
		yych = *++opt;
		switch (yych) {
		case 'a':	goto yy44;
		default:	goto yy2;
		}
yy44:
		yych = *++opt;
		switch (yych) {
		case 'b':	goto yy45;
		default:	goto yy2;
		}
yy45:
		yych = *++opt;
		switch (yych) {
		case '-':	goto yy46;
		default:	goto yy2;
		}
yy46:
		yych = *++opt;
		switch (yych) {
		case 'i':	goto yy48;
		case 'o':	goto yy47;
		default:	goto yy2;
		}
yy47:
		yych = *++opt;
		switch (yych) {
		case 'u':	goto yy50;
		default:	goto yy2;
		}
yy48:
		yych = *++opt;
		switch (yych) {
		case 'n':	goto yy49;
		default:	goto yy2;
		}
yy49:
		yych = *++opt;
		switch (yych) {
		case '=':	goto yy12;
		default:	goto yy2;
		}
yy50:
		yych = *++opt;
		switch (yych) {
		case 't':	goto yy51;
		default:	goto yy2;
		}
yy51:
		yych = *++opt;
		switch (yych) {
		case '=':	goto yy52;
		default:	goto yy2;
		}
yy52:
		++opt;
#line 140 "bcplus/Configuration.r2c"
		{ val = opt; return Option::SYMTAB_OUTPUT; }
#line 414 "<stdout>"
	}
#line 147 "bcplus/Configuration.r2c"


}




std::ostream& Configuration::output(std::ostream& out) const {
	out 
		<< "Executable name: " << *_bin_name << std::endl
		<< "Version: " << *_version << std::endl << std::endl
		<< "Symbol Table Input: \"" << (_symtab_in ? _symtab_in->native() : "<NONE>") << "\"" << std::endl
		<< "Symbol Table Output: \"" << (_symtab_out ? _symtab_out->native() : "<NONE>") << "\"" << std::endl
		<< "Verbosity: " << "\"" << _verb << "\"" << std::endl;

	return out;
}

std::ostream& Configuration::outputVersion(std::ostream& out) const {
	out << binaryName() << " version " << *version() << std::endl;
	return out;
}

std::ostream& Configuration::outputHelp(std::ostream& out) const {
	out << "---------------------------------------------------------------------------------------"<< std::endl
		<< *binaryName() << " version " << *version() 												<< std::endl
		<< "---------------------------------------------------------------------------------------"<< std::endl
		<< "Usage: " << *binaryName() << " <OPTIONS> <INPUT_FILES>" 								<< std::endl
		<< "          -s=<FILE>"																	<< std::endl
		<< "          --symtab-in=<FILE>"															<< std::endl
		<< "                   - An XML file to read the initial symbol table in from. [none]"		<< std::endl
		<< "          --symtab-out=<FILE>"															<< std::endl
		<< "                   - A file to write the final symbol table to. [none]"					<< std::endl
		<< "          --verb=<LEVEL>"																<< std::endl
		<< "                   - The level of output to show:"										<< std::endl
		<< "                        " << Verb::ERROR 		<< "  - Error output only"				<< std::endl
		<< "                        " << Verb::WARN 		<< "  - Warnings"						<< std::endl
		<< "                        " << Verb::STD	 		<< "  - Standard messages [default]"	<< std::endl
		<< "                     Only available when compiled in debug mode:"						<< std::endl
		<< "                        " << Verb::OP 			<< "  - Operation level trace output" 	<< std::endl
		<< "                        " << Verb::DETAIL	 	<< "  - Detailed debugging messages"	<< std::endl
		<< "                        " << Verb::TRACE_PARSER	<< "+ - Parser debugging messages"		<< std::endl
		<< "          --parse-trace"																<< std::endl
		<< "                   - Enable lemon parser trace output."									<< std::endl
		<< "          -v"																			<< std::endl
		<< "          --version"																	<< std::endl
		<< "                   - Displays the version dialog."										<< std::endl
		<< "          -h"																			<< std::endl
		<< "          --help"																		<< std::endl
		<< "                   - Shows this dialog."												<< std::endl;
	return out;
}

};
