/* Generated by re2c 0.13.5 on Fri Mar 28 20:20:53 2014 */
#line 1 "bcplus/Configuration.r2c"

#include <string>
#include <iostream>

#ifndef BOOST_FILESYSTEM_VERSION
#define BOOST_FILESYSTEM_VERSION 3
#endif
#include <boost/filesystem.hpp>
#include <boost/iostreams/stream.hpp>
#include <boost/iostreams/device/null.hpp>

#include "babb/utils/memory.h"
#include "babb/utils/utils.h"

#include "bcplus/Configuration.h"

namespace ios = boost::iostreams;
namespace fs = boost::filesystem;

namespace bcplus {

const size_t Configuration::DEFAULT_VERB_LEVEL = Verb::STD;

Configuration::Configuration(char const* bin, char const* version)
{ 
	_verb = DEFAULT_VERB_LEVEL;
	_version = new ReferencedString(version);
	_bin_name = new ReferencedString(fs::path(bin).filename().native());
	_parse_trace = false;
}


Configuration::~Configuration()
{ /* Intentionally left blank */ }


int Configuration::load(int argc, char const** argv) {
	Option::Status ret = Option::STAT_OK;
	std::string val, val2;
	int int_v;
	bool good;

	// Figure out who we are
	fs::path bin = argv[0];
	_bin_name = new ReferencedString(bin.filename().native());

	// parse arguments

	for (int i = 1; i < argc; i++) {
		int opt = parseOption(argv[i], val, val2);

		switch (opt) {
		case Option::SYMTAB_INPUT:
			if (fs::native(val2)) {
				_symtab_in = new ReferencedPath(val);
			} else {
				ret = Option::STAT_BAD_ARG;
				std::cerr << "ERROR: \"" << val2 << "\" is not a valid file path." << std::endl;
			}
			break;
		case Option::SYMTAB_OUTPUT:
			if (fs::native(val2)) {
				_symtab_out = new ReferencedPath(val2);
			} else {
				ret = Option::STAT_BAD_ARG;
				std::cerr << "ERROR: \"" << val2 << "\" is not a valid file path." << std::endl;

			}
			break;

		case Option::VERBOSITY:
			good = babb::utils::fromString(val2.c_str(), int_v);
			if (!good || int_v < 0) {
				ret = Option::STAT_BAD_ARG;
				std::cerr << "ERROR: Bad value provided for command line option. Expected a non-negative integer for argument \"" << val << "\"." << std::endl;
			} else {
				verbosity(int_v);	
			}
			break;
		case Option::PARSE_TRACE:
			if (val2 == "true") {
				_parse_trace = true;
			} else if (val2 == "false") {
				_parse_trace = false;
			} else {
				ret = Option::STAT_BAD_ARG;
				std::cerr << "ERROR: Bad value provided for command line option. Expected \"true\" or \"false\" for argument \"" << val <<"." << std::endl;
			}
			break;
		case Option::MACRO_DEF:
			addMacro(new ReferencedString(val), new ReferencedString(val2));
			break;

		case Option::HELP:
			return Option::STAT_HELP;

		case Option::VERSION:
			return Option::STAT_VERSION;

		case Option::BAD:			
		default:
			ret = Option::STAT_BAD_ARG;
			std::cerr << "ERROR: Unrecognized option: \"" << argv[i] << "\"." << std::endl;
			break;
		}

	}
	return ret;
}

bool Configuration::good() {
	bool good = true;
	// TODO
	return good;
}

std::ostream& Configuration::ostream(Verb::Level v) const {
	static ios::stream<ios::null_sink> NULLSTREAM( (ios::null_sink()) );

	if (v > _verb) return NULLSTREAM;
	else if (v == Verb::ERROR || v == Verb::WARN) return std::cerr;
#ifdef NDEBUG
	else if (v > Verb::STD) return NULLSTREAM;
#endif
	else return std::cout;
}

int Configuration::parseOption(char const* opt, std::string& val, std::string& val2) {
    char const* marker;
	char const* token = opt;

    val = "";
	val2 = "";

    
#line 139 "<stdout>"
	{
		char yych;

		yych = *opt;
		switch (yych) {
		case '\n':	goto yy2;
		case '-':	goto yy3;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy5;
		default:	goto yy6;
		}
yy2:
		opt = marker;
		goto yy4;
yy3:
		yych = *(marker = ++opt);
		switch (yych) {
		case '-':	goto yy12;
		case '?':
		case 'h':	goto yy15;
		case 's':	goto yy17;
		case 'v':	goto yy13;
		default:	goto yy4;
		}
yy4:
#line 175 "bcplus/Configuration.r2c"
		{ 
												  val = token;
												  return Option::BAD; }
#line 220 "<stdout>"
yy5:
		yych = *(marker = ++opt);
		switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy7;
		default:	goto yy4;
		}
yy6:
		yych = *++opt;
		goto yy4;
yy7:
		++opt;
		yych = *opt;
		switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy7;
		case '=':	goto yy9;
		default:	goto yy2;
		}
yy9:
		++opt;
		yych = *opt;
		if (yych >= 0x01) goto yy9;
#line 170 "bcplus/Configuration.r2c"
		{ 
												  char const* c = strchr(token, '=');
												  val.assign(token, (size_t)(c - token));
												  val2.assign(c+1,opt-c-1);
												  return Option::MACRO_DEF; }
#line 372 "<stdout>"
yy12:
		yych = *++opt;
		switch (yych) {
		case 'h':	goto yy23;
		case 'p':	goto yy22;
		case 's':	goto yy20;
		case 'v':	goto yy21;
		default:	goto yy2;
		}
yy13:
		++opt;
#line 167 "bcplus/Configuration.r2c"
		{ 
												  val = token;
												  return Option::VERSION; }
#line 388 "<stdout>"
yy15:
		++opt;
#line 164 "bcplus/Configuration.r2c"
		{ 
												  val = token;
												  return Option::HELP; }
#line 395 "<stdout>"
yy17:
		yych = *++opt;
		switch (yych) {
		case '=':	goto yy18;
		default:	goto yy2;
		}
yy18:
		++opt;
#line 144 "bcplus/Configuration.r2c"
		{ 
												  val.assign(token, (size_t)(opt - token - 2));
												  val2 = opt; 
												  return Option::SYMTAB_INPUT; }
#line 409 "<stdout>"
yy20:
		yych = *++opt;
		switch (yych) {
		case 'y':	goto yy47;
		default:	goto yy2;
		}
yy21:
		yych = *++opt;
		switch (yych) {
		case 'e':	goto yy39;
		default:	goto yy2;
		}
yy22:
		yych = *++opt;
		switch (yych) {
		case 'a':	goto yy26;
		default:	goto yy2;
		}
yy23:
		yych = *++opt;
		switch (yych) {
		case 'e':	goto yy24;
		default:	goto yy2;
		}
yy24:
		yych = *++opt;
		switch (yych) {
		case 'l':	goto yy25;
		default:	goto yy2;
		}
yy25:
		yych = *++opt;
		switch (yych) {
		case 'p':	goto yy15;
		default:	goto yy2;
		}
yy26:
		yych = *++opt;
		switch (yych) {
		case 'r':	goto yy27;
		default:	goto yy2;
		}
yy27:
		yych = *++opt;
		switch (yych) {
		case 's':	goto yy28;
		default:	goto yy2;
		}
yy28:
		yych = *++opt;
		switch (yych) {
		case 'e':	goto yy29;
		default:	goto yy2;
		}
yy29:
		yych = *++opt;
		switch (yych) {
		case '-':	goto yy30;
		default:	goto yy2;
		}
yy30:
		yych = *++opt;
		switch (yych) {
		case 't':	goto yy31;
		default:	goto yy2;
		}
yy31:
		yych = *++opt;
		switch (yych) {
		case 'r':	goto yy32;
		default:	goto yy2;
		}
yy32:
		yych = *++opt;
		switch (yych) {
		case 'a':	goto yy33;
		default:	goto yy2;
		}
yy33:
		yych = *++opt;
		switch (yych) {
		case 'c':	goto yy34;
		default:	goto yy2;
		}
yy34:
		yych = *++opt;
		switch (yych) {
		case 'e':	goto yy35;
		default:	goto yy2;
		}
yy35:
		++opt;
		switch ((yych = *opt)) {
		case '=':	goto yy37;
		default:	goto yy36;
		}
yy36:
#line 160 "bcplus/Configuration.r2c"
		{ 
												  val.assign(token, (size_t)(opt - token - 2));
												  val = "true"; 
												  return Option::PARSE_TRACE; }
#line 512 "<stdout>"
yy37:
		++opt;
#line 156 "bcplus/Configuration.r2c"
		{ 
												  val.assign(token, (size_t)(opt - token - 2));
												  val = opt; 
												  return Option::PARSE_TRACE; }
#line 520 "<stdout>"
yy39:
		yych = *++opt;
		switch (yych) {
		case 'r':	goto yy40;
		default:	goto yy2;
		}
yy40:
		yych = *++opt;
		switch (yych) {
		case 'b':	goto yy42;
		case 's':	goto yy41;
		default:	goto yy2;
		}
yy41:
		yych = *++opt;
		switch (yych) {
		case 'i':	goto yy45;
		default:	goto yy2;
		}
yy42:
		yych = *++opt;
		switch (yych) {
		case '=':	goto yy43;
		default:	goto yy2;
		}
yy43:
		++opt;
#line 152 "bcplus/Configuration.r2c"
		{ 
												  val.assign(token, (size_t)(opt - token - 2));
												  val2 = opt; 
												  return Option::VERBOSITY; }
#line 553 "<stdout>"
yy45:
		yych = *++opt;
		switch (yych) {
		case 'o':	goto yy46;
		default:	goto yy2;
		}
yy46:
		yych = *++opt;
		switch (yych) {
		case 'n':	goto yy13;
		default:	goto yy2;
		}
yy47:
		yych = *++opt;
		switch (yych) {
		case 'm':	goto yy48;
		default:	goto yy2;
		}
yy48:
		yych = *++opt;
		switch (yych) {
		case 't':	goto yy49;
		default:	goto yy2;
		}
yy49:
		yych = *++opt;
		switch (yych) {
		case 'a':	goto yy50;
		default:	goto yy2;
		}
yy50:
		yych = *++opt;
		switch (yych) {
		case 'b':	goto yy51;
		default:	goto yy2;
		}
yy51:
		yych = *++opt;
		switch (yych) {
		case '-':	goto yy52;
		default:	goto yy2;
		}
yy52:
		yych = *++opt;
		switch (yych) {
		case 'i':	goto yy54;
		case 'o':	goto yy53;
		default:	goto yy2;
		}
yy53:
		yych = *++opt;
		switch (yych) {
		case 'u':	goto yy56;
		default:	goto yy2;
		}
yy54:
		yych = *++opt;
		switch (yych) {
		case 'n':	goto yy55;
		default:	goto yy2;
		}
yy55:
		yych = *++opt;
		switch (yych) {
		case '=':	goto yy18;
		default:	goto yy2;
		}
yy56:
		yych = *++opt;
		switch (yych) {
		case 't':	goto yy57;
		default:	goto yy2;
		}
yy57:
		yych = *++opt;
		switch (yych) {
		case '=':	goto yy58;
		default:	goto yy2;
		}
yy58:
		++opt;
#line 148 "bcplus/Configuration.r2c"
		{ 
												  val.assign(token, (size_t)(opt - token - 2));
												  val2 = opt; 
												  return Option::SYMTAB_OUTPUT; }
#line 640 "<stdout>"
	}
#line 178 "bcplus/Configuration.r2c"


}




std::ostream& Configuration::output(std::ostream& out) const {
	out 
		<< "Executable name: " << *_bin_name << std::endl
		<< "Version: " << *_version << std::endl << std::endl
		<< "Symbol Table Input: \"" << (_symtab_in ? _symtab_in->native() : "<NONE>") << "\"" << std::endl
		<< "Symbol Table Output: \"" << (_symtab_out ? _symtab_out->native() : "<NONE>") << "\"" << std::endl
		<< "Verbosity: " << "\"" << _verb << "\"" << std::endl
		<< "Parser trace: " << "\"" << (parseTrace() ? "true" : "false") << "\"" << std::endl;
	return out;
}

std::ostream& Configuration::outputVersion(std::ostream& out) const {
	out << binaryName() << " version " << *version() << std::endl;
	return out;
}

std::ostream& Configuration::outputHelp(std::ostream& out) const {
	out << "---------------------------------------------------------------------------------------"<< std::endl
		<< *binaryName() << " version " << *version() 												<< std::endl
		<< "---------------------------------------------------------------------------------------"<< std::endl
		<< "Usage: " << *binaryName() << " <OPTIONS> <INPUT_FILES>" 								<< std::endl
		<< "          -s=<FILE>"																	<< std::endl
		<< "          --symtab-in=<FILE>"															<< std::endl
		<< "                   - An XML file to read the initial symbol table in from. [none]"		<< std::endl
		<< "          --symtab-out=<FILE>"															<< std::endl
		<< "                   - A file to write the final symbol table to. [none]"					<< std::endl
		<< "          --verb=<LEVEL>"																<< std::endl
		<< "                   - The level of output to show:"										<< std::endl
		<< "                        " << Verb::ERROR 		<< "  - Error output only"				<< std::endl
		<< "                        " << Verb::WARN 		<< "  - Warnings"						<< std::endl
		<< "                        " << Verb::STD	 		<< "  - Standard messages [default]"	<< std::endl
		<< "                     Only available when compiled in debug mode:"						<< std::endl
		<< "                        " << Verb::OP 			<< "  - Operation level trace output" 	<< std::endl
		<< "                        " << Verb::DETAIL	 	<< "  - Detailed debugging messages"	<< std::endl
		<< "                        " << Verb::TRACE_PARSER	<< "+ - Parser debugging messages"		<< std::endl
		<< "          --parse-trace"																<< std::endl
		<< "                   - Enable lemon parser trace output."									<< std::endl
		<< "          -v"																			<< std::endl
		<< "          --version"																	<< std::endl
		<< "                   - Displays the version dialog."										<< std::endl
		<< "          -h"																			<< std::endl
		<< "          --help"																		<< std::endl
		<< "                   - Shows this dialog."												<< std::endl;
	return out;
}

};
