#define T_INTEGER                         1
#define T_IDENTIFIER                      2
#define T_STRING_LITERAL                  3
#define T_ASP_GR                          4
#define T_ASP_CP                          5
#define T_LUA_GR                          6
#define T_LUA_CP                          7
#define T_F2LP_GR                         8
#define T_F2LP_CP                         9
#define T_COMMENT                        10
#define T_CONSTANTS                      11
#define T_INCLUDE                        12
#define T_MACROS                         13
#define T_OBJECTS                        14
#define T_QUERY                          15
#define T_SHOW                           16
#define T_SORTS                          17
#define T_VARIABLES                      18
#define T_ABACTION                       19
#define T_ACTION                         20
#define T_ADDITIVEACTION                 21
#define T_ADDITIVEFLUENT                 22
#define T_AFTER                          23
#define T_ALWAYS                         24
#define T_ASSUMING                       25
#define T_ATTRIBUTE                      26
#define T_BY                             27
#define T_CAUSED                         28
#define T_CAUSES                         29
#define T_IMPOSSIBLE                     30
#define T_CONSTRAINT                     31
#define T_DECREMENTS                     32
#define T_DEFAULT                        33
#define T_EXTERNALACTION                 34
#define T_EXOGENOUS                      35
#define T_EXOGENOUSACTION                36
#define T_IF                             37
#define T_IFCONS                         38
#define T_INCREMENTS                     39
#define T_INERTIAL                       40
#define T_INERTIALFLUENT                 41
#define T_LABEL                          42
#define T_MAY_CAUSE                      43
#define T_MAXADDITIVE                    44
#define T_MAXAFVALUE                     45
#define T_MAXSTEP                        46
#define T_NEVER                          47
#define T_NOCONCURRENCY                  48
#define T_STRONG_NOCONCURRENCY           49
#define T_NONEXECUTABLE                  50
#define T_OF                             51
#define T_POSSIBLY_CAUSED                52
#define T_RIGID                          53
#define T_SDFLUENT                       54
#define T_SIMPLEFLUENT                   55
#define T_EXTERNALFLUENT                 56
#define T_UNLESS                         57
#define T_WHERE                          58
#define T_FALSE                          59
#define T_NONE                           60
#define T_TRUE                           61
#define T_ABS                            62
#define T_AT                             63
#define T_BRACKET_L                      64
#define T_BRACKET_R                      65
#define T_COLON_DASH                     66
#define T_CBRACKET_L                     67
#define T_CBRACKET_R                     68
#define T_PAREN_L                        69
#define T_PAREN_R                        70
#define T_PERIOD                         71
#define T_PIPE                           72
#define T_TILDE                          73
#define T_DBL_COLON                      74
#define T_ARROW_LEQ                      75
#define T_ARROW_REQ                      76
#define T_ARROW_LDASH                    77
#define T_COLON                          78
#define T_EQ                             79
#define T_DBL_EQ                         80
#define T_NEQ                            81
#define T_NOT_EQ                         82
#define T_LTHAN                          83
#define T_GTHAN                          84
#define T_LTHAN_EQ                       85
#define T_GTHAN_EQ                       86
#define T_DBL_PERIOD                     87
#define T_BIG_CONJ                       88
#define T_BIG_DISJ                       89
#define T_POUND                          90
#define T_SEMICOLON                      91
#define T_EQUIV                          92
#define T_IMPL                           93
#define T_ARROW_RDASH                    94
#define T_DBL_PLUS                       95
#define T_AMP                            96
#define T_DBL_AMP                        97
#define T_COMMA                          98
#define T_NOT                            99
#define T_DASH                           100
#define T_PLUS                           101
#define T_DBL_GTHAN                      102
#define T_STAR                           103
#define T_INT_DIV                        104
#define T_MOD                            105
#define T_UMINUS                         106
#define T_EOF                            107
#define T_ERR_IO                         108
#define T_ERR_UNKNOWN_SYMBOL             109
#define T_ERR_UNTERMINATED_STRING        110
#define T_ERR_UNTERMINATED_ASP           111
#define T_ERR_UNTERMINATED_LUA           112
#define T_ERR_UNTERMINATED_F2LP          113
#define T_ERR_UNTERMINATED_BLK_COMMENT   114
