/* Generated by re2c 0.13.6 on Mon May  5 23:51:11 2014 */
#line 1 "bcplus/parser/detail/Scanner.2.re2c"

#include <sstream>

#include <boost/filesystem.hpp>
#include <boost/filesystem/fstream.hpp>

#include "bcplus/parser/detail/Scanner.h"
#include "bcplus/parser/detail/lemon_parser.h"

#include "bcplus/Location.h"
#include "bcplus/parser/Token.h"

#include "bcplus/parser/detail/ScannerSource.h"
#include "bcplus/parser/detail/ScannerRawSource.h"
#include "bcplus/parser/detail/ScannerTokenSource.h"
#include "bcplus/parser/detail/ScannerFileSource.h"
#include "bcplus/parser/detail/ScannerBufferSource.h"

namespace u = babb::utils; 
namespace fs = boost::filesystem;

namespace bcplus {
namespace parser {
namespace detail {

Token* Scanner::tokenize_2(ScannerRawSource* source) {
	if (source->eof()) return new Token(T_EOF, new ReferencedString("<EOF>"), source->loc(), source->loc());
	else if (!source->good()) return new Token(T_ERR_IO, new ReferencedString("<IO ERROR>"), source->loc(), source->loc());


	int ret;
	Location begin;

	begin = source->loc();
	source->token() = source->cursor();

	if (_cond == yycNORMAL) {
			
#line 42 "<stdout>"
{
	char yych;
	unsigned int yyaccept = 0;
	goto yyc_NORMAL;
/* *********************************** */
yyc_NORMAL:
	{
		static const unsigned char yybm[] = {
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0, 128,   0, 128, 128,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			128,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
		};
		if ((source->limit() - source->cursor()) < 20) source->fill(20);
		yych = *source->cursor();
		if (yych <= 'k') {
			if (yych <= 'c') {
				if (yych <= '`') {
					if (yych != '\n') goto yy2_4;
				} else {
					if (yych <= 'a') goto yy2_6;
					if (yych <= 'b') goto yy2_7;
					goto yy2_8;
				}
			} else {
				if (yych <= 'f') {
					if (yych <= 'd') goto yy2_9;
					if (yych <= 'e') goto yy2_10;
					goto yy2_11;
				} else {
					if (yych == 'i') goto yy2_12;
					goto yy2_4;
				}
			}
		} else {
			if (yych <= 'q') {
				if (yych <= 'n') {
					if (yych <= 'l') goto yy2_13;
					if (yych <= 'm') goto yy2_14;
					goto yy2_15;
				} else {
					if (yych <= 'o') goto yy2_16;
					if (yych <= 'p') goto yy2_17;
					goto yy2_18;
				}
			} else {
				if (yych <= 't') {
					if (yych <= 'r') goto yy2_19;
					if (yych <= 's') goto yy2_20;
					goto yy2_21;
				} else {
					if (yych <= 'u') goto yy2_22;
					if (yych <= 'v') goto yy2_23;
					if (yych <= 'w') goto yy2_24;
					goto yy2_4;
				}
			}
		}
yy2_3:
		source->cursor() = source->marker();
		if (yyaccept <= 2) {
			if (yyaccept <= 1) {
				if (yyaccept == 0) {
					goto yy2_5;
				} else {
					goto yy2_162;
				}
			} else {
				goto yy2_232;
			}
		} else {
			if (yyaccept == 3) {
				goto yy2_254;
			} else {
				goto yy2_291;
			}
		}
yy2_4:
		++source->cursor();
yy2_5:
#line 117 "bcplus/parser/detail/Scanner.2.re2c"
		{ goto re2c_notkw; }
#line 153 "<stdout>"
yy2_6:
		yyaccept = 0;
		yych = *(source->marker() = ++source->cursor());
		switch (yych) {
		case 'b':	goto yy2_359;
		case 'c':	goto yy2_365;
		case 'd':	goto yy2_364;
		case 'f':	goto yy2_363;
		case 'l':	goto yy2_360;
		case 's':	goto yy2_362;
		case 't':	goto yy2_361;
		default:	goto yy2_5;
		}
yy2_7:
		yych = *++source->cursor();
		if (yych == 'y') goto yy2_357;
		goto yy2_5;
yy2_8:
		yyaccept = 0;
		yych = *(source->marker() = ++source->cursor());
		if (yych == 'a') goto yy2_335;
		if (yych == 'o') goto yy2_334;
		goto yy2_5;
yy2_9:
		yyaccept = 0;
		yych = *(source->marker() = ++source->cursor());
		if (yych == 'e') goto yy2_318;
		goto yy2_5;
yy2_10:
		yyaccept = 0;
		yych = *(source->marker() = ++source->cursor());
		if (yych == 'q') goto yy2_280;
		if (yych == 'x') goto yy2_282;
		goto yy2_5;
yy2_11:
		yyaccept = 0;
		yych = *(source->marker() = ++source->cursor());
		if (yych == 'a') goto yy2_275;
		goto yy2_5;
yy2_12:
		yyaccept = 0;
		yych = *(source->marker() = ++source->cursor());
		if (yych <= 'l') {
			if (yych == 'f') goto yy2_231;
			goto yy2_5;
		} else {
			if (yych <= 'm') goto yy2_230;
			if (yych <= 'n') goto yy2_229;
			goto yy2_5;
		}
yy2_13:
		yyaccept = 0;
		yych = *(source->marker() = ++source->cursor());
		if (yych == 'a') goto yy2_224;
		goto yy2_5;
yy2_14:
		yyaccept = 0;
		yych = *(source->marker() = ++source->cursor());
		if (yych == 'a') goto yy2_185;
		if (yych == 'o') goto yy2_184;
		goto yy2_5;
yy2_15:
		yyaccept = 0;
		yych = *(source->marker() = ++source->cursor());
		if (yych == 'e') goto yy2_150;
		if (yych == 'o') goto yy2_149;
		goto yy2_5;
yy2_16:
		yyaccept = 0;
		yych = *(source->marker() = ++source->cursor());
		if (yych == 'b') goto yy2_142;
		if (yych == 'f') goto yy2_140;
		goto yy2_5;
yy2_17:
		yyaccept = 0;
		yych = *(source->marker() = ++source->cursor());
		if (yych == 'o') goto yy2_124;
		goto yy2_5;
yy2_18:
		yyaccept = 0;
		yych = *(source->marker() = ++source->cursor());
		if (yych == 'u') goto yy2_119;
		goto yy2_5;
yy2_19:
		yyaccept = 0;
		yych = *(source->marker() = ++source->cursor());
		if (yych == 'i') goto yy2_114;
		goto yy2_5;
yy2_20:
		yyaccept = 0;
		yych = *(source->marker() = ++source->cursor());
		switch (yych) {
		case 'd':	goto yy2_51;
		case 'h':	goto yy2_53;
		case 'i':	goto yy2_50;
		case 'o':	goto yy2_52;
		case 't':	goto yy2_49;
		default:	goto yy2_5;
		}
yy2_21:
		yyaccept = 0;
		yych = *(source->marker() = ++source->cursor());
		if (yych == 'r') goto yy2_45;
		goto yy2_5;
yy2_22:
		yyaccept = 0;
		yych = *(source->marker() = ++source->cursor());
		if (yych == 'n') goto yy2_39;
		goto yy2_5;
yy2_23:
		yyaccept = 0;
		yych = *(source->marker() = ++source->cursor());
		if (yych == 'a') goto yy2_30;
		goto yy2_5;
yy2_24:
		yyaccept = 0;
		yych = *(source->marker() = ++source->cursor());
		if (yych != 'h') goto yy2_5;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'r') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		++source->cursor();
#line 105 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_WHERE;						goto re2c_finish;					}
#line 281 "<stdout>"
yy2_30:
		yych = *++source->cursor();
		if (yych != 'r') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'i') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'a') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'b') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'l') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 's') goto yy2_3;
		++source->cursor();
#line 60 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_VARIABLES;					goto re2c_finish;					}
#line 300 "<stdout>"
yy2_39:
		yych = *++source->cursor();
		if (yych != 'l') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 's') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 's') goto yy2_3;
		++source->cursor();
#line 104 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_UNLESS;						goto re2c_finish;					}
#line 313 "<stdout>"
yy2_45:
		yych = *++source->cursor();
		if (yych != 'u') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		++source->cursor();
#line 113 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_TRUE;							goto re2c_finish;					}
#line 322 "<stdout>"
yy2_49:
		yych = *++source->cursor();
		if (yych == 'r') goto yy2_79;
		goto yy2_3;
yy2_50:
		yych = *++source->cursor();
		if (yych == 'm') goto yy2_68;
		goto yy2_3;
yy2_51:
		yych = *++source->cursor();
		if (yych == 'F') goto yy2_61;
		goto yy2_3;
yy2_52:
		yych = *++source->cursor();
		if (yych == 'r') goto yy2_57;
		goto yy2_3;
yy2_53:
		yych = *++source->cursor();
		if (yych != 'o') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'w') goto yy2_3;
		++source->cursor();
#line 58 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_SHOW;							goto re2c_finish;					}
#line 347 "<stdout>"
yy2_57:
		yych = *++source->cursor();
		if (yych != 't') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 's') goto yy2_3;
		++source->cursor();
#line 59 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_SORTS;						goto re2c_finish;					}
#line 356 "<stdout>"
yy2_61:
		yych = *++source->cursor();
		if (yych != 'l') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'u') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 't') goto yy2_3;
		++source->cursor();
#line 98 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_SDFLUENT;						goto re2c_finish;					}
#line 371 "<stdout>"
yy2_68:
		yych = *++source->cursor();
		if (yych != 'p') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'l') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'F') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'l') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'u') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 't') goto yy2_3;
		++source->cursor();
#line 99 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_SIMPLEFLUENT;					goto re2c_finish;					}
#line 394 "<stdout>"
yy2_79:
		yych = *++source->cursor();
		if (yych != 'o') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'g') goto yy2_3;
		yych = *++source->cursor();
		if (yych == '_') goto yy2_85;
		if (yych == 'n') goto yy2_3;
		goto yy2_84;
yy2_83:
		++source->cursor();
		if ((source->limit() - source->cursor()) < 13) source->fill(13);
		yych = *source->cursor();
yy2_84:
		if (yybm[0+yych] & 128) {
			goto yy2_83;
		}
		if (yych == 'n') goto yy2_100;
		goto yy2_3;
yy2_85:
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'o') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'c') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'o') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'c') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'u') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'r') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'r') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'c') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'y') goto yy2_3;
		++source->cursor();
#line 101 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_STRONG_NOCONCURRENCY;			goto re2c_finish;					}
#line 446 "<stdout>"
yy2_100:
		yych = *++source->cursor();
		if (yych != 'o') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'c') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'o') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'c') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'u') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'r') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'r') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'c') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'y') goto yy2_3;
		++source->cursor();
#line 100 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_STRONG_NOCONCURRENCY;			goto re2c_finish;					}
#line 475 "<stdout>"
yy2_114:
		yych = *++source->cursor();
		if (yych != 'g') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'i') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'd') goto yy2_3;
		++source->cursor();
#line 97 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_RIGID;						goto re2c_finish;					}
#line 486 "<stdout>"
yy2_119:
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'r') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'y') goto yy2_3;
		++source->cursor();
#line 57 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_QUERY;						goto re2c_finish;					}
#line 497 "<stdout>"
yy2_124:
		yych = *++source->cursor();
		if (yych != 's') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 's') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'i') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'b') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'l') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'y') goto yy2_3;
		yych = *++source->cursor();
		if (yych == 'c') goto yy2_3;
		goto yy2_132;
yy2_131:
		++source->cursor();
		if ((source->limit() - source->cursor()) < 6) source->fill(6);
		yych = *source->cursor();
yy2_132:
		if (yych <= '\f') {
			if (yych == '\t') goto yy2_131;
			if (yych <= '\n') goto yy2_3;
			goto yy2_131;
		} else {
			if (yych <= ' ') {
				if (yych <= 0x1F) goto yy2_3;
				goto yy2_131;
			} else {
				if (yych != 'c') goto yy2_3;
			}
		}
		yych = *++source->cursor();
		if (yych != 'a') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'u') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 's') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'd') goto yy2_3;
		++source->cursor();
#line 96 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_POSSIBLY_CAUSED;				goto re2c_finish;					}
#line 544 "<stdout>"
yy2_140:
		++source->cursor();
#line 95 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_OF;							goto re2c_finish;					}
#line 549 "<stdout>"
yy2_142:
		yych = *++source->cursor();
		if (yych != 'j') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'c') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 't') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 's') goto yy2_3;
		++source->cursor();
#line 56 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_OBJECTS;						goto re2c_finish;					}
#line 564 "<stdout>"
yy2_149:
		yych = *++source->cursor();
		if (yych <= 'm') {
			if (yych == 'c') goto yy2_157;
			goto yy2_3;
		} else {
			if (yych <= 'n') goto yy2_158;
			if (yych == 't') goto yy2_159;
			goto yy2_3;
		}
yy2_150:
		yych = *++source->cursor();
		if (yych == 'q') goto yy2_152;
		if (yych != 'v') goto yy2_3;
		yych = *++source->cursor();
		if (yych == 'e') goto yy2_154;
		goto yy2_3;
yy2_152:
		++source->cursor();
#line 110 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_NEQ;							goto re2c_finish;					}
#line 586 "<stdout>"
yy2_154:
		yych = *++source->cursor();
		if (yych != 'r') goto yy2_3;
		++source->cursor();
#line 92 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_NEVER;						goto re2c_finish;					}
#line 593 "<stdout>"
yy2_157:
		yych = *++source->cursor();
		if (yych == 'o') goto yy2_173;
		goto yy2_3;
yy2_158:
		yych = *++source->cursor();
		if (yych == 'e') goto yy2_161;
		goto yy2_3;
yy2_159:
		++source->cursor();
#line 112 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_NOT;							goto re2c_finish;					}
#line 606 "<stdout>"
yy2_161:
		yyaccept = 1;
		yych = *(source->marker() = ++source->cursor());
		if (yych == 'x') goto yy2_163;
yy2_162:
#line 111 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_NONE;							goto re2c_finish;					}
#line 614 "<stdout>"
yy2_163:
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'c') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'u') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 't') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'a') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'b') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'l') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		++source->cursor();
#line 94 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_NONEXECUTABLE;				goto re2c_finish;					}
#line 635 "<stdout>"
yy2_173:
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'c') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'u') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'r') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'r') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'c') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'y') goto yy2_3;
		++source->cursor();
#line 93 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_NOCONCURRENCY;				goto re2c_finish;					}
#line 658 "<stdout>"
yy2_184:
		yych = *++source->cursor();
		if (yych == 'd') goto yy2_222;
		goto yy2_3;
yy2_185:
		yych = *++source->cursor();
		if (yych <= 'w') {
			if (yych != 'c') goto yy2_3;
		} else {
			if (yych <= 'x') goto yy2_188;
			if (yych <= 'y') goto yy2_187;
			goto yy2_3;
		}
		yych = *++source->cursor();
		if (yych == 'r') goto yy2_218;
		goto yy2_3;
yy2_187:
		yych = *++source->cursor();
		if (yych == 'c') goto yy2_3;
		goto yy2_211;
yy2_188:
		yych = *++source->cursor();
		if (yych == 'A') goto yy2_190;
		if (yych != 's') goto yy2_3;
		yych = *++source->cursor();
		if (yych == 't') goto yy2_206;
		goto yy2_3;
yy2_190:
		yych = *++source->cursor();
		if (yych == 'F') goto yy2_192;
		if (yych != 'd') goto yy2_3;
		yych = *++source->cursor();
		if (yych == 'd') goto yy2_199;
		goto yy2_3;
yy2_192:
		yych = *++source->cursor();
		if (yych != 'V') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'a') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'l') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'u') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		++source->cursor();
#line 90 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_MAXAFVALUE;					goto re2c_finish;					}
#line 707 "<stdout>"
yy2_199:
		yych = *++source->cursor();
		if (yych != 'i') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 't') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'i') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'v') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		++source->cursor();
#line 89 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_MAXADDITIVE;					goto re2c_finish;					}
#line 722 "<stdout>"
yy2_206:
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'p') goto yy2_3;
		++source->cursor();
#line 91 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_MAXSTEP;						goto re2c_finish;					}
#line 731 "<stdout>"
yy2_210:
		++source->cursor();
		if ((source->limit() - source->cursor()) < 5) source->fill(5);
		yych = *source->cursor();
yy2_211:
		if (yych <= '\f') {
			if (yych == '\t') goto yy2_210;
			if (yych <= '\n') goto yy2_3;
			goto yy2_210;
		} else {
			if (yych <= ' ') {
				if (yych <= 0x1F) goto yy2_3;
				goto yy2_210;
			} else {
				if (yych != 'c') goto yy2_3;
			}
		}
		yych = *++source->cursor();
		if (yych != 'a') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'u') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 's') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		++source->cursor();
#line 88 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_MAY_CAUSE;					goto re2c_finish;					}
#line 760 "<stdout>"
yy2_218:
		yych = *++source->cursor();
		if (yych != 'o') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 's') goto yy2_3;
		++source->cursor();
#line 55 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_MACROS; _in_macro = true;		goto re2c_finish;					}
#line 769 "<stdout>"
yy2_222:
		++source->cursor();
#line 109 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_MOD;							goto re2c_finish;					}
#line 774 "<stdout>"
yy2_224:
		yych = *++source->cursor();
		if (yych != 'b') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'l') goto yy2_3;
		++source->cursor();
#line 87 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_LABEL;						goto re2c_finish;					}
#line 785 "<stdout>"
yy2_229:
		yych = *++source->cursor();
		if (yych == 'c') goto yy2_247;
		if (yych == 'e') goto yy2_248;
		goto yy2_3;
yy2_230:
		yych = *++source->cursor();
		if (yych == 'p') goto yy2_238;
		goto yy2_3;
yy2_231:
		yyaccept = 2;
		yych = *(source->marker() = ++source->cursor());
		if (yych == 'c') goto yy2_233;
yy2_232:
#line 81 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_IF;							goto re2c_finish;					}
#line 802 "<stdout>"
yy2_233:
		yych = *++source->cursor();
		if (yych != 'o') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 's') goto yy2_3;
		++source->cursor();
#line 82 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_IFCONS;						goto re2c_finish;					}
#line 813 "<stdout>"
yy2_238:
		yych = *++source->cursor();
		if (yych != 'o') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 's') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 's') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'i') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'b') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'l') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		++source->cursor();
#line 83 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_IMPOSSIBLE;					goto re2c_finish;					}
#line 832 "<stdout>"
yy2_247:
		yych = *++source->cursor();
		if (yych == 'l') goto yy2_263;
		if (yych == 'r') goto yy2_262;
		goto yy2_3;
yy2_248:
		yych = *++source->cursor();
		if (yych != 'r') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 't') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'i') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'a') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'l') goto yy2_3;
		yyaccept = 3;
		yych = *(source->marker() = ++source->cursor());
		if (yych == 'F') goto yy2_255;
yy2_254:
#line 85 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_INERTIAL;						goto re2c_finish;					}
#line 855 "<stdout>"
yy2_255:
		yych = *++source->cursor();
		if (yych != 'l') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'u') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 't') goto yy2_3;
		++source->cursor();
#line 86 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_INERTIALFLUENT;				goto re2c_finish;					}
#line 870 "<stdout>"
yy2_262:
		yych = *++source->cursor();
		if (yych == 'e') goto yy2_268;
		goto yy2_3;
yy2_263:
		yych = *++source->cursor();
		if (yych != 'u') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'd') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		++source->cursor();
#line 54 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_INCLUDE;						goto re2c_finish;					}
#line 885 "<stdout>"
yy2_268:
		yych = *++source->cursor();
		if (yych != 'm') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 't') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 's') goto yy2_3;
		++source->cursor();
#line 84 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_INCREMENTS;					goto re2c_finish;					}
#line 900 "<stdout>"
yy2_275:
		yych = *++source->cursor();
		if (yych != 'l') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 's') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		++source->cursor();
#line 108 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_FALSE;						goto re2c_finish;					}
#line 911 "<stdout>"
yy2_280:
		++source->cursor();
#line 107 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_EQ;							goto re2c_finish;					}
#line 916 "<stdout>"
yy2_282:
		yych = *++source->cursor();
		if (yych == 'o') goto yy2_284;
		if (yych != 't') goto yy2_3;
		yych = *++source->cursor();
		if (yych == 'e') goto yy2_299;
		goto yy2_3;
yy2_284:
		yych = *++source->cursor();
		if (yych != 'g') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'o') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'u') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 's') goto yy2_3;
		yyaccept = 4;
		yych = *(source->marker() = ++source->cursor());
		if (yych == 'A') goto yy2_292;
yy2_291:
#line 79 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_EXOGENOUS;					goto re2c_finish;					}
#line 943 "<stdout>"
yy2_292:
		yych = *++source->cursor();
		if (yych != 'c') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 't') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'i') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'o') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		++source->cursor();
#line 80 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_EXOGENOUSACTION;				goto re2c_finish;					}
#line 958 "<stdout>"
yy2_299:
		yych = *++source->cursor();
		if (yych != 'r') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'a') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'l') goto yy2_3;
		yych = *++source->cursor();
		if (yych == 'A') goto yy2_304;
		if (yych == 'F') goto yy2_305;
		goto yy2_3;
yy2_304:
		yych = *++source->cursor();
		if (yych == 'c') goto yy2_312;
		goto yy2_3;
yy2_305:
		yych = *++source->cursor();
		if (yych != 'l') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'u') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 't') goto yy2_3;
		++source->cursor();
#line 78 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_EXTERNALFLUENT;				goto re2c_finish;					}
#line 990 "<stdout>"
yy2_312:
		yych = *++source->cursor();
		if (yych != 't') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'i') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'o') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		++source->cursor();
#line 77 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_EXTERNALACTION;				goto re2c_finish;					}
#line 1003 "<stdout>"
yy2_318:
		yych = *++source->cursor();
		if (yych == 'c') goto yy2_319;
		if (yych == 'f') goto yy2_320;
		goto yy2_3;
yy2_319:
		yych = *++source->cursor();
		if (yych == 'r') goto yy2_326;
		goto yy2_3;
yy2_320:
		yych = *++source->cursor();
		if (yych != 'a') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'u') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'l') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 't') goto yy2_3;
		++source->cursor();
#line 76 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_DEFAULT;						goto re2c_finish;					}
#line 1025 "<stdout>"
yy2_326:
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'm') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 't') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 's') goto yy2_3;
		++source->cursor();
#line 75 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_DECREMENTS;					goto re2c_finish;					}
#line 1042 "<stdout>"
yy2_334:
		yych = *++source->cursor();
		if (yych == 'n') goto yy2_343;
		goto yy2_3;
yy2_335:
		yych = *++source->cursor();
		if (yych != 'u') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 's') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		yych = *++source->cursor();
		if (yych == 'd') goto yy2_341;
		if (yych != 's') goto yy2_3;
		++source->cursor();
#line 72 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_CAUSES;						goto re2c_finish;					}
#line 1060 "<stdout>"
yy2_341:
		++source->cursor();
#line 71 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_CAUSED;						goto re2c_finish;					}
#line 1065 "<stdout>"
yy2_343:
		yych = *++source->cursor();
		if (yych != 's') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 't') goto yy2_3;
		yych = *++source->cursor();
		if (yych == 'a') goto yy2_347;
		if (yych != 'r') goto yy2_3;
		yych = *++source->cursor();
		if (yych == 'a') goto yy2_352;
		goto yy2_3;
yy2_347:
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 't') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 's') goto yy2_3;
		++source->cursor();
#line 73 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_CONSTANTS;					goto re2c_finish;					}
#line 1087 "<stdout>"
yy2_352:
		yych = *++source->cursor();
		if (yych != 'i') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 't') goto yy2_3;
		++source->cursor();
#line 74 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_CONSTRAINT;					goto re2c_finish;					}
#line 1098 "<stdout>"
yy2_357:
		++source->cursor();
#line 70 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_BY;							goto re2c_finish;					}
#line 1103 "<stdout>"
yy2_359:
		yych = *++source->cursor();
		if (yych == 'A') goto yy2_417;
		if (yych == 's') goto yy2_418;
		goto yy2_3;
yy2_360:
		yych = *++source->cursor();
		if (yych == 'l') goto yy2_411;
		if (yych == 'w') goto yy2_410;
		goto yy2_3;
yy2_361:
		yych = *++source->cursor();
		if (yych == 't') goto yy2_402;
		goto yy2_3;
yy2_362:
		yych = *++source->cursor();
		if (yych == 's') goto yy2_395;
		goto yy2_3;
yy2_363:
		yych = *++source->cursor();
		if (yych == 't') goto yy2_391;
		goto yy2_3;
yy2_364:
		yych = *++source->cursor();
		if (yych == 'd') goto yy2_371;
		goto yy2_3;
yy2_365:
		yych = *++source->cursor();
		if (yych != 't') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'i') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'o') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		++source->cursor();
#line 62 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_ACTION;						goto re2c_finish;					}
#line 1142 "<stdout>"
yy2_371:
		yych = *++source->cursor();
		if (yych != 'i') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 't') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'i') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'v') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		yych = *++source->cursor();
		if (yych == 'A') goto yy2_377;
		if (yych == 'F') goto yy2_378;
		goto yy2_3;
yy2_377:
		yych = *++source->cursor();
		if (yych == 'c') goto yy2_385;
		goto yy2_3;
yy2_378:
		yych = *++source->cursor();
		if (yych != 'l') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'u') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 't') goto yy2_3;
		++source->cursor();
#line 64 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_ADDITIVEFLUENT;				goto re2c_finish;					}
#line 1176 "<stdout>"
yy2_385:
		yych = *++source->cursor();
		if (yych != 't') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'i') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'o') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		++source->cursor();
#line 63 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_ADDITIVEACTION;				goto re2c_finish;					}
#line 1189 "<stdout>"
yy2_391:
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'r') goto yy2_3;
		++source->cursor();
#line 65 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_AFTER;						goto re2c_finish;					}
#line 1198 "<stdout>"
yy2_395:
		yych = *++source->cursor();
		if (yych != 'u') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'm') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'i') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'g') goto yy2_3;
		++source->cursor();
#line 67 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_ASSUMING;						goto re2c_finish;					}
#line 1213 "<stdout>"
yy2_402:
		yych = *++source->cursor();
		if (yych != 'r') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'i') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'b') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'u') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 't') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		++source->cursor();
#line 68 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_ATTRIBUTE;					goto re2c_finish;					}
#line 1230 "<stdout>"
yy2_410:
		yych = *++source->cursor();
		if (yych == 'a') goto yy2_413;
		goto yy2_3;
yy2_411:
		++source->cursor();
#line 69 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_ALL;							goto re2c_finish;					}
#line 1239 "<stdout>"
yy2_413:
		yych = *++source->cursor();
		if (yych != 'y') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 's') goto yy2_3;
		++source->cursor();
#line 66 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_ALWAYS;						goto re2c_finish;					}
#line 1248 "<stdout>"
yy2_417:
		yych = *++source->cursor();
		if (yych == 'c') goto yy2_420;
		goto yy2_3;
yy2_418:
		++source->cursor();
#line 106 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_ABS;							goto re2c_finish;					}
#line 1257 "<stdout>"
yy2_420:
		yych = *++source->cursor();
		if (yych != 't') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'i') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'o') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		++source->cursor();
#line 61 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_ABACTION;						goto re2c_finish;					}
#line 1270 "<stdout>"
	}
}
#line 119 "bcplus/parser/detail/Scanner.2.re2c"

	}
re2c_notkw:
	source->cursor() = source->token();
	return tokenize_3(source);

re2c_finish:
	u::ref_ptr<ReferencedString> str = new ReferencedString();
	if (ret != T_EOF) {
		str->assign(source->token(), (size_t)(source->cursor() - source->token()));
	} else {
		str->assign("<EOF>");
	}

	return new Token(ret, str, begin, source->loc());
}

}}}
