/* Generated by re2c 0.13.6 on Thu Jul 31 19:01:25 2014 */
#line 1 "bcplus/parser/detail/Scanner.2.re2c"

#include <sstream>

#include <boost/filesystem.hpp>
#include <boost/filesystem/fstream.hpp>

#include "bcplus/parser/detail/Scanner.h"
#include "bcplus/parser/detail/lemon_parser.h"

#include "bcplus/Location.h"
#include "bcplus/parser/Token.h"

#include "bcplus/parser/detail/ScannerSource.h"
#include "bcplus/parser/detail/ScannerRawSource.h"
#include "bcplus/parser/detail/ScannerTokenSource.h"
#include "bcplus/parser/detail/ScannerFileSource.h"
#include "bcplus/parser/detail/ScannerBufferSource.h"

namespace u = babb::utils; 
namespace fs = boost::filesystem;

namespace bcplus {
namespace parser {
namespace detail {

Token* Scanner::tokenize_2(ScannerRawSource* source) {
	if (source->eof()) return new Token(T_EOF, new ReferencedString("<EOF>"), source->loc(), source->loc());
	else if (!source->good()) return new Token(T_ERR_IO, new ReferencedString("<IO ERROR>"), source->loc(), source->loc());


	int ret;
	Location begin;

	begin = source->loc();
	source->token() = source->cursor();

	if (_cond == yycNORMAL) {
			
#line 42 "<stdout>"
{
	char yych;
	unsigned int yyaccept = 0;
	goto yyc_NORMAL;
/* *********************************** */
yyc_NORMAL:
	{
		static const unsigned char yybm[] = {
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0, 128,   0, 128, 128,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			128,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
		};
		if ((source->limit() - source->cursor()) < 20) source->fill(20);
		yych = *source->cursor();
		if (yych <= 'k') {
			if (yych <= 'c') {
				if (yych <= '`') {
					if (yych != '\n') goto yy2_4;
				} else {
					if (yych <= 'a') goto yy2_6;
					if (yych <= 'b') goto yy2_7;
					goto yy2_8;
				}
			} else {
				if (yych <= 'f') {
					if (yych <= 'd') goto yy2_9;
					if (yych <= 'e') goto yy2_10;
					goto yy2_11;
				} else {
					if (yych <= 'g') goto yy2_4;
					if (yych <= 'h') goto yy2_12;
					if (yych <= 'i') goto yy2_13;
					goto yy2_4;
				}
			}
		} else {
			if (yych <= 'q') {
				if (yych <= 'n') {
					if (yych <= 'l') goto yy2_14;
					if (yych <= 'm') goto yy2_15;
					goto yy2_16;
				} else {
					if (yych <= 'o') goto yy2_17;
					if (yych <= 'p') goto yy2_18;
					goto yy2_19;
				}
			} else {
				if (yych <= 't') {
					if (yych <= 'r') goto yy2_20;
					if (yych <= 's') goto yy2_21;
					goto yy2_22;
				} else {
					if (yych <= 'u') goto yy2_23;
					if (yych <= 'v') goto yy2_24;
					if (yych <= 'w') goto yy2_25;
					goto yy2_4;
				}
			}
		}
yy2_3:
		source->cursor() = source->marker();
		if (yyaccept <= 1) {
			if (yyaccept == 0) {
				goto yy2_5;
			} else {
				goto yy2_232;
			}
		} else {
			if (yyaccept == 2) {
				goto yy2_254;
			} else {
				goto yy2_295;
			}
		}
yy2_4:
		++source->cursor();
yy2_5:
#line 117 "bcplus/parser/detail/Scanner.2.re2c"
		{ goto re2c_notkw; }
#line 151 "<stdout>"
yy2_6:
		yyaccept = 0;
		yych = *(source->marker() = ++source->cursor());
		switch (yych) {
		case 'b':	goto yy2_363;
		case 'c':	goto yy2_369;
		case 'd':	goto yy2_368;
		case 'f':	goto yy2_367;
		case 'l':	goto yy2_364;
		case 's':	goto yy2_366;
		case 't':	goto yy2_365;
		default:	goto yy2_5;
		}
yy2_7:
		yych = *++source->cursor();
		if (yych == 'y') goto yy2_361;
		goto yy2_5;
yy2_8:
		yyaccept = 0;
		yych = *(source->marker() = ++source->cursor());
		if (yych == 'a') goto yy2_339;
		if (yych == 'o') goto yy2_338;
		goto yy2_5;
yy2_9:
		yyaccept = 0;
		yych = *(source->marker() = ++source->cursor());
		if (yych == 'e') goto yy2_322;
		goto yy2_5;
yy2_10:
		yyaccept = 0;
		yych = *(source->marker() = ++source->cursor());
		if (yych == 'q') goto yy2_284;
		if (yych == 'x') goto yy2_286;
		goto yy2_5;
yy2_11:
		yyaccept = 0;
		yych = *(source->marker() = ++source->cursor());
		if (yych == 'a') goto yy2_279;
		goto yy2_5;
yy2_12:
		yyaccept = 0;
		yych = *(source->marker() = ++source->cursor());
		if (yych == 'i') goto yy2_275;
		goto yy2_5;
yy2_13:
		yyaccept = 0;
		yych = *(source->marker() = ++source->cursor());
		if (yych <= 'l') {
			if (yych == 'f') goto yy2_231;
			goto yy2_5;
		} else {
			if (yych <= 'm') goto yy2_230;
			if (yych <= 'n') goto yy2_229;
			goto yy2_5;
		}
yy2_14:
		yyaccept = 0;
		yych = *(source->marker() = ++source->cursor());
		if (yych == 'a') goto yy2_224;
		goto yy2_5;
yy2_15:
		yyaccept = 0;
		yych = *(source->marker() = ++source->cursor());
		if (yych == 'a') goto yy2_185;
		if (yych == 'o') goto yy2_184;
		goto yy2_5;
yy2_16:
		yyaccept = 0;
		yych = *(source->marker() = ++source->cursor());
		if (yych == 'e') goto yy2_151;
		if (yych == 'o') goto yy2_150;
		goto yy2_5;
yy2_17:
		yyaccept = 0;
		yych = *(source->marker() = ++source->cursor());
		if (yych == 'b') goto yy2_143;
		if (yych == 'f') goto yy2_141;
		goto yy2_5;
yy2_18:
		yyaccept = 0;
		yych = *(source->marker() = ++source->cursor());
		if (yych == 'o') goto yy2_125;
		goto yy2_5;
yy2_19:
		yyaccept = 0;
		yych = *(source->marker() = ++source->cursor());
		if (yych == 'u') goto yy2_120;
		goto yy2_5;
yy2_20:
		yyaccept = 0;
		yych = *(source->marker() = ++source->cursor());
		if (yych == 'i') goto yy2_115;
		goto yy2_5;
yy2_21:
		yyaccept = 0;
		yych = *(source->marker() = ++source->cursor());
		switch (yych) {
		case 'd':	goto yy2_52;
		case 'h':	goto yy2_54;
		case 'i':	goto yy2_51;
		case 'o':	goto yy2_53;
		case 't':	goto yy2_50;
		default:	goto yy2_5;
		}
yy2_22:
		yyaccept = 0;
		yych = *(source->marker() = ++source->cursor());
		if (yych == 'r') goto yy2_46;
		goto yy2_5;
yy2_23:
		yyaccept = 0;
		yych = *(source->marker() = ++source->cursor());
		if (yych == 'n') goto yy2_40;
		goto yy2_5;
yy2_24:
		yyaccept = 0;
		yych = *(source->marker() = ++source->cursor());
		if (yych == 'a') goto yy2_31;
		goto yy2_5;
yy2_25:
		yyaccept = 0;
		yych = *(source->marker() = ++source->cursor());
		if (yych != 'h') goto yy2_5;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'r') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		++source->cursor();
#line 106 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_WHERE;						goto re2c_finish;					}
#line 284 "<stdout>"
yy2_31:
		yych = *++source->cursor();
		if (yych != 'r') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'i') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'a') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'b') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'l') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 's') goto yy2_3;
		++source->cursor();
#line 61 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_VARIABLES;					goto re2c_finish;					}
#line 303 "<stdout>"
yy2_40:
		yych = *++source->cursor();
		if (yych != 'l') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 's') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 's') goto yy2_3;
		++source->cursor();
#line 105 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_UNLESS;						goto re2c_finish;					}
#line 316 "<stdout>"
yy2_46:
		yych = *++source->cursor();
		if (yych != 'u') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		++source->cursor();
#line 113 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_TRUE;							goto re2c_finish;					}
#line 325 "<stdout>"
yy2_50:
		yych = *++source->cursor();
		if (yych == 'r') goto yy2_80;
		goto yy2_3;
yy2_51:
		yych = *++source->cursor();
		if (yych == 'm') goto yy2_69;
		goto yy2_3;
yy2_52:
		yych = *++source->cursor();
		if (yych == 'F') goto yy2_62;
		goto yy2_3;
yy2_53:
		yych = *++source->cursor();
		if (yych == 'r') goto yy2_58;
		goto yy2_3;
yy2_54:
		yych = *++source->cursor();
		if (yych != 'o') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'w') goto yy2_3;
		++source->cursor();
#line 58 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_SHOW;							goto re2c_finish;					}
#line 350 "<stdout>"
yy2_58:
		yych = *++source->cursor();
		if (yych != 't') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 's') goto yy2_3;
		++source->cursor();
#line 60 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_SORTS;						goto re2c_finish;					}
#line 359 "<stdout>"
yy2_62:
		yych = *++source->cursor();
		if (yych != 'l') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'u') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 't') goto yy2_3;
		++source->cursor();
#line 99 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_SDFLUENT;						goto re2c_finish;					}
#line 374 "<stdout>"
yy2_69:
		yych = *++source->cursor();
		if (yych != 'p') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'l') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'F') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'l') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'u') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 't') goto yy2_3;
		++source->cursor();
#line 100 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_SIMPLEFLUENT;					goto re2c_finish;					}
#line 397 "<stdout>"
yy2_80:
		yych = *++source->cursor();
		if (yych != 'o') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'g') goto yy2_3;
		yych = *++source->cursor();
		if (yych == '_') goto yy2_86;
		if (yych == 'n') goto yy2_3;
		goto yy2_85;
yy2_84:
		++source->cursor();
		if ((source->limit() - source->cursor()) < 13) source->fill(13);
		yych = *source->cursor();
yy2_85:
		if (yybm[0+yych] & 128) {
			goto yy2_84;
		}
		if (yych == 'n') goto yy2_101;
		goto yy2_3;
yy2_86:
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'o') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'c') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'o') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'c') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'u') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'r') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'r') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'c') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'y') goto yy2_3;
		++source->cursor();
#line 102 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_STRONG_NOCONCURRENCY;			goto re2c_finish;					}
#line 449 "<stdout>"
yy2_101:
		yych = *++source->cursor();
		if (yych != 'o') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'c') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'o') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'c') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'u') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'r') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'r') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'c') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'y') goto yy2_3;
		++source->cursor();
#line 101 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_STRONG_NOCONCURRENCY;			goto re2c_finish;					}
#line 478 "<stdout>"
yy2_115:
		yych = *++source->cursor();
		if (yych != 'g') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'i') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'd') goto yy2_3;
		++source->cursor();
#line 98 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_RIGID;						goto re2c_finish;					}
#line 489 "<stdout>"
yy2_120:
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'r') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'y') goto yy2_3;
		++source->cursor();
#line 57 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_QUERY;						goto re2c_finish;					}
#line 500 "<stdout>"
yy2_125:
		yych = *++source->cursor();
		if (yych != 's') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 's') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'i') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'b') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'l') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'y') goto yy2_3;
		yych = *++source->cursor();
		if (yych == 'c') goto yy2_3;
		goto yy2_133;
yy2_132:
		++source->cursor();
		if ((source->limit() - source->cursor()) < 6) source->fill(6);
		yych = *source->cursor();
yy2_133:
		if (yych <= '\f') {
			if (yych == '\t') goto yy2_132;
			if (yych <= '\n') goto yy2_3;
			goto yy2_132;
		} else {
			if (yych <= ' ') {
				if (yych <= 0x1F) goto yy2_3;
				goto yy2_132;
			} else {
				if (yych != 'c') goto yy2_3;
			}
		}
		yych = *++source->cursor();
		if (yych != 'a') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'u') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 's') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'd') goto yy2_3;
		++source->cursor();
#line 97 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_POSSIBLY_CAUSED;				goto re2c_finish;					}
#line 547 "<stdout>"
yy2_141:
		++source->cursor();
#line 96 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_OF;							goto re2c_finish;					}
#line 552 "<stdout>"
yy2_143:
		yych = *++source->cursor();
		if (yych != 'j') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'c') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 't') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 's') goto yy2_3;
		++source->cursor();
#line 56 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_OBJECTS;						goto re2c_finish;					}
#line 567 "<stdout>"
yy2_150:
		yych = *++source->cursor();
		if (yych <= 'm') {
			if (yych == 'c') goto yy2_158;
			goto yy2_3;
		} else {
			if (yych <= 'n') goto yy2_159;
			if (yych == 't') goto yy2_160;
			goto yy2_3;
		}
yy2_151:
		yych = *++source->cursor();
		if (yych == 'q') goto yy2_153;
		if (yych != 'v') goto yy2_3;
		yych = *++source->cursor();
		if (yych == 'e') goto yy2_155;
		goto yy2_3;
yy2_153:
		++source->cursor();
#line 111 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_NEQ;							goto re2c_finish;					}
#line 589 "<stdout>"
yy2_155:
		yych = *++source->cursor();
		if (yych != 'r') goto yy2_3;
		++source->cursor();
#line 93 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_NEVER;						goto re2c_finish;					}
#line 596 "<stdout>"
yy2_158:
		yych = *++source->cursor();
		if (yych == 'o') goto yy2_173;
		goto yy2_3;
yy2_159:
		yych = *++source->cursor();
		if (yych == 'e') goto yy2_162;
		goto yy2_3;
yy2_160:
		++source->cursor();
#line 112 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_NOT;							goto re2c_finish;					}
#line 609 "<stdout>"
yy2_162:
		yych = *++source->cursor();
		if (yych != 'x') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'c') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'u') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 't') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'a') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'b') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'l') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		++source->cursor();
#line 95 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_NONEXECUTABLE;				goto re2c_finish;					}
#line 632 "<stdout>"
yy2_173:
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'c') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'u') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'r') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'r') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'c') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'y') goto yy2_3;
		++source->cursor();
#line 94 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_NOCONCURRENCY;				goto re2c_finish;					}
#line 655 "<stdout>"
yy2_184:
		yych = *++source->cursor();
		if (yych == 'd') goto yy2_222;
		goto yy2_3;
yy2_185:
		yych = *++source->cursor();
		if (yych <= 'w') {
			if (yych != 'c') goto yy2_3;
		} else {
			if (yych <= 'x') goto yy2_188;
			if (yych <= 'y') goto yy2_187;
			goto yy2_3;
		}
		yych = *++source->cursor();
		if (yych == 'r') goto yy2_218;
		goto yy2_3;
yy2_187:
		yych = *++source->cursor();
		if (yych == 'c') goto yy2_3;
		goto yy2_211;
yy2_188:
		yych = *++source->cursor();
		if (yych == 'A') goto yy2_190;
		if (yych != 's') goto yy2_3;
		yych = *++source->cursor();
		if (yych == 't') goto yy2_206;
		goto yy2_3;
yy2_190:
		yych = *++source->cursor();
		if (yych == 'F') goto yy2_192;
		if (yych != 'd') goto yy2_3;
		yych = *++source->cursor();
		if (yych == 'd') goto yy2_199;
		goto yy2_3;
yy2_192:
		yych = *++source->cursor();
		if (yych != 'V') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'a') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'l') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'u') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		++source->cursor();
#line 91 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_MAXAFVALUE;					goto re2c_finish;					}
#line 704 "<stdout>"
yy2_199:
		yych = *++source->cursor();
		if (yych != 'i') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 't') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'i') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'v') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		++source->cursor();
#line 90 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_MAXADDITIVE;					goto re2c_finish;					}
#line 719 "<stdout>"
yy2_206:
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'p') goto yy2_3;
		++source->cursor();
#line 92 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_MAXSTEP;						goto re2c_finish;					}
#line 728 "<stdout>"
yy2_210:
		++source->cursor();
		if ((source->limit() - source->cursor()) < 5) source->fill(5);
		yych = *source->cursor();
yy2_211:
		if (yych <= '\f') {
			if (yych == '\t') goto yy2_210;
			if (yych <= '\n') goto yy2_3;
			goto yy2_210;
		} else {
			if (yych <= ' ') {
				if (yych <= 0x1F) goto yy2_3;
				goto yy2_210;
			} else {
				if (yych != 'c') goto yy2_3;
			}
		}
		yych = *++source->cursor();
		if (yych != 'a') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'u') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 's') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		++source->cursor();
#line 89 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_MAY_CAUSE;					goto re2c_finish;					}
#line 757 "<stdout>"
yy2_218:
		yych = *++source->cursor();
		if (yych != 'o') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 's') goto yy2_3;
		++source->cursor();
#line 55 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_MACROS; _in_macro = true;		goto re2c_finish;					}
#line 766 "<stdout>"
yy2_222:
		++source->cursor();
#line 110 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_MOD;							goto re2c_finish;					}
#line 771 "<stdout>"
yy2_224:
		yych = *++source->cursor();
		if (yych != 'b') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'l') goto yy2_3;
		++source->cursor();
#line 88 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_LABEL;						goto re2c_finish;					}
#line 782 "<stdout>"
yy2_229:
		yych = *++source->cursor();
		if (yych == 'c') goto yy2_247;
		if (yych == 'e') goto yy2_248;
		goto yy2_3;
yy2_230:
		yych = *++source->cursor();
		if (yych == 'p') goto yy2_238;
		goto yy2_3;
yy2_231:
		yyaccept = 1;
		yych = *(source->marker() = ++source->cursor());
		if (yych == 'c') goto yy2_233;
yy2_232:
#line 82 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_IF;							goto re2c_finish;					}
#line 799 "<stdout>"
yy2_233:
		yych = *++source->cursor();
		if (yych != 'o') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 's') goto yy2_3;
		++source->cursor();
#line 83 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_IFCONS;						goto re2c_finish;					}
#line 810 "<stdout>"
yy2_238:
		yych = *++source->cursor();
		if (yych != 'o') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 's') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 's') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'i') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'b') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'l') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		++source->cursor();
#line 84 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_IMPOSSIBLE;					goto re2c_finish;					}
#line 829 "<stdout>"
yy2_247:
		yych = *++source->cursor();
		if (yych == 'l') goto yy2_263;
		if (yych == 'r') goto yy2_262;
		goto yy2_3;
yy2_248:
		yych = *++source->cursor();
		if (yych != 'r') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 't') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'i') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'a') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'l') goto yy2_3;
		yyaccept = 2;
		yych = *(source->marker() = ++source->cursor());
		if (yych == 'F') goto yy2_255;
yy2_254:
#line 86 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_INERTIAL;						goto re2c_finish;					}
#line 852 "<stdout>"
yy2_255:
		yych = *++source->cursor();
		if (yych != 'l') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'u') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 't') goto yy2_3;
		++source->cursor();
#line 87 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_INERTIALFLUENT;				goto re2c_finish;					}
#line 867 "<stdout>"
yy2_262:
		yych = *++source->cursor();
		if (yych == 'e') goto yy2_268;
		goto yy2_3;
yy2_263:
		yych = *++source->cursor();
		if (yych != 'u') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'd') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		++source->cursor();
#line 54 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_INCLUDE;						goto re2c_finish;					}
#line 882 "<stdout>"
yy2_268:
		yych = *++source->cursor();
		if (yych != 'm') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 't') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 's') goto yy2_3;
		++source->cursor();
#line 85 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_INCREMENTS;					goto re2c_finish;					}
#line 897 "<stdout>"
yy2_275:
		yych = *++source->cursor();
		if (yych != 'd') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		++source->cursor();
#line 59 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_HIDE;							goto re2c_finish;					}
#line 906 "<stdout>"
yy2_279:
		yych = *++source->cursor();
		if (yych != 'l') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 's') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		++source->cursor();
#line 109 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_FALSE;						goto re2c_finish;					}
#line 917 "<stdout>"
yy2_284:
		++source->cursor();
#line 108 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_EQ;							goto re2c_finish;					}
#line 922 "<stdout>"
yy2_286:
		yych = *++source->cursor();
		if (yych == 'o') goto yy2_288;
		if (yych != 't') goto yy2_3;
		yych = *++source->cursor();
		if (yych == 'e') goto yy2_303;
		goto yy2_3;
yy2_288:
		yych = *++source->cursor();
		if (yych != 'g') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'o') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'u') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 's') goto yy2_3;
		yyaccept = 3;
		yych = *(source->marker() = ++source->cursor());
		if (yych == 'A') goto yy2_296;
yy2_295:
#line 80 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_EXOGENOUS;					goto re2c_finish;					}
#line 949 "<stdout>"
yy2_296:
		yych = *++source->cursor();
		if (yych != 'c') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 't') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'i') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'o') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		++source->cursor();
#line 81 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_EXOGENOUSACTION;				goto re2c_finish;					}
#line 964 "<stdout>"
yy2_303:
		yych = *++source->cursor();
		if (yych != 'r') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'a') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'l') goto yy2_3;
		yych = *++source->cursor();
		if (yych == 'A') goto yy2_308;
		if (yych == 'F') goto yy2_309;
		goto yy2_3;
yy2_308:
		yych = *++source->cursor();
		if (yych == 'c') goto yy2_316;
		goto yy2_3;
yy2_309:
		yych = *++source->cursor();
		if (yych != 'l') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'u') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 't') goto yy2_3;
		++source->cursor();
#line 79 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_EXTERNALFLUENT;				goto re2c_finish;					}
#line 996 "<stdout>"
yy2_316:
		yych = *++source->cursor();
		if (yych != 't') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'i') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'o') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		++source->cursor();
#line 78 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_EXTERNALACTION;				goto re2c_finish;					}
#line 1009 "<stdout>"
yy2_322:
		yych = *++source->cursor();
		if (yych == 'c') goto yy2_323;
		if (yych == 'f') goto yy2_324;
		goto yy2_3;
yy2_323:
		yych = *++source->cursor();
		if (yych == 'r') goto yy2_330;
		goto yy2_3;
yy2_324:
		yych = *++source->cursor();
		if (yych != 'a') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'u') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'l') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 't') goto yy2_3;
		++source->cursor();
#line 77 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_DEFAULT;						goto re2c_finish;					}
#line 1031 "<stdout>"
yy2_330:
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'm') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 't') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 's') goto yy2_3;
		++source->cursor();
#line 76 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_DECREMENTS;					goto re2c_finish;					}
#line 1048 "<stdout>"
yy2_338:
		yych = *++source->cursor();
		if (yych == 'n') goto yy2_347;
		goto yy2_3;
yy2_339:
		yych = *++source->cursor();
		if (yych != 'u') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 's') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		yych = *++source->cursor();
		if (yych == 'd') goto yy2_345;
		if (yych != 's') goto yy2_3;
		++source->cursor();
#line 73 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_CAUSES;						goto re2c_finish;					}
#line 1066 "<stdout>"
yy2_345:
		++source->cursor();
#line 72 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_CAUSED;						goto re2c_finish;					}
#line 1071 "<stdout>"
yy2_347:
		yych = *++source->cursor();
		if (yych != 's') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 't') goto yy2_3;
		yych = *++source->cursor();
		if (yych == 'a') goto yy2_351;
		if (yych != 'r') goto yy2_3;
		yych = *++source->cursor();
		if (yych == 'a') goto yy2_356;
		goto yy2_3;
yy2_351:
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 't') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 's') goto yy2_3;
		++source->cursor();
#line 74 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_CONSTANTS;					goto re2c_finish;					}
#line 1093 "<stdout>"
yy2_356:
		yych = *++source->cursor();
		if (yych != 'i') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 't') goto yy2_3;
		++source->cursor();
#line 75 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_CONSTRAINT;					goto re2c_finish;					}
#line 1104 "<stdout>"
yy2_361:
		++source->cursor();
#line 71 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_BY;							goto re2c_finish;					}
#line 1109 "<stdout>"
yy2_363:
		yych = *++source->cursor();
		if (yych == 'A') goto yy2_421;
		if (yych == 's') goto yy2_422;
		goto yy2_3;
yy2_364:
		yych = *++source->cursor();
		if (yych == 'l') goto yy2_415;
		if (yych == 'w') goto yy2_414;
		goto yy2_3;
yy2_365:
		yych = *++source->cursor();
		if (yych == 't') goto yy2_406;
		goto yy2_3;
yy2_366:
		yych = *++source->cursor();
		if (yych == 's') goto yy2_399;
		goto yy2_3;
yy2_367:
		yych = *++source->cursor();
		if (yych == 't') goto yy2_395;
		goto yy2_3;
yy2_368:
		yych = *++source->cursor();
		if (yych == 'd') goto yy2_375;
		goto yy2_3;
yy2_369:
		yych = *++source->cursor();
		if (yych != 't') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'i') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'o') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		++source->cursor();
#line 63 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_ACTION;						goto re2c_finish;					}
#line 1148 "<stdout>"
yy2_375:
		yych = *++source->cursor();
		if (yych != 'i') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 't') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'i') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'v') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		yych = *++source->cursor();
		if (yych == 'A') goto yy2_381;
		if (yych == 'F') goto yy2_382;
		goto yy2_3;
yy2_381:
		yych = *++source->cursor();
		if (yych == 'c') goto yy2_389;
		goto yy2_3;
yy2_382:
		yych = *++source->cursor();
		if (yych != 'l') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'u') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 't') goto yy2_3;
		++source->cursor();
#line 65 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_ADDITIVEFLUENT;				goto re2c_finish;					}
#line 1182 "<stdout>"
yy2_389:
		yych = *++source->cursor();
		if (yych != 't') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'i') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'o') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		++source->cursor();
#line 64 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_ADDITIVEACTION;				goto re2c_finish;					}
#line 1195 "<stdout>"
yy2_395:
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'r') goto yy2_3;
		++source->cursor();
#line 66 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_AFTER;						goto re2c_finish;					}
#line 1204 "<stdout>"
yy2_399:
		yych = *++source->cursor();
		if (yych != 'u') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'm') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'i') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'g') goto yy2_3;
		++source->cursor();
#line 68 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_ASSUMING;						goto re2c_finish;					}
#line 1219 "<stdout>"
yy2_406:
		yych = *++source->cursor();
		if (yych != 'r') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'i') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'b') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'u') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 't') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		++source->cursor();
#line 69 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_ATTRIBUTE;					goto re2c_finish;					}
#line 1236 "<stdout>"
yy2_414:
		yych = *++source->cursor();
		if (yych == 'a') goto yy2_417;
		goto yy2_3;
yy2_415:
		++source->cursor();
#line 70 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_ALL;							goto re2c_finish;					}
#line 1245 "<stdout>"
yy2_417:
		yych = *++source->cursor();
		if (yych != 'y') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 's') goto yy2_3;
		++source->cursor();
#line 67 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_ALWAYS;						goto re2c_finish;					}
#line 1254 "<stdout>"
yy2_421:
		yych = *++source->cursor();
		if (yych == 'c') goto yy2_424;
		goto yy2_3;
yy2_422:
		++source->cursor();
#line 107 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_ABS;							goto re2c_finish;					}
#line 1263 "<stdout>"
yy2_424:
		yych = *++source->cursor();
		if (yych != 't') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'i') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'o') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		++source->cursor();
#line 62 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_ABACTION;						goto re2c_finish;					}
#line 1276 "<stdout>"
	}
}
#line 119 "bcplus/parser/detail/Scanner.2.re2c"

	}
re2c_notkw:
	source->cursor() = source->token();
	return tokenize_3(source);

re2c_finish:
	u::ref_ptr<ReferencedString> str = new ReferencedString();
	if (ret != T_EOF) {
		str->assign(source->token(), (size_t)(source->cursor() - source->token()));
	} else {
		str->assign("<EOF>");
	}

	return new Token(ret, str, begin, source->loc());
}

}}}
