/* Generated by re2c 0.13.6 on Fri May  9 12:23:18 2014 */
#line 1 "bcplus/parser/detail/Scanner.3.re2c"

#include <sstream>

#include <boost/filesystem.hpp>
#include <boost/filesystem/fstream.hpp>

#include "bcplus/parser/detail/Scanner.h"
#include "bcplus/parser/detail/lemon_parser.h"

#include "bcplus/Location.h"
#include "bcplus/parser/Token.h"

#include "bcplus/parser/detail/ScannerSource.h"
#include "bcplus/parser/detail/ScannerRawSource.h"
#include "bcplus/parser/detail/ScannerTokenSource.h"
#include "bcplus/parser/detail/ScannerFileSource.h"
#include "bcplus/parser/detail/ScannerBufferSource.h"

namespace u = babb::utils; 
namespace fs = boost::filesystem;

namespace bcplus {
namespace parser {
namespace detail {


#define BLK_INIT \
	blk.str(""); \
	use_blk = true; \
	source->token() = source->cursor();

#define BLK_LINE \
	source->newline(); \
    blk.write(source->token(), (size_t)(source->cursor() - source->token())); \
	source->token() = source->cursor();		

#define BLK_FINISH(sz) \
	blk.write(source->token(), (size_t)(source->cursor() - source->token() - sz));

Token* Scanner::tokenize_3(ScannerRawSource* source) {
	if (source->eof()) return new Token(T_EOF, new ReferencedString("<EOF>"), source->loc(), source->loc());
	else if (!source->good()) return new Token(T_ERR_IO, new ReferencedString("<IO ERROR>"), source->loc(), source->loc());


	std::stringstream blk;
	int ret;
	Location begin;
	bool use_blk = false;
	size_t preskip = 0;
	size_t postskip = 0;

	int parens = 0;
	bool dbl_quote = false;
	bool sgl_quote = false;
	bool ln_cmt = false;
	bool blk_cmt = false;
	static bool repeat = false;

	char const* marker = NULL;

	marker = source->token() = source->cursor();
	begin = source->loc();

	
#line 68 "<stdout>"
{
	char yych;
	unsigned int yyaccept = 0;
	if (_cond < 6) {
		if (_cond < 3) {
			if (_cond < 1) {
				goto yyc_NORMAL;
			} else {
				if (_cond < 2) {
					goto yyc_DBL_STRING;
				} else {
					goto yyc_SGL_STRING;
				}
			}
		} else {
			if (_cond < 4) {
				goto yyc_ASP_GR;
			} else {
				if (_cond < 5) {
					goto yyc_ASP_CP;
				} else {
					goto yyc_LUA_GR;
				}
			}
		}
	} else {
		if (_cond < 9) {
			if (_cond < 7) {
				goto yyc_LUA_CP;
			} else {
				if (_cond < 8) {
					goto yyc_F2LP_GR;
				} else {
					goto yyc_F2LP_CP;
				}
			}
		} else {
			if (_cond < 11) {
				if (_cond < 10) {
					goto yyc_ARG;
				} else {
					goto yyc_MACRO;
				}
			} else {
				if (_cond < 12) {
					goto yyc_BLK_COMMENT;
				} else {
					goto yyc_COMMENT;
				}
			}
		}
	}
/* *********************************** */
yyc_ARG:
	if ((source->limit() - source->cursor()) < 2) source->fill(2);
	yych = *source->cursor();
	if (yych <= '&') {
		if (yych <= '!') {
			if (yych <= 0x00) goto yy3_3;
			if (yych == '\n') goto yy3_21;
			goto yy3_5;
		} else {
			if (yych <= '"') goto yy3_7;
			if (yych == '%') goto yy3_9;
			goto yy3_5;
		}
	} else {
		if (yych <= '*') {
			if (yych <= '\'') goto yy3_11;
			if (yych <= '(') goto yy3_13;
			if (yych <= ')') goto yy3_15;
			goto yy3_17;
		} else {
			if (yych <= ',') {
				if (yych <= '+') goto yy3_5;
				goto yy3_18;
			} else {
				if (yych == '/') goto yy3_20;
				goto yy3_5;
			}
		}
	}
yy3_3:
	++source->cursor();
#line 574 "bcplus/parser/detail/Scanner.3.re2c"
	{
													// Figure out why we're still here...
													if (parens > 0 ) {
														_cond = yycNORMAL;
														ret = T_ERR_PAREN_MISMATCH;
													} else if (sgl_quote || dbl_quote) {
														_cond = yycNORMAL;
														ret = T_ERR_UNTERMINATED_STRING;
													}else {
														_cond = yycNORMAL;
														ret = T_ERR_SYNTAX;
													}
													goto re2c_finish;
												}
#line 168 "<stdout>"
yy3_5:
	++source->cursor();
yy3_6:
#line 588 "bcplus/parser/detail/Scanner.3.re2c"
	{ 												goto yyc_ARG;						}
#line 174 "<stdout>"
yy3_7:
	++source->cursor();
#line 566 "bcplus/parser/detail/Scanner.3.re2c"
	{ 
												  if (!sgl_quote && !ln_cmt && !blk_cmt) dbl_quote = !dbl_quote;		
												  goto yyc_ARG;						
												}
#line 182 "<stdout>"
yy3_9:
	++source->cursor();
#line 510 "bcplus/parser/detail/Scanner.3.re2c"
	{
												  if (!blk_cmt && !sgl_quote && !dbl_quote) ln_cmt = true;		
												  goto yyc_ARG;
												}
#line 190 "<stdout>"
yy3_11:
	++source->cursor();
#line 570 "bcplus/parser/detail/Scanner.3.re2c"
	{ 
												  if (!dbl_quote && !ln_cmt && !blk_cmt) sgl_quote = !sgl_quote;		
												  goto yyc_ARG;						
												}
#line 198 "<stdout>"
yy3_13:
	++source->cursor();
#line 523 "bcplus/parser/detail/Scanner.3.re2c"
	{ 
												  if (sgl_quote || dbl_quote || ln_cmt || blk_cmt) goto yyc_ARG;
												  if (!parens++) {
												  	ret = T_PAREN_L;						
													goto re2c_finish;
												  } 

												  goto yyc_ARG;
												}
#line 211 "<stdout>"
yy3_15:
	++source->cursor();
#line 532 "bcplus/parser/detail/Scanner.3.re2c"
	{
												  if (sgl_quote || dbl_quote || ln_cmt || blk_cmt) goto yyc_ARG;
												  if (repeat) {
													// 2nd end paren
													repeat = false;
												    ret = T_PAREN_R;
													_cond = yycNORMAL;
													goto re2c_finish;
				
												  } else if (--parens <= 0) {
													// first end paren
													repeat = true;
													source->cursor()--;
													ret = T_ARG;
													goto re2c_finish;
												  }

												  goto yyc_ARG;
												}
#line 234 "<stdout>"
yy3_17:
	yych = *++source->cursor();
	if (yych == '/') goto yy3_25;
	goto yy3_6;
yy3_18:
	++source->cursor();
#line 551 "bcplus/parser/detail/Scanner.3.re2c"
	{
												  if (sgl_quote || dbl_quote || ln_cmt || blk_cmt) goto yyc_ARG;
												  if (repeat) {
													// 2nd comma
													repeat = false;
													ret = T_COMMA;
													goto re2c_finish;
												  } else {
													// first comma
													repeat = true;
													source->cursor()--;
													ret = T_ARG;
													goto re2c_finish;
												  }								  
												}
#line 257 "<stdout>"
yy3_20:
	yych = *++source->cursor();
	if (yych == '*') goto yy3_23;
	goto yy3_6;
yy3_21:
	++source->cursor();
#line 505 "bcplus/parser/detail/Scanner.3.re2c"
	{
												  source->newline();
												  ln_cmt = false;
												  goto yyc_ARG;
												}
#line 270 "<stdout>"
yy3_23:
	++source->cursor();
#line 514 "bcplus/parser/detail/Scanner.3.re2c"
	{
												  if (!ln_cmt && !sgl_quote && !dbl_quote) blk_cmt = true;
												  goto yyc_ARG;
												}
#line 278 "<stdout>"
yy3_25:
	++source->cursor();
#line 518 "bcplus/parser/detail/Scanner.3.re2c"
	{
												  blk_cmt = false;
												  goto yyc_ARG;
												}
#line 286 "<stdout>"
/* *********************************** */
yyc_ASP_CP:
	{
		static const unsigned char yybm[] = {
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0, 128,   0, 128, 128,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			128,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
		};
		if ((source->limit() - source->cursor()) < 2) source->fill(2);
		yych = *source->cursor();
		if (yych <= '$') {
			if (yych <= '\n') {
				if (yych <= 0x00) goto yy3_29;
				if (yych <= '\t') goto yy3_31;
				goto yy3_40;
			} else {
				if (yych == '"') goto yy3_33;
				goto yy3_31;
			}
		} else {
			if (yych <= '\'') {
				if (yych <= '%') goto yy3_35;
				if (yych <= '&') goto yy3_31;
				goto yy3_37;
			} else {
				if (yych == ':') goto yy3_39;
				goto yy3_31;
			}
		}
yy3_29:
		++source->cursor();
#line 311 "bcplus/parser/detail/Scanner.3.re2c"
		{ 
												  BLK_FINISH(1);
												  ret = T_ERR_UNTERMINATED_ASP;			
												  _cond = yycNORMAL;
												  source->cursor()--;
												  goto re2c_finish;					
												}
#line 355 "<stdout>"
yy3_31:
		++source->cursor();
yy3_32:
#line 318 "bcplus/parser/detail/Scanner.3.re2c"
		{												goto yyc_ASP_CP;					}
#line 361 "<stdout>"
yy3_33:
		++source->cursor();
#line 284 "bcplus/parser/detail/Scanner.3.re2c"
		{
												  if (!sgl_quote && !ln_cmt && !blk_cmt) dbl_quote = !dbl_quote;
												  goto yyc_ASP_CP;
												}
#line 369 "<stdout>"
yy3_35:
		++source->cursor();
#line 288 "bcplus/parser/detail/Scanner.3.re2c"
		{
												  if (!blk_cmt && !sgl_quote && !dbl_quote) ln_cmt = true;
												  goto yyc_ASP_CP;
												}
#line 377 "<stdout>"
yy3_37:
		++source->cursor();
#line 280 "bcplus/parser/detail/Scanner.3.re2c"
		{
												  if (!dbl_quote && !ln_cmt && !blk_cmt) sgl_quote = !sgl_quote;
												  goto yyc_ASP_CP;
												}
#line 385 "<stdout>"
yy3_39:
		yyaccept = 0;
		yych = *(source->marker() = ++source->cursor());
		if (yych == '-') goto yy3_42;
		goto yy3_32;
yy3_40:
		++source->cursor();
#line 275 "bcplus/parser/detail/Scanner.3.re2c"
		{ 
												  BLK_LINE;
												  ln_cmt = false;
												  goto yyc_ASP_CP;					
												}
#line 399 "<stdout>"
yy3_42:
		++source->cursor();
		if ((source->limit() - source->cursor()) < 7) source->fill(7);
		yych = *source->cursor();
		if (yybm[0+yych] & 128) {
			goto yy3_42;
		}
		if (yych == 'e') goto yy3_45;
yy3_44:
		source->cursor() = source->marker();
		goto yy3_32;
yy3_45:
		yych = *++source->cursor();
		if (yych != 'n') goto yy3_44;
		yych = *++source->cursor();
		if (yych != 'd') goto yy3_44;
		yych = *++source->cursor();
		if (yych == '_') goto yy3_50;
		if (yych == 'a') goto yy3_44;
		goto yy3_49;
yy3_48:
		++source->cursor();
		if ((source->limit() - source->cursor()) < 3) source->fill(3);
		yych = *source->cursor();
yy3_49:
		if (yych <= '\f') {
			if (yych == '\t') goto yy3_48;
			if (yych <= '\n') goto yy3_44;
			goto yy3_48;
		} else {
			if (yych <= ' ') {
				if (yych <= 0x1F) goto yy3_44;
				goto yy3_48;
			} else {
				if (yych == 'a') goto yy3_57;
				goto yy3_44;
			}
		}
yy3_50:
		yych = *++source->cursor();
		if (yych != 'a') goto yy3_44;
		yych = *++source->cursor();
		if (yych != 's') goto yy3_44;
		yych = *++source->cursor();
		if (yych != 'p') goto yy3_44;
yy3_53:
		++source->cursor();
		if (source->limit() <= source->cursor()) source->fill(1);
		yych = *source->cursor();
		if (yych <= '\f') {
			if (yych == '\t') goto yy3_53;
			if (yych <= '\n') goto yy3_44;
			goto yy3_53;
		} else {
			if (yych <= ' ') {
				if (yych <= 0x1F) goto yy3_44;
				goto yy3_53;
			} else {
				if (yych != '.') goto yy3_44;
			}
		}
		++source->cursor();
#line 294 "bcplus/parser/detail/Scanner.3.re2c"
		{ 
												  if (!ln_cmt && !blk_cmt && !sgl_quote && !dbl_quote) {
												 	 _cond = yycNORMAL; 
												 	 ret = T_ASP_CP; 
												 	 goto re2c_finish;					
												  } else goto yyc_ASP_CP;
												}
#line 470 "<stdout>"
yy3_57:
		yych = *++source->cursor();
		if (yych != 's') goto yy3_44;
		yych = *++source->cursor();
		if (yych != 'p') goto yy3_44;
yy3_59:
		++source->cursor();
		if (source->limit() <= source->cursor()) source->fill(1);
		yych = *source->cursor();
		if (yych <= '\f') {
			if (yych == '\t') goto yy3_59;
			if (yych <= '\n') goto yy3_44;
			goto yy3_59;
		} else {
			if (yych <= ' ') {
				if (yych <= 0x1F) goto yy3_44;
				goto yy3_59;
			} else {
				if (yych != '.') goto yy3_44;
			}
		}
		++source->cursor();
#line 302 "bcplus/parser/detail/Scanner.3.re2c"
		{ 
												  if (!ln_cmt && !blk_cmt && !sgl_quote && !dbl_quote) {
												 	 _cond = yycNORMAL; 
												 	 ret = T_ASP_CP; 
												 	 goto re2c_finish;					
												  } else goto yyc_ASP_CP;
												}
#line 501 "<stdout>"
	}
/* *********************************** */
yyc_ASP_GR:
	{
		static const unsigned char yybm[] = {
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0, 128,   0, 128, 128,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			128,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
		};
		if ((source->limit() - source->cursor()) < 8) source->fill(8);
		yych = *source->cursor();
		if (yych <= '"') {
			if (yych <= '\t') {
				if (yych >= 0x01) goto yy3_67;
			} else {
				if (yych <= '\n') goto yy3_76;
				if (yych <= '!') goto yy3_67;
				goto yy3_69;
			}
		} else {
			if (yych <= '%') {
				if (yych <= '#') goto yy3_71;
				if (yych <= '$') goto yy3_67;
				goto yy3_72;
			} else {
				if (yych == '\'') goto yy3_74;
				goto yy3_67;
			}
		}
		++source->cursor();
#line 266 "bcplus/parser/detail/Scanner.3.re2c"
		{ 
												  BLK_FINISH(1);
												  ret = T_ERR_UNTERMINATED_ASP;			
												  _cond = yycNORMAL;
												  source->cursor()--;
												  goto re2c_finish;					
												}
#line 569 "<stdout>"
yy3_67:
		++source->cursor();
yy3_68:
#line 273 "bcplus/parser/detail/Scanner.3.re2c"
		{												goto yyc_ASP_GR;					}
#line 575 "<stdout>"
yy3_69:
		++source->cursor();
#line 251 "bcplus/parser/detail/Scanner.3.re2c"
		{
												  if (!sgl_quote && !ln_cmt && !blk_cmt) dbl_quote = !dbl_quote;
												  goto yyc_ASP_GR;
												}
#line 583 "<stdout>"
yy3_71:
		yyaccept = 0;
		yych = *(source->marker() = ++source->cursor());
		if (yych == 'e') goto yy3_78;
		goto yy3_68;
yy3_72:
		++source->cursor();
#line 255 "bcplus/parser/detail/Scanner.3.re2c"
		{
												  if (!blk_cmt && !sgl_quote && !dbl_quote) ln_cmt = true;
												  goto yyc_ASP_GR;
												}
#line 596 "<stdout>"
yy3_74:
		++source->cursor();
#line 247 "bcplus/parser/detail/Scanner.3.re2c"
		{
												  if (!dbl_quote && !ln_cmt && !blk_cmt) sgl_quote = !sgl_quote;
												  goto yyc_ASP_GR;
												}
#line 604 "<stdout>"
yy3_76:
		++source->cursor();
#line 242 "bcplus/parser/detail/Scanner.3.re2c"
		{ 
									 			  BLK_LINE;
												  ln_cmt = false;
												  goto yyc_ASP_GR;				
												}
#line 613 "<stdout>"
yy3_78:
		yych = *++source->cursor();
		if (yych == 'n') goto yy3_80;
yy3_79:
		source->cursor() = source->marker();
		goto yy3_68;
yy3_80:
		yych = *++source->cursor();
		if (yych != 'd') goto yy3_79;
		yych = *++source->cursor();
		if (yych != '_') goto yy3_79;
		yych = *++source->cursor();
		if (yych != 'a') goto yy3_79;
		yych = *++source->cursor();
		if (yych != 's') goto yy3_79;
		yych = *++source->cursor();
		if (yych != 'p') goto yy3_79;
yy3_85:
		++source->cursor();
		if (source->limit() <= source->cursor()) source->fill(1);
		yych = *source->cursor();
		if (yybm[0+yych] & 128) {
			goto yy3_85;
		}
		if (yych != '.') goto yy3_79;
		++source->cursor();
#line 259 "bcplus/parser/detail/Scanner.3.re2c"
		{ 
												  if (!ln_cmt && !blk_cmt && !sgl_quote && !dbl_quote) {
										 		    _cond = yycNORMAL; 
										 		    ret = T_ASP_GR; 
										 		    goto re2c_finish;					
												  } else goto yyc_ASP_GR;
												}
#line 648 "<stdout>"
	}
/* *********************************** */
yyc_BLK_COMMENT:
	if (source->limit() <= source->cursor()) source->fill(1);
	yych = *source->cursor();
	if (yych != '\n') goto yy3_92;
yy3_92:
	++source->cursor();
#line 634 "bcplus/parser/detail/Scanner.3.re2c"
	{ ret = T_ERR_UNKNOWN_SYMBOL;					goto re2c_finish;					}
#line 659 "<stdout>"
/* *********************************** */
yyc_COMMENT:
	if (source->limit() <= source->cursor()) source->fill(1);
	yych = *source->cursor();
	if (yych != '\n') goto yy3_97;
yy3_97:
	++source->cursor();
#line 634 "bcplus/parser/detail/Scanner.3.re2c"
	{ ret = T_ERR_UNKNOWN_SYMBOL;					goto re2c_finish;					}
#line 669 "<stdout>"
/* *********************************** */
yyc_DBL_STRING:
	if ((source->limit() - source->cursor()) < 2) source->fill(2);
	yych = *source->cursor();
	if (yych <= '!') {
		if (yych <= 0x00) goto yy3_101;
		if (yych == '\n') goto yy3_107;
		goto yy3_103;
	} else {
		if (yych <= '"') goto yy3_104;
		if (yych == '\\') goto yy3_106;
		goto yy3_103;
	}
yy3_101:
	++source->cursor();
yy3_102:
#line 218 "bcplus/parser/detail/Scanner.3.re2c"
	{												goto yyc_DBL_STRING;				}
#line 688 "<stdout>"
yy3_103:
	yych = *++source->cursor();
	goto yy3_102;
yy3_104:
	++source->cursor();
#line 212 "bcplus/parser/detail/Scanner.3.re2c"
	{ 
												  _cond = yycNORMAL; 
												  ret = T_STRING_LITERAL;	
												  postskip = 1;
												  goto re2c_finish;					
												}
#line 701 "<stdout>"
yy3_106:
	yych = *++source->cursor();
	if (yych == '"') goto yy3_109;
	goto yy3_102;
yy3_107:
	++source->cursor();
#line 210 "bcplus/parser/detail/Scanner.3.re2c"
	{ source->newline();				 			goto yyc_DBL_STRING; 				}
#line 710 "<stdout>"
yy3_109:
	++source->cursor();
#line 211 "bcplus/parser/detail/Scanner.3.re2c"
	{ 												goto yyc_DBL_STRING; 				}
#line 715 "<stdout>"
/* *********************************** */
yyc_F2LP_CP:
	{
		static const unsigned char yybm[] = {
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0, 128,   0, 128, 128,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			128,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
		};
		if ((source->limit() - source->cursor()) < 2) source->fill(2);
		yych = *source->cursor();
		if (yych <= '$') {
			if (yych <= '\n') {
				if (yych <= 0x00) goto yy3_113;
				if (yych <= '\t') goto yy3_115;
				goto yy3_124;
			} else {
				if (yych == '"') goto yy3_117;
				goto yy3_115;
			}
		} else {
			if (yych <= '\'') {
				if (yych <= '%') goto yy3_119;
				if (yych <= '&') goto yy3_115;
				goto yy3_121;
			} else {
				if (yych == ':') goto yy3_123;
				goto yy3_115;
			}
		}
yy3_113:
		++source->cursor();
#line 496 "bcplus/parser/detail/Scanner.3.re2c"
		{ 
												  BLK_FINISH(1);
												  ret = T_ERR_UNTERMINATED_F2LP;			
												  _cond = yycNORMAL;
												  source->cursor()--;
												  goto re2c_finish;					
												}
#line 784 "<stdout>"
yy3_115:
		++source->cursor();
yy3_116:
#line 503 "bcplus/parser/detail/Scanner.3.re2c"
		{												goto yyc_F2LP_CP;					}
#line 790 "<stdout>"
yy3_117:
		++source->cursor();
#line 472 "bcplus/parser/detail/Scanner.3.re2c"
		{
												  if (!sgl_quote && !ln_cmt && !blk_cmt) dbl_quote = !dbl_quote;
												  goto yyc_F2LP_CP;
												}
#line 798 "<stdout>"
yy3_119:
		++source->cursor();
#line 476 "bcplus/parser/detail/Scanner.3.re2c"
		{
												  if (!blk_cmt && !sgl_quote && !dbl_quote) ln_cmt = true;
												  goto yyc_F2LP_CP;
												}
#line 806 "<stdout>"
yy3_121:
		++source->cursor();
#line 468 "bcplus/parser/detail/Scanner.3.re2c"
		{
												  if (!dbl_quote && !ln_cmt && !blk_cmt) sgl_quote = !sgl_quote;
												  goto yyc_F2LP_CP;
												}
#line 814 "<stdout>"
yy3_123:
		yyaccept = 0;
		yych = *(source->marker() = ++source->cursor());
		if (yych == '-') goto yy3_126;
		goto yy3_116;
yy3_124:
		++source->cursor();
#line 463 "bcplus/parser/detail/Scanner.3.re2c"
		{ 
												  BLK_LINE;
												  ln_cmt = false; 	
												  goto yyc_F2LP_CP;	
												}
#line 828 "<stdout>"
yy3_126:
		++source->cursor();
		if ((source->limit() - source->cursor()) < 8) source->fill(8);
		yych = *source->cursor();
		if (yybm[0+yych] & 128) {
			goto yy3_126;
		}
		if (yych == 'e') goto yy3_129;
yy3_128:
		source->cursor() = source->marker();
		goto yy3_116;
yy3_129:
		yych = *++source->cursor();
		if (yych != 'n') goto yy3_128;
		yych = *++source->cursor();
		if (yych != 'd') goto yy3_128;
		yych = *++source->cursor();
		if (yych == '_') goto yy3_134;
		if (yych == 'f') goto yy3_128;
		goto yy3_133;
yy3_132:
		++source->cursor();
		if ((source->limit() - source->cursor()) < 4) source->fill(4);
		yych = *source->cursor();
yy3_133:
		if (yych <= '\f') {
			if (yych == '\t') goto yy3_132;
			if (yych <= '\n') goto yy3_128;
			goto yy3_132;
		} else {
			if (yych <= ' ') {
				if (yych <= 0x1F) goto yy3_128;
				goto yy3_132;
			} else {
				if (yych == 'f') goto yy3_142;
				goto yy3_128;
			}
		}
yy3_134:
		yych = *++source->cursor();
		if (yych != 'f') goto yy3_128;
		yych = *++source->cursor();
		if (yych != '2') goto yy3_128;
		yych = *++source->cursor();
		if (yych != 'l') goto yy3_128;
		yych = *++source->cursor();
		if (yych != 'p') goto yy3_128;
yy3_138:
		++source->cursor();
		if (source->limit() <= source->cursor()) source->fill(1);
		yych = *source->cursor();
		if (yych <= '\f') {
			if (yych == '\t') goto yy3_138;
			if (yych <= '\n') goto yy3_128;
			goto yy3_138;
		} else {
			if (yych <= ' ') {
				if (yych <= 0x1F) goto yy3_128;
				goto yy3_138;
			} else {
				if (yych != '.') goto yy3_128;
			}
		}
		++source->cursor();
#line 481 "bcplus/parser/detail/Scanner.3.re2c"
		{ 
												  if (!ln_cmt && !blk_cmt && !sgl_quote && !dbl_quote) {
													  _cond = yycNORMAL; 
													  ret = T_F2LP_CP; 
													  goto re2c_finish;					
												  } else goto yyc_F2LP_CP;
												}
#line 901 "<stdout>"
yy3_142:
		yych = *++source->cursor();
		if (yych != '2') goto yy3_128;
		yych = *++source->cursor();
		if (yych != 'l') goto yy3_128;
		yych = *++source->cursor();
		if (yych != 'p') goto yy3_128;
yy3_145:
		++source->cursor();
		if (source->limit() <= source->cursor()) source->fill(1);
		yych = *source->cursor();
		if (yych <= '\f') {
			if (yych == '\t') goto yy3_145;
			if (yych <= '\n') goto yy3_128;
			goto yy3_145;
		} else {
			if (yych <= ' ') {
				if (yych <= 0x1F) goto yy3_128;
				goto yy3_145;
			} else {
				if (yych != '.') goto yy3_128;
			}
		}
		++source->cursor();
#line 489 "bcplus/parser/detail/Scanner.3.re2c"
		{
												  if (!ln_cmt && !blk_cmt && !sgl_quote && !dbl_quote) { 
													  _cond = yycNORMAL; 
													  ret = T_F2LP_CP; 
													  goto re2c_finish;					
												  } else goto yyc_F2LP_CP;
												}
#line 934 "<stdout>"
	}
/* *********************************** */
yyc_F2LP_GR:
	{
		static const unsigned char yybm[] = {
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0, 128,   0, 128, 128,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			128,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
		};
		if ((source->limit() - source->cursor()) < 9) source->fill(9);
		yych = *source->cursor();
		if (yych <= '$') {
			if (yych <= '\n') {
				if (yych <= 0x00) goto yy3_151;
				if (yych <= '\t') goto yy3_153;
				goto yy3_164;
			} else {
				if (yych <= '!') goto yy3_153;
				if (yych <= '"') goto yy3_155;
				if (yych <= '#') goto yy3_157;
				goto yy3_153;
			}
		} else {
			if (yych <= ')') {
				if (yych <= '%') goto yy3_158;
				if (yych == '\'') goto yy3_160;
				goto yy3_153;
			} else {
				if (yych <= '*') goto yy3_162;
				if (yych == '/') goto yy3_163;
				goto yy3_153;
			}
		}
yy3_151:
		++source->cursor();
#line 454 "bcplus/parser/detail/Scanner.3.re2c"
		{ 
												  BLK_FINISH(1);
												  ret = T_ERR_UNTERMINATED_F2LP;			
												  _cond = yycNORMAL;
												  source->cursor()--;
												  goto re2c_finish;					
												}
#line 1007 "<stdout>"
yy3_153:
		++source->cursor();
yy3_154:
#line 461 "bcplus/parser/detail/Scanner.3.re2c"
		{												goto yyc_F2LP_GR;					}
#line 1013 "<stdout>"
yy3_155:
		++source->cursor();
#line 430 "bcplus/parser/detail/Scanner.3.re2c"
		{
												  if (!sgl_quote && !ln_cmt && !blk_cmt) dbl_quote = !dbl_quote;
												  goto yyc_F2LP_GR;
												}
#line 1021 "<stdout>"
yy3_157:
		yyaccept = 0;
		yych = *(source->marker() = ++source->cursor());
		if (yych == 'e') goto yy3_170;
		goto yy3_154;
yy3_158:
		++source->cursor();
#line 434 "bcplus/parser/detail/Scanner.3.re2c"
		{
												  if (!blk_cmt && !sgl_quote && !dbl_quote) ln_cmt = true;
												  goto yyc_F2LP_GR;
												}
#line 1034 "<stdout>"
yy3_160:
		++source->cursor();
#line 426 "bcplus/parser/detail/Scanner.3.re2c"
		{
												  if (!dbl_quote && !ln_cmt && !blk_cmt) sgl_quote = !sgl_quote;
												  goto yyc_F2LP_GR;
												}
#line 1042 "<stdout>"
yy3_162:
		yych = *++source->cursor();
		if (yych == '/') goto yy3_168;
		goto yy3_154;
yy3_163:
		yych = *++source->cursor();
		if (yych == '*') goto yy3_166;
		goto yy3_154;
yy3_164:
		++source->cursor();
#line 421 "bcplus/parser/detail/Scanner.3.re2c"
		{ 
												  BLK_LINE;
												  ln_cmt = false;
												  goto yyc_F2LP_GR;				
												}
#line 1059 "<stdout>"
yy3_166:
		++source->cursor();
#line 438 "bcplus/parser/detail/Scanner.3.re2c"
		{
												  if (!ln_cmt && !sgl_quote && !dbl_quote) blk_cmt = true;
												  goto yyc_F2LP_GR;
												}
#line 1067 "<stdout>"
yy3_168:
		++source->cursor();
#line 442 "bcplus/parser/detail/Scanner.3.re2c"
		{
												  blk_cmt = false;
												  goto yyc_F2LP_GR;
												}
#line 1075 "<stdout>"
yy3_170:
		yych = *++source->cursor();
		if (yych == 'n') goto yy3_172;
yy3_171:
		source->cursor() = source->marker();
		goto yy3_154;
yy3_172:
		yych = *++source->cursor();
		if (yych != 'd') goto yy3_171;
		yych = *++source->cursor();
		if (yych != '_') goto yy3_171;
		yych = *++source->cursor();
		if (yych != 'f') goto yy3_171;
		yych = *++source->cursor();
		if (yych != '2') goto yy3_171;
		yych = *++source->cursor();
		if (yych != 'l') goto yy3_171;
		yych = *++source->cursor();
		if (yych != 'p') goto yy3_171;
yy3_178:
		++source->cursor();
		if (source->limit() <= source->cursor()) source->fill(1);
		yych = *source->cursor();
		if (yybm[0+yych] & 128) {
			goto yy3_178;
		}
		if (yych != '.') goto yy3_171;
		++source->cursor();
#line 447 "bcplus/parser/detail/Scanner.3.re2c"
		{
												  if (!ln_cmt && !blk_cmt && !sgl_quote && !dbl_quote) { 
													  _cond = yycNORMAL; 
													  ret = T_F2LP_GR; 	
													  goto re2c_finish;				
												  } else goto yyc_F2LP_GR;	
												}
#line 1112 "<stdout>"
	}
/* *********************************** */
yyc_LUA_CP:
	{
		static const unsigned char yybm[] = {
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0, 128,   0, 128, 128,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			128,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
		};
		if ((source->limit() - source->cursor()) < 3) source->fill(3);
		yych = *source->cursor();
		if (yych <= '\'') {
			if (yych <= '\n') {
				if (yych <= 0x00) goto yy3_184;
				if (yych <= '\t') goto yy3_186;
				goto yy3_196;
			} else {
				if (yych == '"') goto yy3_188;
				if (yych <= '&') goto yy3_186;
				goto yy3_190;
			}
		} else {
			if (yych <= '9') {
				if (yych == '-') goto yy3_192;
				goto yy3_186;
			} else {
				if (yych <= ':') goto yy3_193;
				if (yych == '}') goto yy3_194;
				goto yy3_186;
			}
		}
yy3_184:
		++source->cursor();
#line 411 "bcplus/parser/detail/Scanner.3.re2c"
		{ 
												  BLK_FINISH(1);
												  ret = T_ERR_UNTERMINATED_LUA;			
												  _cond = yycNORMAL;
												  source->cursor()--;
												  goto re2c_finish;					
												}
#line 1183 "<stdout>"
yy3_186:
		++source->cursor();
yy3_187:
#line 418 "bcplus/parser/detail/Scanner.3.re2c"
		{												goto yyc_LUA_CP;					}
#line 1189 "<stdout>"
yy3_188:
		++source->cursor();
#line 375 "bcplus/parser/detail/Scanner.3.re2c"
		{
												  if (!sgl_quote && !ln_cmt && !blk_cmt) dbl_quote = !dbl_quote;
												  goto yyc_LUA_CP;
												}
#line 1197 "<stdout>"
yy3_190:
		++source->cursor();
#line 371 "bcplus/parser/detail/Scanner.3.re2c"
		{
												  if (!dbl_quote && !ln_cmt && !blk_cmt) sgl_quote = !sgl_quote;
												  goto yyc_LUA_CP;
												}
#line 1205 "<stdout>"
yy3_192:
		yych = *++source->cursor();
		if (yych == '-') goto yy3_219;
		goto yy3_187;
yy3_193:
		yyaccept = 0;
		yych = *(source->marker() = ++source->cursor());
		if (yych == '-') goto yy3_198;
		goto yy3_187;
yy3_194:
		++source->cursor();
#line 391 "bcplus/parser/detail/Scanner.3.re2c"
		{
												  blk_cmt = false;
												  goto yyc_LUA_CP;
												}
#line 1222 "<stdout>"
yy3_196:
		++source->cursor();
#line 366 "bcplus/parser/detail/Scanner.3.re2c"
		{ 
												  BLK_LINE;
												  ln_cmt = false;
												  goto yyc_LUA_CP;					
												}
#line 1231 "<stdout>"
yy3_198:
		++source->cursor();
		if ((source->limit() - source->cursor()) < 7) source->fill(7);
		yych = *source->cursor();
		if (yybm[0+yych] & 128) {
			goto yy3_198;
		}
		if (yych == 'e') goto yy3_201;
yy3_200:
		source->cursor() = source->marker();
		goto yy3_187;
yy3_201:
		yych = *++source->cursor();
		if (yych != 'n') goto yy3_200;
		yych = *++source->cursor();
		if (yych != 'd') goto yy3_200;
		yych = *++source->cursor();
		if (yych == '_') goto yy3_206;
		if (yych == 'l') goto yy3_200;
		goto yy3_205;
yy3_204:
		++source->cursor();
		if ((source->limit() - source->cursor()) < 3) source->fill(3);
		yych = *source->cursor();
yy3_205:
		if (yych <= '\f') {
			if (yych == '\t') goto yy3_204;
			if (yych <= '\n') goto yy3_200;
			goto yy3_204;
		} else {
			if (yych <= ' ') {
				if (yych <= 0x1F) goto yy3_200;
				goto yy3_204;
			} else {
				if (yych == 'l') goto yy3_213;
				goto yy3_200;
			}
		}
yy3_206:
		yych = *++source->cursor();
		if (yych != 'l') goto yy3_200;
		yych = *++source->cursor();
		if (yych != 'u') goto yy3_200;
		yych = *++source->cursor();
		if (yych != 'a') goto yy3_200;
yy3_209:
		++source->cursor();
		if (source->limit() <= source->cursor()) source->fill(1);
		yych = *source->cursor();
		if (yych <= '\f') {
			if (yych == '\t') goto yy3_209;
			if (yych <= '\n') goto yy3_200;
			goto yy3_209;
		} else {
			if (yych <= ' ') {
				if (yych <= 0x1F) goto yy3_200;
				goto yy3_209;
			} else {
				if (yych != '.') goto yy3_200;
			}
		}
		++source->cursor();
#line 396 "bcplus/parser/detail/Scanner.3.re2c"
		{ 
												  if (!ln_cmt && !blk_cmt && !sgl_quote && !dbl_quote) {
												    _cond = yycNORMAL; 
												    ret = T_LUA_CP; 
												    goto re2c_finish;					
												  } else goto yyc_LUA_CP;
												}
#line 1302 "<stdout>"
yy3_213:
		yych = *++source->cursor();
		if (yych != 'u') goto yy3_200;
		yych = *++source->cursor();
		if (yych != 'a') goto yy3_200;
yy3_215:
		++source->cursor();
		if (source->limit() <= source->cursor()) source->fill(1);
		yych = *source->cursor();
		if (yych <= '\f') {
			if (yych == '\t') goto yy3_215;
			if (yych <= '\n') goto yy3_200;
			goto yy3_215;
		} else {
			if (yych <= ' ') {
				if (yych <= 0x1F) goto yy3_200;
				goto yy3_215;
			} else {
				if (yych != '.') goto yy3_200;
			}
		}
		++source->cursor();
#line 404 "bcplus/parser/detail/Scanner.3.re2c"
		{ 
												  if (!ln_cmt && !blk_cmt && !sgl_quote && !dbl_quote) {
													  _cond = yycNORMAL; 
													  ret = T_LUA_CP; 
													  goto re2c_finish;					
												  } else goto yyc_LUA_CP;
												}
#line 1333 "<stdout>"
yy3_219:
		++source->cursor();
		if ((yych = *source->cursor()) == '{') goto yy3_221;
#line 379 "bcplus/parser/detail/Scanner.3.re2c"
		{
												  if (!blk_cmt && !sgl_quote && !dbl_quote) {
													  ln_cmt = true;
												  }
												  goto yyc_LUA_CP;
												}
#line 1344 "<stdout>"
yy3_221:
		++source->cursor();
#line 385 "bcplus/parser/detail/Scanner.3.re2c"
		{
												  if (!ln_cmt && !sgl_quote && !dbl_quote) {
													  blk_cmt = true;
												  }
												  goto yyc_LUA_CP;
												}
#line 1354 "<stdout>"
	}
/* *********************************** */
yyc_LUA_GR:
	{
		static const unsigned char yybm[] = {
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0, 128,   0, 128, 128,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			128,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
		};
		if ((source->limit() - source->cursor()) < 8) source->fill(8);
		yych = *source->cursor();
		if (yych <= '#') {
			if (yych <= '\n') {
				if (yych <= 0x00) goto yy3_225;
				if (yych <= '\t') goto yy3_227;
				goto yy3_237;
			} else {
				if (yych <= '!') goto yy3_227;
				if (yych <= '"') goto yy3_229;
				goto yy3_231;
			}
		} else {
			if (yych <= ',') {
				if (yych == '\'') goto yy3_232;
				goto yy3_227;
			} else {
				if (yych <= '-') goto yy3_234;
				if (yych == '}') goto yy3_235;
				goto yy3_227;
			}
		}
yy3_225:
		++source->cursor();
#line 357 "bcplus/parser/detail/Scanner.3.re2c"
		{ 
												  BLK_FINISH(1);
												  ret = T_ERR_UNTERMINATED_LUA;			
												  _cond = yycNORMAL;
												  source->cursor()--;
												  goto re2c_finish;					
												}
#line 1425 "<stdout>"
yy3_227:
		++source->cursor();
yy3_228:
#line 364 "bcplus/parser/detail/Scanner.3.re2c"
		{												goto yyc_LUA_GR;					}
#line 1431 "<stdout>"
yy3_229:
		++source->cursor();
#line 330 "bcplus/parser/detail/Scanner.3.re2c"
		{
												  if (!sgl_quote && !ln_cmt && !blk_cmt) dbl_quote = !dbl_quote;
												  goto yyc_LUA_GR;
												}
#line 1439 "<stdout>"
yy3_231:
		yyaccept = 0;
		yych = *(source->marker() = ++source->cursor());
		if (yych == 'e') goto yy3_243;
		goto yy3_228;
yy3_232:
		++source->cursor();
#line 326 "bcplus/parser/detail/Scanner.3.re2c"
		{
												  if (!dbl_quote && !ln_cmt && !blk_cmt) sgl_quote = !sgl_quote;
												  goto yyc_LUA_GR;
												}
#line 1452 "<stdout>"
yy3_234:
		yych = *++source->cursor();
		if (yych == '-') goto yy3_239;
		goto yy3_228;
yy3_235:
		++source->cursor();
#line 346 "bcplus/parser/detail/Scanner.3.re2c"
		{
												  blk_cmt = false;
												  goto yyc_LUA_GR;
												}
#line 1464 "<stdout>"
yy3_237:
		++source->cursor();
#line 321 "bcplus/parser/detail/Scanner.3.re2c"
		{ 
												  BLK_LINE;
												  ln_cmt = false;
												  goto yyc_LUA_GR;				
												}
#line 1473 "<stdout>"
yy3_239:
		++source->cursor();
		if ((yych = *source->cursor()) == '{') goto yy3_241;
#line 334 "bcplus/parser/detail/Scanner.3.re2c"
		{
												  if (!blk_cmt && !sgl_quote && !dbl_quote) {
													  ln_cmt = true;
												  }
												  goto yyc_LUA_GR;
												}
#line 1484 "<stdout>"
yy3_241:
		++source->cursor();
#line 340 "bcplus/parser/detail/Scanner.3.re2c"
		{
												  if (!ln_cmt && !sgl_quote && !dbl_quote) {
													  blk_cmt = true;
												  }
												  goto yyc_LUA_GR;
												}
#line 1494 "<stdout>"
yy3_243:
		yych = *++source->cursor();
		if (yych == 'n') goto yy3_245;
yy3_244:
		source->cursor() = source->marker();
		goto yy3_228;
yy3_245:
		yych = *++source->cursor();
		if (yych != 'd') goto yy3_244;
		yych = *++source->cursor();
		if (yych != '_') goto yy3_244;
		yych = *++source->cursor();
		if (yych != 'l') goto yy3_244;
		yych = *++source->cursor();
		if (yych != 'u') goto yy3_244;
		yych = *++source->cursor();
		if (yych != 'a') goto yy3_244;
yy3_250:
		++source->cursor();
		if (source->limit() <= source->cursor()) source->fill(1);
		yych = *source->cursor();
		if (yybm[0+yych] & 128) {
			goto yy3_250;
		}
		if (yych != '.') goto yy3_244;
		++source->cursor();
#line 350 "bcplus/parser/detail/Scanner.3.re2c"
		{ 
												  if (!blk_cmt && !ln_cmt && !sgl_quote && !dbl_quote) {
													  _cond = yycNORMAL; 
													  ret = T_LUA_GR; 
													  goto re2c_finish;					
												  } else goto yyc_LUA_GR;
												}
#line 1529 "<stdout>"
	}
/* *********************************** */
yyc_MACRO:
	if ((source->limit() - source->cursor()) < 2) source->fill(2);
	yych = *source->cursor();
	if (yych <= '&') {
		if (yych <= '!') {
			if (yych <= 0x00) goto yy3_256;
			if (yych == '\n') goto yy3_270;
			goto yy3_258;
		} else {
			if (yych <= '"') goto yy3_260;
			if (yych == '%') goto yy3_262;
			goto yy3_258;
		}
	} else {
		if (yych <= '-') {
			if (yych <= '\'') goto yy3_264;
			if (yych == '*') goto yy3_266;
			goto yy3_258;
		} else {
			if (yych <= '/') {
				if (yych <= '.') goto yy3_267;
				goto yy3_269;
			} else {
				if (yych == ';') goto yy3_267;
				goto yy3_258;
			}
		}
	}
yy3_256:
	++source->cursor();
#line 622 "bcplus/parser/detail/Scanner.3.re2c"
	{
													if (sgl_quote || dbl_quote) {
														_cond = yycNORMAL;
														ret = T_ERR_UNTERMINATED_STRING;
													} else {
														_cond = yycNORMAL;
														ret = T_ERR_SYNTAX;
													} goto re2c_finish;
												}
#line 1572 "<stdout>"
yy3_258:
	++source->cursor();
yy3_259:
#line 631 "bcplus/parser/detail/Scanner.3.re2c"
	{ if (_cond == yycARG) std::cout << "crap." <<std::endl;  												goto yyc_MACRO;						}
#line 1578 "<stdout>"
yy3_260:
	++source->cursor();
#line 607 "bcplus/parser/detail/Scanner.3.re2c"
	{ 
												  if (!ln_cmt && !blk_cmt && !sgl_quote)  dbl_quote = !dbl_quote; 	
												  goto yyc_MACRO;						
												}
#line 1586 "<stdout>"
yy3_262:
	++source->cursor();
#line 595 "bcplus/parser/detail/Scanner.3.re2c"
	{ 
												  if (!blk_cmt && !sgl_quote && !dbl_quote) ln_cmt = true;
												  goto yyc_MACRO;
												}
#line 1594 "<stdout>"
yy3_264:
	++source->cursor();
#line 611 "bcplus/parser/detail/Scanner.3.re2c"
	{ 
												  if (!ln_cmt && !blk_cmt && !dbl_quote)  sgl_quote = !sgl_quote;	
												  goto yyc_MACRO;						
												}
#line 1602 "<stdout>"
yy3_266:
	yych = *++source->cursor();
	if (yych == '/') goto yy3_274;
	goto yy3_259;
yy3_267:
	++source->cursor();
#line 615 "bcplus/parser/detail/Scanner.3.re2c"
	{
												  if (sgl_quote || dbl_quote || blk_cmt || ln_cmt) goto yyc_MACRO;
												  _cond = yycNORMAL;
												  source->cursor()--;
												  ret = T_MACRO_STRING;
												  goto re2c_finish;
												}
#line 1617 "<stdout>"
yy3_269:
	yych = *++source->cursor();
	if (yych == '*') goto yy3_272;
	goto yy3_259;
yy3_270:
	++source->cursor();
#line 590 "bcplus/parser/detail/Scanner.3.re2c"
	{
												  source->newline();
												  ln_cmt = false;
												  goto yyc_MACRO;
												}
#line 1630 "<stdout>"
yy3_272:
	++source->cursor();
#line 599 "bcplus/parser/detail/Scanner.3.re2c"
	{
												  if (!ln_cmt && !sgl_quote && !dbl_quote) blk_cmt = true;
												  goto yyc_MACRO;
												}
#line 1638 "<stdout>"
yy3_274:
	++source->cursor();
#line 603 "bcplus/parser/detail/Scanner.3.re2c"
	{
												  if (!ln_cmt && !sgl_quote && !dbl_quote) blk_cmt = false;
												  goto yyc_MACRO;
												}
#line 1646 "<stdout>"
/* *********************************** */
yyc_NORMAL:
	{
		static const unsigned char yybm[] = {
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,  64,   0,  64,  64,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			 64,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			160, 160, 160, 160, 160, 160, 160, 160, 
			160, 160,   0,   0,   0,   0,   0,   0, 
			  0,  32,  32,  32,  32,  32,  32,  32, 
			 32,  32,  32,  32,  32,  32,  32,  32, 
			 32,  32,  32,  32,  32,  32,  32,  32, 
			 32,  32,  32,   0,   0,   0,   0,  32, 
			  0,  32,  32,  32,  32,  32,  32,  32, 
			 32,  32,  32,  32,  32,  32,  32,  32, 
			 32,  32,  32,  32,  32,  32,  32,  32, 
			 32,  32,  32,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
		};
		if ((source->limit() - source->cursor()) < 12) source->fill(12);
		yych = *source->cursor();
		if (yych <= ':') {
			if (yych <= '(') {
				if (yych <= '"') {
					if (yych == '\n') goto yy3_278;
					if (yych <= '!') goto yy3_279;
					goto yy3_281;
				} else {
					if (yych <= '%') {
						if (yych <= '#') goto yy3_283;
						goto yy3_279;
					} else {
						if (yych <= '&') goto yy3_285;
						if (yych <= '\'') goto yy3_287;
						goto yy3_289;
					}
				}
			} else {
				if (yych <= ',') {
					if (yych <= ')') goto yy3_291;
					if (yych <= '*') goto yy3_293;
					if (yych <= '+') goto yy3_295;
					goto yy3_297;
				} else {
					if (yych <= '.') {
						if (yych <= '-') goto yy3_299;
						goto yy3_301;
					} else {
						if (yych <= '/') goto yy3_303;
						if (yych <= '9') goto yy3_304;
						goto yy3_306;
					}
				}
			}
		} else {
			if (yych <= '\\') {
				if (yych <= '>') {
					if (yych <= ';') goto yy3_308;
					if (yych <= '<') goto yy3_310;
					if (yych <= '=') goto yy3_312;
					goto yy3_314;
				} else {
					if (yych <= '@') {
						if (yych <= '?') goto yy3_279;
						goto yy3_316;
					} else {
						if (yych <= 'Z') goto yy3_318;
						if (yych <= '[') goto yy3_320;
						goto yy3_322;
					}
				}
			} else {
				if (yych <= 'z') {
					if (yych <= '^') {
						if (yych <= ']') goto yy3_323;
						goto yy3_325;
					} else {
						if (yych == '`') goto yy3_279;
						goto yy3_318;
					}
				} else {
					if (yych <= '|') {
						if (yych <= '{') goto yy3_327;
						goto yy3_329;
					} else {
						if (yych <= '}') goto yy3_331;
						if (yych <= '~') goto yy3_333;
						goto yy3_279;
					}
				}
			}
		}
yy3_278:
		source->cursor() = source->marker();
		if (yyaccept <= 1) {
			if (yyaccept == 0) {
				goto yy3_317;
			} else {
				goto yy3_319;
			}
		} else {
			goto yy3_380;
		}
yy3_279:
		++source->cursor();
yy3_280:
#line 635 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_ERR_UNKNOWN_SYMBOL;					goto re2c_finish;					}
#line 1773 "<stdout>"
yy3_281:
		++source->cursor();
#line 138 "bcplus/parser/detail/Scanner.3.re2c"
		{ _cond = yycDBL_STRING;	preskip = 1;		goto yyc_DBL_STRING;				}
#line 1778 "<stdout>"
yy3_283:
		++source->cursor();
		if ((yych = *source->cursor()) <= '^') {
			if (yych <= '9') {
				if (yych >= '0') goto yy3_447;
			} else {
				if (yych <= '@') goto yy3_284;
				if (yych <= 'Z') goto yy3_450;
			}
		} else {
			if (yych <= 'a') {
				if (yych != '`') goto yy3_450;
			} else {
				if (yych <= 'b') goto yy3_453;
				if (yych <= 'z') goto yy3_450;
			}
		}
yy3_284:
#line 125 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_POUND;						goto re2c_finish;					}
#line 1799 "<stdout>"
yy3_285:
		++source->cursor();
		if ((yych = *source->cursor()) == '&') goto yy3_445;
#line 113 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_AMP;							goto re2c_finish;					}
#line 1805 "<stdout>"
yy3_287:
		++source->cursor();
#line 139 "bcplus/parser/detail/Scanner.3.re2c"
		{ _cond = yycSGL_STRING; 	preskip = 1;		goto yyc_SGL_STRING;				}
#line 1810 "<stdout>"
yy3_289:
		++source->cursor();
#line 133 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_PAREN_L;						goto re2c_finish;					}
#line 1815 "<stdout>"
yy3_291:
		++source->cursor();
#line 134 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_PAREN_R;						goto re2c_finish;					}
#line 1820 "<stdout>"
yy3_293:
		++source->cursor();
#line 126 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_STAR;							goto re2c_finish;					}
#line 1825 "<stdout>"
yy3_295:
		++source->cursor();
		if ((yych = *source->cursor()) == '+') goto yy3_443;
#line 115 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_PLUS;							goto re2c_finish;					}
#line 1831 "<stdout>"
yy3_297:
		++source->cursor();
#line 122 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_COMMA;						goto re2c_finish;					}
#line 1836 "<stdout>"
yy3_299:
		++source->cursor();
		if ((yych = *source->cursor()) == '>') goto yy3_439;
#line 93 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_DASH;							goto re2c_finish;					}
#line 1842 "<stdout>"
yy3_301:
		++source->cursor();
		if ((yych = *source->cursor()) == '.') goto yy3_437;
#line 117 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_PERIOD; _in_macro = false;	goto re2c_finish;					}
#line 1848 "<stdout>"
yy3_303:
		yych = *++source->cursor();
		if (yych == '/') goto yy3_435;
		if (yych == '\\') goto yy3_433;
		goto yy3_280;
yy3_304:
		++source->cursor();
		yych = *source->cursor();
		goto yy3_432;
yy3_305:
#line 204 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_INTEGER;						goto re2c_finish;					}
#line 1861 "<stdout>"
yy3_306:
		++source->cursor();
		if ((yych = *source->cursor()) == '-') goto yy3_379;
		if (yych == ':') goto yy3_381;
#line 90 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_COLON;						goto re2c_finish;					}
#line 1868 "<stdout>"
yy3_308:
		++source->cursor();
#line 123 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_SEMICOLON;					goto re2c_finish;					}
#line 1873 "<stdout>"
yy3_310:
		++source->cursor();
		if ((yych = *source->cursor()) <= '<') {
			if (yych == '-') goto yy3_375;
		} else {
			if (yych <= '=') goto yy3_371;
			if (yych <= '>') goto yy3_373;
		}
#line 97 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_LTHAN;						goto re2c_finish;					}
#line 1884 "<stdout>"
yy3_312:
		++source->cursor();
		if ((yych = *source->cursor()) <= ';') goto yy3_313;
		if (yych <= '<') goto yy3_369;
		if (yych <= '=') goto yy3_365;
		if (yych <= '>') goto yy3_367;
yy3_313:
#line 111 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_EQ;							goto re2c_finish;					}
#line 1894 "<stdout>"
yy3_314:
		++source->cursor();
		if ((yych = *source->cursor()) <= '<') goto yy3_315;
		if (yych <= '=') goto yy3_363;
		if (yych <= '>') goto yy3_361;
yy3_315:
#line 99 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_GTHAN;						goto re2c_finish;					}
#line 1903 "<stdout>"
yy3_316:
		yyaccept = 0;
		yych = *(source->marker() = ++source->cursor());
		if (yych <= '@') {
			if (yych <= '<') {
				if (yych >= '<') goto yy3_351;
			} else {
				if (yych <= '=') goto yy3_348;
				if (yych <= '>') goto yy3_349;
			}
		} else {
			if (yych <= '_') {
				if (yych <= 'Z') goto yy3_345;
				if (yych >= '_') goto yy3_345;
			} else {
				if (yych <= '`') goto yy3_317;
				if (yych <= 'z') goto yy3_345;
			}
		}
yy3_317:
#line 128 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_AT;							goto re2c_finish;					}
#line 1926 "<stdout>"
yy3_318:
		marker = source->cursor() + 1;
		yyaccept = 1;
		yych = *(source->marker() = ++source->cursor());
		if (yybm[0+yych] & 64) {
			goto yy3_341;
		}
		if (yych <= '@') {
			if (yych <= '(') {
				if (yych >= '(') goto yy3_343;
			} else {
				if (yych <= '/') goto yy3_319;
				if (yych <= '9') goto yy3_339;
			}
		} else {
			if (yych <= '_') {
				if (yych <= 'Z') goto yy3_339;
				if (yych >= '_') goto yy3_339;
			} else {
				if (yych <= '`') goto yy3_319;
				if (yych <= 'z') goto yy3_339;
			}
		}
yy3_319:
#line 205 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_IDENTIFIER;					goto re2c_finish;					}
#line 1953 "<stdout>"
yy3_320:
		++source->cursor();
#line 129 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_BRACKET_L;					goto re2c_finish;					}
#line 1958 "<stdout>"
yy3_322:
		yych = *++source->cursor();
		if (yych == '/') goto yy3_335;
		if (yych == '=') goto yy3_337;
		goto yy3_280;
yy3_323:
		++source->cursor();
#line 130 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_BRACKET_R;					goto re2c_finish;					}
#line 1968 "<stdout>"
yy3_325:
		++source->cursor();
#line 127 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_CARROT;						goto re2c_finish;					}
#line 1973 "<stdout>"
yy3_327:
		++source->cursor();
#line 131 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_CBRACKET_L;					goto re2c_finish;					}
#line 1978 "<stdout>"
yy3_329:
		++source->cursor();
#line 124 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_PIPE;							goto re2c_finish;					}
#line 1983 "<stdout>"
yy3_331:
		++source->cursor();
#line 132 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_CBRACKET_R;					goto re2c_finish;					}
#line 1988 "<stdout>"
yy3_333:
		++source->cursor();
#line 91 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_TILDE;						goto re2c_finish;					}
#line 1993 "<stdout>"
yy3_335:
		++source->cursor();
#line 119 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_BIG_DISJ;						goto re2c_finish;					}
#line 1998 "<stdout>"
yy3_337:
		++source->cursor();
#line 118 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_NEQ;							goto re2c_finish;					}
#line 2003 "<stdout>"
yy3_339:
		marker = source->cursor() + 1;
		yyaccept = 1;
		source->marker() = ++source->cursor();
		if (source->limit() <= source->cursor()) source->fill(1);
		yych = *source->cursor();
		if (yybm[0+yych] & 64) {
			goto yy3_341;
		}
		if (yych <= '@') {
			if (yych <= '(') {
				if (yych <= '\'') goto yy3_319;
				goto yy3_343;
			} else {
				if (yych <= '/') goto yy3_319;
				if (yych <= '9') goto yy3_339;
				goto yy3_319;
			}
		} else {
			if (yych <= '_') {
				if (yych <= 'Z') goto yy3_339;
				if (yych <= '^') goto yy3_319;
				goto yy3_339;
			} else {
				if (yych <= '`') goto yy3_319;
				if (yych <= 'z') goto yy3_339;
				goto yy3_319;
			}
		}
yy3_341:
		++source->cursor();
		if (source->limit() <= source->cursor()) source->fill(1);
		yych = *source->cursor();
		if (yybm[0+yych] & 64) {
			goto yy3_341;
		}
		if (yych != '(') goto yy3_278;
yy3_343:
		++source->cursor();
		source->cursor() = marker;
#line 193 "bcplus/parser/detail/Scanner.3.re2c"
		{ 
												  ret = T_IDENTIFIER;
												  _cond = yycARG;
												  goto re2c_finish;					
												}
#line 2050 "<stdout>"
yy3_345:
		++source->cursor();
		if (source->limit() <= source->cursor()) source->fill(1);
		yych = *source->cursor();
		if (yych <= 'Z') {
			if (yych <= '/') goto yy3_347;
			if (yych <= '9') goto yy3_345;
			if (yych >= 'A') goto yy3_345;
		} else {
			if (yych <= '_') {
				if (yych >= '_') goto yy3_345;
			} else {
				if (yych <= '`') goto yy3_347;
				if (yych <= 'z') goto yy3_345;
			}
		}
yy3_347:
#line 208 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_AT_IDENTIFIER;				goto re2c_finish;					}
#line 2070 "<stdout>"
yy3_348:
		yych = *++source->cursor();
		if (yych == '<') goto yy3_357;
		if (yych == '>') goto yy3_359;
		goto yy3_278;
yy3_349:
		++source->cursor();
		if ((yych = *source->cursor()) == '=') goto yy3_355;
#line 103 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_GTHAN;						goto re2c_finish;					}
#line 2081 "<stdout>"
yy3_351:
		++source->cursor();
		if ((yych = *source->cursor()) == '=') goto yy3_353;
#line 102 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_LTHAN;						goto re2c_finish;					}
#line 2087 "<stdout>"
yy3_353:
		++source->cursor();
#line 104 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_LTHAN_EQ;						goto re2c_finish;					}
#line 2092 "<stdout>"
yy3_355:
		++source->cursor();
#line 105 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_GTHAN_EQ;						goto re2c_finish;					}
#line 2097 "<stdout>"
yy3_357:
		++source->cursor();
#line 106 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_LTHAN_EQ;						goto re2c_finish;					}
#line 2102 "<stdout>"
yy3_359:
		++source->cursor();
#line 107 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_GTHAN_EQ;						goto re2c_finish;					}
#line 2107 "<stdout>"
yy3_361:
		++source->cursor();
#line 101 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_DBL_GTHAN;					goto re2c_finish;					}
#line 2112 "<stdout>"
yy3_363:
		++source->cursor();
#line 100 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_GTHAN_EQ;						goto re2c_finish;					}
#line 2117 "<stdout>"
yy3_365:
		++source->cursor();
#line 110 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_DBL_EQ;						goto re2c_finish;					}
#line 2122 "<stdout>"
yy3_367:
		++source->cursor();
#line 109 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_GTHAN_EQ;						goto re2c_finish;					}
#line 2127 "<stdout>"
yy3_369:
		++source->cursor();
#line 108 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_LTHAN_EQ;						goto re2c_finish;					}
#line 2132 "<stdout>"
yy3_371:
		++source->cursor();
#line 98 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_LTHAN_EQ;						goto re2c_finish;					}
#line 2137 "<stdout>"
yy3_373:
		++source->cursor();
#line 96 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_NEQ;							goto re2c_finish;					}
#line 2142 "<stdout>"
yy3_375:
		++source->cursor();
		if ((yych = *source->cursor()) == '>') goto yy3_377;
#line 95 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_ARROW_LDASH;					goto re2c_finish;					}
#line 2148 "<stdout>"
yy3_377:
		++source->cursor();
#line 94 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_EQUIV;						goto re2c_finish;					}
#line 2153 "<stdout>"
yy3_379:
		yyaccept = 2;
		yych = *(source->marker() = ++source->cursor());
		if (yych <= '\f') {
			if (yych == '\t') goto yy3_383;
			if (yych >= '\v') goto yy3_383;
		} else {
			if (yych <= ' ') {
				if (yych >= ' ') goto yy3_383;
			} else {
				if (yych == 'b') goto yy3_385;
			}
		}
yy3_380:
#line 88 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_COLON_DASH;					goto re2c_finish;					}
#line 2170 "<stdout>"
yy3_381:
		++source->cursor();
#line 89 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_DBL_COLON;					goto re2c_finish;					}
#line 2175 "<stdout>"
yy3_383:
		++source->cursor();
		if ((source->limit() - source->cursor()) < 10) source->fill(10);
		yych = *source->cursor();
		if (yych <= '\f') {
			if (yych == '\t') goto yy3_383;
			if (yych <= '\n') goto yy3_278;
			goto yy3_383;
		} else {
			if (yych <= ' ') {
				if (yych <= 0x1F) goto yy3_278;
				goto yy3_383;
			} else {
				if (yych != 'b') goto yy3_278;
			}
		}
yy3_385:
		yych = *++source->cursor();
		if (yych != 'e') goto yy3_278;
		yych = *++source->cursor();
		if (yych != 'g') goto yy3_278;
		yych = *++source->cursor();
		if (yych != 'i') goto yy3_278;
		yych = *++source->cursor();
		if (yych != 'n') goto yy3_278;
		yych = *++source->cursor();
		if (yych <= '\f') {
			if (yych == '\t') goto yy3_390;
			if (yych <= '\n') goto yy3_278;
		} else {
			if (yych <= ' ') {
				if (yych <= 0x1F) goto yy3_278;
			} else {
				if (yych == '_') goto yy3_392;
				goto yy3_278;
			}
		}
yy3_390:
		++source->cursor();
		if ((source->limit() - source->cursor()) < 4) source->fill(4);
		yych = *source->cursor();
		if (yych <= ' ') {
			if (yych <= '\n') {
				if (yych == '\t') goto yy3_390;
				goto yy3_278;
			} else {
				if (yych <= '\f') goto yy3_390;
				if (yych <= 0x1F) goto yy3_278;
				goto yy3_390;
			}
		} else {
			if (yych <= 'e') {
				if (yych == 'a') goto yy3_412;
				goto yy3_278;
			} else {
				if (yych <= 'f') goto yy3_414;
				if (yych == 'l') goto yy3_413;
				goto yy3_278;
			}
		}
yy3_392:
		yych = *++source->cursor();
		if (yych <= 'e') {
			if (yych != 'a') goto yy3_278;
		} else {
			if (yych <= 'f') goto yy3_395;
			if (yych == 'l') goto yy3_394;
			goto yy3_278;
		}
		yych = *++source->cursor();
		if (yych == 's') goto yy3_407;
		goto yy3_278;
yy3_394:
		yych = *++source->cursor();
		if (yych == 'u') goto yy3_402;
		goto yy3_278;
yy3_395:
		yych = *++source->cursor();
		if (yych != '2') goto yy3_278;
		yych = *++source->cursor();
		if (yych != 'l') goto yy3_278;
		yych = *++source->cursor();
		if (yych != 'p') goto yy3_278;
yy3_398:
		++source->cursor();
		if (source->limit() <= source->cursor()) source->fill(1);
		yych = *source->cursor();
		if (yych <= '\f') {
			if (yych == '\t') goto yy3_398;
			if (yych <= '\n') goto yy3_278;
			goto yy3_398;
		} else {
			if (yych <= ' ') {
				if (yych <= 0x1F) goto yy3_278;
				goto yy3_398;
			} else {
				if (yych != '.') goto yy3_278;
			}
		}
		++source->cursor();
#line 177 "bcplus/parser/detail/Scanner.3.re2c"
		{
												  _cond = yycF2LP_CP;
												  BLK_INIT;
												  goto yyc_F2LP_CP;
												}
#line 2282 "<stdout>"
yy3_402:
		yych = *++source->cursor();
		if (yych != 'a') goto yy3_278;
yy3_403:
		++source->cursor();
		if (source->limit() <= source->cursor()) source->fill(1);
		yych = *source->cursor();
		if (yych <= '\f') {
			if (yych == '\t') goto yy3_403;
			if (yych <= '\n') goto yy3_278;
			goto yy3_403;
		} else {
			if (yych <= ' ') {
				if (yych <= 0x1F) goto yy3_278;
				goto yy3_403;
			} else {
				if (yych != '.') goto yy3_278;
			}
		}
		++source->cursor();
#line 160 "bcplus/parser/detail/Scanner.3.re2c"
		{
												  _cond = yycLUA_CP;
												  BLK_INIT;
												  goto yyc_LUA_CP;
												}
#line 2309 "<stdout>"
yy3_407:
		yych = *++source->cursor();
		if (yych != 'p') goto yy3_278;
yy3_408:
		++source->cursor();
		if (source->limit() <= source->cursor()) source->fill(1);
		yych = *source->cursor();
		if (yych <= '\f') {
			if (yych == '\t') goto yy3_408;
			if (yych <= '\n') goto yy3_278;
			goto yy3_408;
		} else {
			if (yych <= ' ') {
				if (yych <= 0x1F) goto yy3_278;
				goto yy3_408;
			} else {
				if (yych != '.') goto yy3_278;
			}
		}
		++source->cursor();
#line 143 "bcplus/parser/detail/Scanner.3.re2c"
		{
												  _cond = yycASP_CP;
												  BLK_INIT;
												  goto yyc_ASP_CP;
												}
#line 2336 "<stdout>"
yy3_412:
		yych = *++source->cursor();
		if (yych == 's') goto yy3_426;
		goto yy3_278;
yy3_413:
		yych = *++source->cursor();
		if (yych == 'u') goto yy3_421;
		goto yy3_278;
yy3_414:
		yych = *++source->cursor();
		if (yych != '2') goto yy3_278;
		yych = *++source->cursor();
		if (yych != 'l') goto yy3_278;
		yych = *++source->cursor();
		if (yych != 'p') goto yy3_278;
yy3_417:
		++source->cursor();
		if (source->limit() <= source->cursor()) source->fill(1);
		yych = *source->cursor();
		if (yych <= '\f') {
			if (yych == '\t') goto yy3_417;
			if (yych <= '\n') goto yy3_278;
			goto yy3_417;
		} else {
			if (yych <= ' ') {
				if (yych <= 0x1F) goto yy3_278;
				goto yy3_417;
			} else {
				if (yych != '.') goto yy3_278;
			}
		}
		++source->cursor();
#line 183 "bcplus/parser/detail/Scanner.3.re2c"
		{
												  _cond = yycF2LP_CP;
												  BLK_INIT;
												  goto yyc_F2LP_CP;
												}
#line 2375 "<stdout>"
yy3_421:
		yych = *++source->cursor();
		if (yych != 'a') goto yy3_278;
yy3_422:
		++source->cursor();
		if (source->limit() <= source->cursor()) source->fill(1);
		yych = *source->cursor();
		if (yych <= '\f') {
			if (yych == '\t') goto yy3_422;
			if (yych <= '\n') goto yy3_278;
			goto yy3_422;
		} else {
			if (yych <= ' ') {
				if (yych <= 0x1F) goto yy3_278;
				goto yy3_422;
			} else {
				if (yych != '.') goto yy3_278;
			}
		}
		++source->cursor();
#line 166 "bcplus/parser/detail/Scanner.3.re2c"
		{
												  _cond = yycLUA_CP;
												  BLK_INIT;
												  goto yyc_LUA_CP;
												}
#line 2402 "<stdout>"
yy3_426:
		yych = *++source->cursor();
		if (yych != 'p') goto yy3_278;
yy3_427:
		++source->cursor();
		if (source->limit() <= source->cursor()) source->fill(1);
		yych = *source->cursor();
		if (yych <= '\f') {
			if (yych == '\t') goto yy3_427;
			if (yych <= '\n') goto yy3_278;
			goto yy3_427;
		} else {
			if (yych <= ' ') {
				if (yych <= 0x1F) goto yy3_278;
				goto yy3_427;
			} else {
				if (yych != '.') goto yy3_278;
			}
		}
		++source->cursor();
#line 149 "bcplus/parser/detail/Scanner.3.re2c"
		{
												  _cond = yycASP_CP;
												  BLK_INIT;
												  goto yyc_ASP_CP;
												}
#line 2429 "<stdout>"
yy3_431:
		++source->cursor();
		if (source->limit() <= source->cursor()) source->fill(1);
		yych = *source->cursor();
yy3_432:
		if (yybm[0+yych] & 128) {
			goto yy3_431;
		}
		goto yy3_305;
yy3_433:
		++source->cursor();
#line 121 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_BIG_CONJ;						goto re2c_finish;					}
#line 2443 "<stdout>"
yy3_435:
		++source->cursor();
#line 120 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_INT_DIV;						goto re2c_finish;					}
#line 2448 "<stdout>"
yy3_437:
		++source->cursor();
#line 116 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_DBL_PERIOD;					goto re2c_finish;					}
#line 2453 "<stdout>"
yy3_439:
		++source->cursor();
		if ((yych = *source->cursor()) == '>') goto yy3_441;
#line 198 "bcplus/parser/detail/Scanner.3.re2c"
		{ 
												  ret = T_ARROW_RDASH; 
												  if (_in_macro) _cond = yycMACRO;		
												  goto re2c_finish;	
												}
#line 2463 "<stdout>"
yy3_441:
		++source->cursor();
#line 92 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_IMPL;							goto re2c_finish;					}
#line 2468 "<stdout>"
yy3_443:
		++source->cursor();
#line 114 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_DBL_PLUS;						goto re2c_finish;					}
#line 2473 "<stdout>"
yy3_445:
		++source->cursor();
#line 112 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_DBL_AMP;						goto re2c_finish;					}
#line 2478 "<stdout>"
yy3_447:
		++source->cursor();
		if (source->limit() <= source->cursor()) source->fill(1);
		yych = *source->cursor();
		if (yych <= '/') goto yy3_449;
		if (yych <= '9') goto yy3_447;
yy3_449:
#line 207 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_POUND_INTEGER;				goto re2c_finish;					}
#line 2488 "<stdout>"
yy3_450:
		++source->cursor();
		if (source->limit() <= source->cursor()) source->fill(1);
		yych = *source->cursor();
yy3_451:
		if (yych <= 'Z') {
			if (yych <= '/') goto yy3_452;
			if (yych <= '9') goto yy3_450;
			if (yych >= 'A') goto yy3_450;
		} else {
			if (yych <= '_') {
				if (yych >= '_') goto yy3_450;
			} else {
				if (yych <= '`') goto yy3_452;
				if (yych <= 'z') goto yy3_450;
			}
		}
yy3_452:
#line 206 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_POUND_IDENTIFIER;				goto re2c_finish;					}
#line 2509 "<stdout>"
yy3_453:
		yych = *++source->cursor();
		if (yych != 'e') goto yy3_451;
		yych = *++source->cursor();
		if (yych != 'g') goto yy3_451;
		yych = *++source->cursor();
		if (yych != 'i') goto yy3_451;
		yych = *++source->cursor();
		if (yych != 'n') goto yy3_451;
		yych = *++source->cursor();
		if (yych != '_') goto yy3_451;
		yych = *++source->cursor();
		if (yych <= 'e') {
			if (yych != 'a') goto yy3_451;
		} else {
			if (yych <= 'f') goto yy3_460;
			if (yych == 'l') goto yy3_461;
			goto yy3_451;
		}
		yych = *++source->cursor();
		if (yych == 's') goto yy3_475;
		goto yy3_451;
yy3_460:
		yych = *++source->cursor();
		if (yych == '2') goto yy3_468;
		goto yy3_451;
yy3_461:
		yych = *++source->cursor();
		if (yych != 'u') goto yy3_451;
		yych = *++source->cursor();
		if (yych != 'a') goto yy3_451;
		++source->cursor();
		if ((yych = *source->cursor()) <= 'Z') {
			if (yych <= '/') goto yy3_466;
			if (yych <= '9') goto yy3_450;
			if (yych <= '@') goto yy3_466;
			goto yy3_450;
		} else {
			if (yych <= '_') {
				if (yych <= '^') goto yy3_466;
				goto yy3_450;
			} else {
				if (yych <= '`') goto yy3_466;
				if (yych <= 'z') goto yy3_450;
				goto yy3_466;
			}
		}
yy3_464:
#line 171 "bcplus/parser/detail/Scanner.3.re2c"
		{
												  _cond = yycLUA_GR;
												  BLK_INIT;
												  goto yyc_LUA_GR;
												}
#line 2564 "<stdout>"
yy3_465:
		++source->cursor();
		if (source->limit() <= source->cursor()) source->fill(1);
		yych = *source->cursor();
yy3_466:
		if (yych <= '\f') {
			if (yych == '\t') goto yy3_465;
			if (yych <= '\n') goto yy3_464;
			goto yy3_465;
		} else {
			if (yych <= ' ') {
				if (yych <= 0x1F) goto yy3_464;
				goto yy3_465;
			} else {
				if (yych != '.') goto yy3_464;
			}
		}
		yych = *++source->cursor();
		goto yy3_464;
yy3_468:
		yych = *++source->cursor();
		if (yych != 'l') goto yy3_451;
		yych = *++source->cursor();
		if (yych != 'p') goto yy3_451;
		++source->cursor();
		if ((yych = *source->cursor()) <= 'Z') {
			if (yych <= '/') goto yy3_473;
			if (yych <= '9') goto yy3_450;
			if (yych <= '@') goto yy3_473;
			goto yy3_450;
		} else {
			if (yych <= '_') {
				if (yych <= '^') goto yy3_473;
				goto yy3_450;
			} else {
				if (yych <= '`') goto yy3_473;
				if (yych <= 'z') goto yy3_450;
				goto yy3_473;
			}
		}
yy3_471:
#line 188 "bcplus/parser/detail/Scanner.3.re2c"
		{
												  _cond = yycF2LP_GR;
												  BLK_INIT;
												  goto yyc_F2LP_GR;
												}
#line 2612 "<stdout>"
yy3_472:
		++source->cursor();
		if (source->limit() <= source->cursor()) source->fill(1);
		yych = *source->cursor();
yy3_473:
		if (yych <= '\f') {
			if (yych == '\t') goto yy3_472;
			if (yych <= '\n') goto yy3_471;
			goto yy3_472;
		} else {
			if (yych <= ' ') {
				if (yych <= 0x1F) goto yy3_471;
				goto yy3_472;
			} else {
				if (yych != '.') goto yy3_471;
			}
		}
		yych = *++source->cursor();
		goto yy3_471;
yy3_475:
		yych = *++source->cursor();
		if (yych != 'p') goto yy3_451;
		++source->cursor();
		if ((yych = *source->cursor()) <= 'Z') {
			if (yych <= '/') goto yy3_479;
			if (yych <= '9') goto yy3_450;
			if (yych <= '@') goto yy3_479;
			goto yy3_450;
		} else {
			if (yych <= '_') {
				if (yych <= '^') goto yy3_479;
				goto yy3_450;
			} else {
				if (yych <= '`') goto yy3_479;
				if (yych <= 'z') goto yy3_450;
				goto yy3_479;
			}
		}
yy3_477:
#line 154 "bcplus/parser/detail/Scanner.3.re2c"
		{
												  _cond = yycASP_GR;
												  BLK_INIT;
												  goto yyc_ASP_GR;
												}
#line 2658 "<stdout>"
yy3_478:
		++source->cursor();
		if (source->limit() <= source->cursor()) source->fill(1);
		yych = *source->cursor();
yy3_479:
		if (yych <= '\f') {
			if (yych == '\t') goto yy3_478;
			if (yych <= '\n') goto yy3_477;
			goto yy3_478;
		} else {
			if (yych <= ' ') {
				if (yych <= 0x1F) goto yy3_477;
				goto yy3_478;
			} else {
				if (yych != '.') goto yy3_477;
			}
		}
		++source->cursor();
		yych = *source->cursor();
		goto yy3_477;
	}
/* *********************************** */
yyc_SGL_STRING:
	if ((source->limit() - source->cursor()) < 2) source->fill(2);
	yych = *source->cursor();
	if (yych <= '&') {
		if (yych <= 0x00) goto yy3_483;
		if (yych == '\n') goto yy3_489;
		goto yy3_485;
	} else {
		if (yych <= '\'') goto yy3_486;
		if (yych == '\\') goto yy3_488;
		goto yy3_485;
	}
yy3_483:
	++source->cursor();
yy3_484:
#line 234 "bcplus/parser/detail/Scanner.3.re2c"
	{												goto yyc_SGL_STRING;				}
#line 2698 "<stdout>"
yy3_485:
	yych = *++source->cursor();
	goto yy3_484;
yy3_486:
	++source->cursor();
#line 228 "bcplus/parser/detail/Scanner.3.re2c"
	{ 
												  _cond = yycNORMAL; 
												  ret = T_STRING_LITERAL;	
												  postskip = 1;
												  goto re2c_finish;					
												}
#line 2711 "<stdout>"
yy3_488:
	yych = *++source->cursor();
	if (yych == '\'') goto yy3_491;
	goto yy3_484;
yy3_489:
	++source->cursor();
#line 226 "bcplus/parser/detail/Scanner.3.re2c"
	{ source->newline();				 			goto yyc_SGL_STRING; 				}
#line 2720 "<stdout>"
yy3_491:
	++source->cursor();
#line 227 "bcplus/parser/detail/Scanner.3.re2c"
	{ 												goto yyc_SGL_STRING; 				}
#line 2725 "<stdout>"
}
#line 637 "bcplus/parser/detail/Scanner.3.re2c"

re2c_finish:
	u::ref_ptr<ReferencedString> str = new ReferencedString();
	if (ret != T_EOF) {
		if (use_blk)
			str->assign(blk.str());
		else
			str->assign(source->token() + preskip, (size_t)(source->cursor() - source->token() - preskip - postskip));
	} else {
		str->assign("<EOF>");
	}

	return new Token(ret, str, begin, source->loc());
}

}}}
