/* Generated by re2c 0.13.5 on Wed Apr  2 23:50:20 2014 */
#line 1 "bcplus/parser/detail/Scanner.1.re2c"

#include <sstream>

#include <boost/filesystem.hpp>
#include <boost/filesystem/fstream.hpp>

#include "bcplus/parser/detail/Scanner.h"
#include "bcplus/parser/detail/lemon_parser.h"

#include "bcplus/Location.h"
#include "bcplus/parser/Token.h"

#include "bcplus/parser/detail/ScannerSource.h"
#include "bcplus/parser/detail/ScannerRawSource.h"
#include "bcplus/parser/detail/ScannerTokenSource.h"
#include "bcplus/parser/detail/ScannerFileSource.h"
#include "bcplus/parser/detail/ScannerBufferSource.h"

namespace u = babb::utils; 
namespace fs = boost::filesystem;

namespace bcplus {
namespace parser {
namespace detail {

Scanner::Scanner(Configuration const* config)
	: _cond(yycNORMAL), _config(config), _in_macro(false) {
	// Intentionally left blank
}

Scanner::~Scanner() {
	// Intentionally left blank
}

bool Scanner::push_front(fs::path const& file, bool squelch) {
	u::ref_ptr<ScannerFileSource> src = new ScannerFileSource(_config, file, squelch);
	if (!src->good()) return false;
	_sources.push_front(src.get());
	return true;
}

bool Scanner::push_back(fs::path const& file, bool squelch) {
	u::ref_ptr<ScannerFileSource> src = new ScannerFileSource(_config, file, squelch);
	if (!src->good()) return false;
	_sources.push_back(src.get());
	return true;
}

void Scanner::push_front(char const* buffer, Location const& loc, bool track_position) {
	u::ref_ptr<ScannerBufferSource> src = new ScannerBufferSource(_config, buffer, loc, track_position);
	_sources.push_front(src.get());
}

void Scanner::push_back(char const* buffer, Location const& loc, bool track_position) {
	u::ref_ptr<ScannerBufferSource> src = new ScannerBufferSource(_config, buffer, loc, track_position);
	_sources.push_back(src.get());
}

void Scanner::push_back(Token* token) {
	if (!_sources.size() || _sources.back()->type() != ScannerSource::Type::TOKENS) {
		_sources.push_back(new ScannerTokenSource(token));
	} else ((ScannerTokenSource*)_sources.back().get())->push_back(token);
}

void Scanner::push_front(Token* token) {
	if (!_sources.size() || _sources.front()->type() != ScannerSource::Type::TOKENS) {
		_sources.push_front(new ScannerTokenSource(token));
	} else ((ScannerTokenSource*)_sources.front().get())->push_front(token);
}

void Scanner::push_back(TokenList* tokens) {
	if (!_sources.size() || _sources.back()->type() != ScannerSource::Type::TOKENS) {
		_sources.push_back(new ScannerTokenSource(tokens));
	} else ((ScannerTokenSource*)_sources.back().get())->push_back(tokens);
}

void Scanner::push_front(TokenList* tokens) {
	if (!_sources.size() || _sources.front()->type() != ScannerSource::Type::TOKENS) {
		_sources.push_front(new ScannerTokenSource(tokens));
	} else ((ScannerTokenSource*)_sources.front().get())->push_front(tokens);
}


Token* Scanner::readToken() {
	u::ref_ptr<Token> token = NULL;
	if (!size()) {
		Location l = loc();
		token  = new Token(T_EOF, new ReferencedString("<EOF>"), l, l);
	} else {
		do {
			ScannerSource* src = _sources.front();
#ifndef NDEBUG
			_config->ostream(Verb::TRACE_SCANNER) << "TRACE: " << size() << " sources, reading from \"" 
				<< (src->loc().file() ? src->loc().file()->native() : std::string("<NULL>")) << "\"." << std::endl;
#endif
			switch(src->type()) {
			case ScannerSource::Type::RAW:
				token = tokenize((ScannerRawSource*)src);
				break;
			case ScannerSource::Type::TOKENS:
				token = ((ScannerTokenSource*)src)->next();
				break;
			}
	
			if (!token || token->type() == T_ERR_IO) {
#ifndef NDEBUG
				_config->ostream(Verb::TRACE_SCANNER) << "TRACE: Scanner encountered IO error." << std::endl;
#endif
				_sources.pop_front();
			} else if (token->type() == T_EOF) {
#ifndef NDEBUG
				_config->ostream(Verb::TRACE_SCANNER) << "TRACE: Scanner encountered end of input source." << std::endl;
#endif
				_sources.pop_front();
			}
		} while (token && token->type() == T_EOF && size());
	}
	
	if (!token) {
		Location l = loc();
#ifndef NDEBUG
		_config->ostream(Verb::TRACE_SCANNER) << "TRACE: Scanner got a null token." << std::endl;
#endif
		token  = new Token(T_ERR_IO, new ReferencedString("<IO ERROR>"), l, l);
	}

#ifndef NDEBUG
	_config->ostream(Verb::TRACE_SCANNER) << "TRACE: " << token->beginLoc() << ": (" << token->typeString() << "): \"" << *token << "\": Read from scanner." << std::endl;
#endif

	return token.release();
}


Token* Scanner::tokenize(ScannerRawSource* source) {
	if (source->eof()) return new Token(T_EOF, new ReferencedString("<EOF>"), source->loc(), source->loc());
	else if (!source->good()) return new Token(T_ERR_IO, new ReferencedString("<IO ERROR>"), source->loc(), source->loc());


	int ret;
	Location begin;
	char const* marker;

re2c_start:
	marker = source->token() = source->cursor();
	begin = source->loc();

	if (_cond == yycNORMAL) {
			
#line 153 "<stdout>"
{
	char yych;
	unsigned int yyaccept = 0;
	goto yyc_NORMAL;
/* *********************************** */
yyc_NORMAL:
	{
		static const unsigned char yybm[] = {
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0, 128,   0, 128, 128,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			128,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
		};

		if ((source->limit() - source->cursor()) < 20) source->fill(20);
		yych = *source->cursor();
		if (yych <= 'h') {
			if (yych <= ' ') {
				if (yych <= '\t') {
					if (yych <= 0x00) goto yy2;
					if (yych <= 0x08) goto yy4;
					goto yy6;
				} else {
					if (yych <= '\n') goto yy27;
					if (yych <= '\f') goto yy6;
					if (yych <= 0x1F) goto yy4;
					goto yy6;
				}
			} else {
				if (yych <= 'c') {
					if (yych <= '`') goto yy4;
					if (yych <= 'a') goto yy8;
					if (yych <= 'b') goto yy9;
					goto yy10;
				} else {
					if (yych <= 'd') goto yy11;
					if (yych <= 'e') goto yy12;
					if (yych <= 'f') goto yy13;
					goto yy4;
				}
			}
		} else {
			if (yych <= 'p') {
				if (yych <= 'l') {
					if (yych <= 'i') goto yy14;
					if (yych <= 'k') goto yy4;
					goto yy15;
				} else {
					if (yych <= 'm') goto yy16;
					if (yych <= 'n') goto yy17;
					if (yych <= 'o') goto yy18;
					goto yy19;
				}
			} else {
				if (yych <= 't') {
					if (yych <= 'q') goto yy20;
					if (yych <= 'r') goto yy21;
					if (yych <= 's') goto yy22;
					goto yy23;
				} else {
					if (yych <= 'u') goto yy24;
					if (yych <= 'v') goto yy25;
					if (yych <= 'w') goto yy26;
					goto yy4;
				}
			}
		}
yy2:
		++source->cursor();
#line 166 "bcplus/parser/detail/Scanner.1.re2c"
		{ ret = T_EOF; 							goto re2c_finish; 					}
#line 253 "<stdout>"
yy4:
		++source->cursor();
yy5:
#line 228 "bcplus/parser/detail/Scanner.1.re2c"
		{ goto re2c_notkw; }
#line 259 "<stdout>"
yy6:
		++source->cursor();
#line 165 "bcplus/parser/detail/Scanner.1.re2c"
		{ 										goto re2c_start; 					}
#line 264 "<stdout>"
yy8:
		yyaccept = 0;
		yych = *(source->marker() = ++source->cursor());
		switch (yych) {
		case 'b':	goto yy364;
		case 'c':	goto yy370;
		case 'd':	goto yy369;
		case 'f':	goto yy368;
		case 'l':	goto yy365;
		case 's':	goto yy367;
		case 't':	goto yy366;
		default:	goto yy5;
		}
yy9:
		yych = *++source->cursor();
		if (yych == 'y') goto yy362;
		goto yy5;
yy10:
		yyaccept = 0;
		yych = *(source->marker() = ++source->cursor());
		if (yych == 'a') goto yy340;
		if (yych == 'o') goto yy339;
		goto yy5;
yy11:
		yyaccept = 0;
		yych = *(source->marker() = ++source->cursor());
		if (yych == 'e') goto yy323;
		goto yy5;
yy12:
		yyaccept = 0;
		yych = *(source->marker() = ++source->cursor());
		if (yych == 'q') goto yy285;
		if (yych == 'x') goto yy287;
		goto yy5;
yy13:
		yyaccept = 0;
		yych = *(source->marker() = ++source->cursor());
		if (yych == 'a') goto yy280;
		goto yy5;
yy14:
		yyaccept = 0;
		yych = *(source->marker() = ++source->cursor());
		if (yych <= 'l') {
			if (yych == 'f') goto yy236;
			goto yy5;
		} else {
			if (yych <= 'm') goto yy235;
			if (yych <= 'n') goto yy234;
			goto yy5;
		}
yy15:
		yyaccept = 0;
		yych = *(source->marker() = ++source->cursor());
		if (yych == 'a') goto yy229;
		goto yy5;
yy16:
		yyaccept = 0;
		yych = *(source->marker() = ++source->cursor());
		if (yych == 'a') goto yy190;
		if (yych == 'o') goto yy189;
		goto yy5;
yy17:
		yyaccept = 0;
		yych = *(source->marker() = ++source->cursor());
		if (yych == 'e') goto yy155;
		if (yych == 'o') goto yy154;
		goto yy5;
yy18:
		yyaccept = 0;
		yych = *(source->marker() = ++source->cursor());
		if (yych == 'b') goto yy147;
		if (yych == 'f') goto yy145;
		goto yy5;
yy19:
		yyaccept = 0;
		yych = *(source->marker() = ++source->cursor());
		if (yych == 'o') goto yy129;
		goto yy5;
yy20:
		yyaccept = 0;
		yych = *(source->marker() = ++source->cursor());
		if (yych == 'u') goto yy124;
		goto yy5;
yy21:
		yyaccept = 0;
		yych = *(source->marker() = ++source->cursor());
		if (yych == 'i') goto yy119;
		goto yy5;
yy22:
		yyaccept = 0;
		yych = *(source->marker() = ++source->cursor());
		switch (yych) {
		case 'd':	goto yy56;
		case 'h':	goto yy58;
		case 'i':	goto yy55;
		case 'o':	goto yy57;
		case 't':	goto yy54;
		default:	goto yy5;
		}
yy23:
		yyaccept = 0;
		yych = *(source->marker() = ++source->cursor());
		if (yych == 'r') goto yy50;
		goto yy5;
yy24:
		yyaccept = 0;
		yych = *(source->marker() = ++source->cursor());
		if (yych == 'n') goto yy44;
		goto yy5;
yy25:
		yyaccept = 0;
		yych = *(source->marker() = ++source->cursor());
		if (yych == 'a') goto yy35;
		goto yy5;
yy26:
		yyaccept = 0;
		yych = *(source->marker() = ++source->cursor());
		if (yych == 'h') goto yy29;
		goto yy5;
yy27:
		++source->cursor();
#line 164 "bcplus/parser/detail/Scanner.1.re2c"
		{ source->newline();		 			goto re2c_start; 					}
#line 388 "<stdout>"
yy29:
		yych = *++source->cursor();
		if (yych == 'e') goto yy31;
yy30:
		source->cursor() = source->marker();
		if (yyaccept <= 2) {
			if (yyaccept <= 1) {
				if (yyaccept <= 0) {
					goto yy5;
				} else {
					goto yy167;
				}
			} else {
				goto yy237;
			}
		} else {
			if (yyaccept <= 3) {
				goto yy259;
			} else {
				goto yy296;
			}
		}
yy31:
		yych = *++source->cursor();
		if (yych != 'r') goto yy30;
		yych = *++source->cursor();
		if (yych != 'e') goto yy30;
		++source->cursor();
#line 218 "bcplus/parser/detail/Scanner.1.re2c"
		{ ret = T_WHERE;						goto re2c_finish;					}
#line 419 "<stdout>"
yy35:
		yych = *++source->cursor();
		if (yych != 'r') goto yy30;
		yych = *++source->cursor();
		if (yych != 'i') goto yy30;
		yych = *++source->cursor();
		if (yych != 'a') goto yy30;
		yych = *++source->cursor();
		if (yych != 'b') goto yy30;
		yych = *++source->cursor();
		if (yych != 'l') goto yy30;
		yych = *++source->cursor();
		if (yych != 'e') goto yy30;
		yych = *++source->cursor();
		if (yych != 's') goto yy30;
		++source->cursor();
#line 173 "bcplus/parser/detail/Scanner.1.re2c"
		{ ret = T_VARIABLES;					goto re2c_finish;					}
#line 438 "<stdout>"
yy44:
		yych = *++source->cursor();
		if (yych != 'l') goto yy30;
		yych = *++source->cursor();
		if (yych != 'e') goto yy30;
		yych = *++source->cursor();
		if (yych != 's') goto yy30;
		yych = *++source->cursor();
		if (yych != 's') goto yy30;
		++source->cursor();
#line 217 "bcplus/parser/detail/Scanner.1.re2c"
		{ ret = T_UNLESS;						goto re2c_finish;					}
#line 451 "<stdout>"
yy50:
		yych = *++source->cursor();
		if (yych != 'u') goto yy30;
		yych = *++source->cursor();
		if (yych != 'e') goto yy30;
		++source->cursor();
#line 226 "bcplus/parser/detail/Scanner.1.re2c"
		{ ret = T_TRUE;							goto re2c_finish;					}
#line 460 "<stdout>"
yy54:
		yych = *++source->cursor();
		if (yych == 'r') goto yy84;
		goto yy30;
yy55:
		yych = *++source->cursor();
		if (yych == 'm') goto yy73;
		goto yy30;
yy56:
		yych = *++source->cursor();
		if (yych == 'F') goto yy66;
		goto yy30;
yy57:
		yych = *++source->cursor();
		if (yych == 'r') goto yy62;
		goto yy30;
yy58:
		yych = *++source->cursor();
		if (yych != 'o') goto yy30;
		yych = *++source->cursor();
		if (yych != 'w') goto yy30;
		++source->cursor();
#line 171 "bcplus/parser/detail/Scanner.1.re2c"
		{ ret = T_SHOW;							goto re2c_finish;					}
#line 485 "<stdout>"
yy62:
		yych = *++source->cursor();
		if (yych != 't') goto yy30;
		yych = *++source->cursor();
		if (yych != 's') goto yy30;
		++source->cursor();
#line 172 "bcplus/parser/detail/Scanner.1.re2c"
		{ ret = T_SORTS;						goto re2c_finish;					}
#line 494 "<stdout>"
yy66:
		yych = *++source->cursor();
		if (yych != 'l') goto yy30;
		yych = *++source->cursor();
		if (yych != 'u') goto yy30;
		yych = *++source->cursor();
		if (yych != 'e') goto yy30;
		yych = *++source->cursor();
		if (yych != 'n') goto yy30;
		yych = *++source->cursor();
		if (yych != 't') goto yy30;
		++source->cursor();
#line 211 "bcplus/parser/detail/Scanner.1.re2c"
		{ ret = T_SDFLUENT;						goto re2c_finish;					}
#line 509 "<stdout>"
yy73:
		yych = *++source->cursor();
		if (yych != 'p') goto yy30;
		yych = *++source->cursor();
		if (yych != 'l') goto yy30;
		yych = *++source->cursor();
		if (yych != 'e') goto yy30;
		yych = *++source->cursor();
		if (yych != 'F') goto yy30;
		yych = *++source->cursor();
		if (yych != 'l') goto yy30;
		yych = *++source->cursor();
		if (yych != 'u') goto yy30;
		yych = *++source->cursor();
		if (yych != 'e') goto yy30;
		yych = *++source->cursor();
		if (yych != 'n') goto yy30;
		yych = *++source->cursor();
		if (yych != 't') goto yy30;
		++source->cursor();
#line 212 "bcplus/parser/detail/Scanner.1.re2c"
		{ ret = T_SIMPLEFLUENT;					goto re2c_finish;					}
#line 532 "<stdout>"
yy84:
		yych = *++source->cursor();
		if (yych != 'o') goto yy30;
		yych = *++source->cursor();
		if (yych != 'n') goto yy30;
		yych = *++source->cursor();
		if (yych != 'g') goto yy30;
		yych = *++source->cursor();
		if (yych == '_') goto yy90;
		if (yych == 'n') goto yy30;
		goto yy89;
yy88:
		++source->cursor();
		if ((source->limit() - source->cursor()) < 13) source->fill(13);
		yych = *source->cursor();
yy89:
		if (yybm[0+yych] & 128) {
			goto yy88;
		}
		if (yych == 'n') goto yy105;
		goto yy30;
yy90:
		yych = *++source->cursor();
		if (yych != 'n') goto yy30;
		yych = *++source->cursor();
		if (yych != 'o') goto yy30;
		yych = *++source->cursor();
		if (yych != 'c') goto yy30;
		yych = *++source->cursor();
		if (yych != 'o') goto yy30;
		yych = *++source->cursor();
		if (yych != 'n') goto yy30;
		yych = *++source->cursor();
		if (yych != 'c') goto yy30;
		yych = *++source->cursor();
		if (yych != 'u') goto yy30;
		yych = *++source->cursor();
		if (yych != 'r') goto yy30;
		yych = *++source->cursor();
		if (yych != 'r') goto yy30;
		yych = *++source->cursor();
		if (yych != 'e') goto yy30;
		yych = *++source->cursor();
		if (yych != 'n') goto yy30;
		yych = *++source->cursor();
		if (yych != 'c') goto yy30;
		yych = *++source->cursor();
		if (yych != 'y') goto yy30;
		++source->cursor();
#line 214 "bcplus/parser/detail/Scanner.1.re2c"
		{ ret = T_STRONG_NOCONCURRENCY;			goto re2c_finish;					}
#line 584 "<stdout>"
yy105:
		yych = *++source->cursor();
		if (yych != 'o') goto yy30;
		yych = *++source->cursor();
		if (yych != 'c') goto yy30;
		yych = *++source->cursor();
		if (yych != 'o') goto yy30;
		yych = *++source->cursor();
		if (yych != 'n') goto yy30;
		yych = *++source->cursor();
		if (yych != 'c') goto yy30;
		yych = *++source->cursor();
		if (yych != 'u') goto yy30;
		yych = *++source->cursor();
		if (yych != 'r') goto yy30;
		yych = *++source->cursor();
		if (yych != 'r') goto yy30;
		yych = *++source->cursor();
		if (yych != 'e') goto yy30;
		yych = *++source->cursor();
		if (yych != 'n') goto yy30;
		yych = *++source->cursor();
		if (yych != 'c') goto yy30;
		yych = *++source->cursor();
		if (yych != 'y') goto yy30;
		++source->cursor();
#line 213 "bcplus/parser/detail/Scanner.1.re2c"
		{ ret = T_STRONG_NOCONCURRENCY;			goto re2c_finish;					}
#line 613 "<stdout>"
yy119:
		yych = *++source->cursor();
		if (yych != 'g') goto yy30;
		yych = *++source->cursor();
		if (yych != 'i') goto yy30;
		yych = *++source->cursor();
		if (yych != 'd') goto yy30;
		++source->cursor();
#line 210 "bcplus/parser/detail/Scanner.1.re2c"
		{ ret = T_RIGID;						goto re2c_finish;					}
#line 624 "<stdout>"
yy124:
		yych = *++source->cursor();
		if (yych != 'e') goto yy30;
		yych = *++source->cursor();
		if (yych != 'r') goto yy30;
		yych = *++source->cursor();
		if (yych != 'y') goto yy30;
		++source->cursor();
#line 170 "bcplus/parser/detail/Scanner.1.re2c"
		{ ret = T_QUERY;						goto re2c_finish;					}
#line 635 "<stdout>"
yy129:
		yych = *++source->cursor();
		if (yych != 's') goto yy30;
		yych = *++source->cursor();
		if (yych != 's') goto yy30;
		yych = *++source->cursor();
		if (yych != 'i') goto yy30;
		yych = *++source->cursor();
		if (yych != 'b') goto yy30;
		yych = *++source->cursor();
		if (yych != 'l') goto yy30;
		yych = *++source->cursor();
		if (yych != 'y') goto yy30;
		yych = *++source->cursor();
		if (yych == 'c') goto yy30;
		goto yy137;
yy136:
		++source->cursor();
		if ((source->limit() - source->cursor()) < 6) source->fill(6);
		yych = *source->cursor();
yy137:
		if (yych <= '\f') {
			if (yych == '\t') goto yy136;
			if (yych <= '\n') goto yy30;
			goto yy136;
		} else {
			if (yych <= ' ') {
				if (yych <= 0x1F) goto yy30;
				goto yy136;
			} else {
				if (yych != 'c') goto yy30;
			}
		}
		yych = *++source->cursor();
		if (yych != 'a') goto yy30;
		yych = *++source->cursor();
		if (yych != 'u') goto yy30;
		yych = *++source->cursor();
		if (yych != 's') goto yy30;
		yych = *++source->cursor();
		if (yych != 'e') goto yy30;
		yych = *++source->cursor();
		if (yych != 'd') goto yy30;
		++source->cursor();
#line 209 "bcplus/parser/detail/Scanner.1.re2c"
		{ ret = T_POSSIBLY_CAUSED;				goto re2c_finish;					}
#line 682 "<stdout>"
yy145:
		++source->cursor();
#line 208 "bcplus/parser/detail/Scanner.1.re2c"
		{ ret = T_OF;							goto re2c_finish;					}
#line 687 "<stdout>"
yy147:
		yych = *++source->cursor();
		if (yych != 'j') goto yy30;
		yych = *++source->cursor();
		if (yych != 'e') goto yy30;
		yych = *++source->cursor();
		if (yych != 'c') goto yy30;
		yych = *++source->cursor();
		if (yych != 't') goto yy30;
		yych = *++source->cursor();
		if (yych != 's') goto yy30;
		++source->cursor();
#line 169 "bcplus/parser/detail/Scanner.1.re2c"
		{ ret = T_OBJECTS;						goto re2c_finish;					}
#line 702 "<stdout>"
yy154:
		yych = *++source->cursor();
		if (yych <= 'm') {
			if (yych == 'c') goto yy162;
			goto yy30;
		} else {
			if (yych <= 'n') goto yy163;
			if (yych == 't') goto yy164;
			goto yy30;
		}
yy155:
		yych = *++source->cursor();
		if (yych == 'q') goto yy157;
		if (yych != 'v') goto yy30;
		yych = *++source->cursor();
		if (yych == 'e') goto yy159;
		goto yy30;
yy157:
		++source->cursor();
#line 223 "bcplus/parser/detail/Scanner.1.re2c"
		{ ret = T_NEQ;							goto re2c_finish;					}
#line 724 "<stdout>"
yy159:
		yych = *++source->cursor();
		if (yych != 'r') goto yy30;
		++source->cursor();
#line 205 "bcplus/parser/detail/Scanner.1.re2c"
		{ ret = T_NEVER;						goto re2c_finish;					}
#line 731 "<stdout>"
yy162:
		yych = *++source->cursor();
		if (yych == 'o') goto yy178;
		goto yy30;
yy163:
		yych = *++source->cursor();
		if (yych == 'e') goto yy166;
		goto yy30;
yy164:
		++source->cursor();
#line 225 "bcplus/parser/detail/Scanner.1.re2c"
		{ ret = T_NOT;							goto re2c_finish;					}
#line 744 "<stdout>"
yy166:
		yyaccept = 1;
		yych = *(source->marker() = ++source->cursor());
		if (yych == 'x') goto yy168;
yy167:
#line 224 "bcplus/parser/detail/Scanner.1.re2c"
		{ ret = T_NONE;							goto re2c_finish;					}
#line 752 "<stdout>"
yy168:
		yych = *++source->cursor();
		if (yych != 'e') goto yy30;
		yych = *++source->cursor();
		if (yych != 'c') goto yy30;
		yych = *++source->cursor();
		if (yych != 'u') goto yy30;
		yych = *++source->cursor();
		if (yych != 't') goto yy30;
		yych = *++source->cursor();
		if (yych != 'a') goto yy30;
		yych = *++source->cursor();
		if (yych != 'b') goto yy30;
		yych = *++source->cursor();
		if (yych != 'l') goto yy30;
		yych = *++source->cursor();
		if (yych != 'e') goto yy30;
		++source->cursor();
#line 207 "bcplus/parser/detail/Scanner.1.re2c"
		{ ret = T_NONEXECUTABLE;				goto re2c_finish;					}
#line 773 "<stdout>"
yy178:
		yych = *++source->cursor();
		if (yych != 'n') goto yy30;
		yych = *++source->cursor();
		if (yych != 'c') goto yy30;
		yych = *++source->cursor();
		if (yych != 'u') goto yy30;
		yych = *++source->cursor();
		if (yych != 'r') goto yy30;
		yych = *++source->cursor();
		if (yych != 'r') goto yy30;
		yych = *++source->cursor();
		if (yych != 'e') goto yy30;
		yych = *++source->cursor();
		if (yych != 'n') goto yy30;
		yych = *++source->cursor();
		if (yych != 'c') goto yy30;
		yych = *++source->cursor();
		if (yych != 'y') goto yy30;
		++source->cursor();
#line 206 "bcplus/parser/detail/Scanner.1.re2c"
		{ ret = T_NOCONCURRENCY;				goto re2c_finish;					}
#line 796 "<stdout>"
yy189:
		yych = *++source->cursor();
		if (yych == 'd') goto yy227;
		goto yy30;
yy190:
		yych = *++source->cursor();
		if (yych <= 'w') {
			if (yych != 'c') goto yy30;
		} else {
			if (yych <= 'x') goto yy193;
			if (yych <= 'y') goto yy192;
			goto yy30;
		}
		yych = *++source->cursor();
		if (yych == 'r') goto yy223;
		goto yy30;
yy192:
		yych = *++source->cursor();
		if (yych == 'c') goto yy30;
		goto yy216;
yy193:
		yych = *++source->cursor();
		if (yych == 'A') goto yy195;
		if (yych != 's') goto yy30;
		yych = *++source->cursor();
		if (yych == 't') goto yy211;
		goto yy30;
yy195:
		yych = *++source->cursor();
		if (yych == 'F') goto yy197;
		if (yych != 'd') goto yy30;
		yych = *++source->cursor();
		if (yych == 'd') goto yy204;
		goto yy30;
yy197:
		yych = *++source->cursor();
		if (yych != 'V') goto yy30;
		yych = *++source->cursor();
		if (yych != 'a') goto yy30;
		yych = *++source->cursor();
		if (yych != 'l') goto yy30;
		yych = *++source->cursor();
		if (yych != 'u') goto yy30;
		yych = *++source->cursor();
		if (yych != 'e') goto yy30;
		++source->cursor();
#line 203 "bcplus/parser/detail/Scanner.1.re2c"
		{ ret = T_MAXAFVALUE;					goto re2c_finish;					}
#line 845 "<stdout>"
yy204:
		yych = *++source->cursor();
		if (yych != 'i') goto yy30;
		yych = *++source->cursor();
		if (yych != 't') goto yy30;
		yych = *++source->cursor();
		if (yych != 'i') goto yy30;
		yych = *++source->cursor();
		if (yych != 'v') goto yy30;
		yych = *++source->cursor();
		if (yych != 'e') goto yy30;
		++source->cursor();
#line 202 "bcplus/parser/detail/Scanner.1.re2c"
		{ ret = T_MAXADDITIVE;					goto re2c_finish;					}
#line 860 "<stdout>"
yy211:
		yych = *++source->cursor();
		if (yych != 'e') goto yy30;
		yych = *++source->cursor();
		if (yych != 'p') goto yy30;
		++source->cursor();
#line 204 "bcplus/parser/detail/Scanner.1.re2c"
		{ ret = T_MAXSTEP;						goto re2c_finish;					}
#line 869 "<stdout>"
yy215:
		++source->cursor();
		if ((source->limit() - source->cursor()) < 5) source->fill(5);
		yych = *source->cursor();
yy216:
		if (yych <= '\f') {
			if (yych == '\t') goto yy215;
			if (yych <= '\n') goto yy30;
			goto yy215;
		} else {
			if (yych <= ' ') {
				if (yych <= 0x1F) goto yy30;
				goto yy215;
			} else {
				if (yych != 'c') goto yy30;
			}
		}
		yych = *++source->cursor();
		if (yych != 'a') goto yy30;
		yych = *++source->cursor();
		if (yych != 'u') goto yy30;
		yych = *++source->cursor();
		if (yych != 's') goto yy30;
		yych = *++source->cursor();
		if (yych != 'e') goto yy30;
		++source->cursor();
#line 201 "bcplus/parser/detail/Scanner.1.re2c"
		{ ret = T_MAY_CAUSE;					goto re2c_finish;					}
#line 898 "<stdout>"
yy223:
		yych = *++source->cursor();
		if (yych != 'o') goto yy30;
		yych = *++source->cursor();
		if (yych != 's') goto yy30;
		++source->cursor();
#line 168 "bcplus/parser/detail/Scanner.1.re2c"
		{ ret = T_MACROS; _in_macro = true;		goto re2c_finish;					}
#line 907 "<stdout>"
yy227:
		++source->cursor();
#line 222 "bcplus/parser/detail/Scanner.1.re2c"
		{ ret = T_MOD;							goto re2c_finish;					}
#line 912 "<stdout>"
yy229:
		yych = *++source->cursor();
		if (yych != 'b') goto yy30;
		yych = *++source->cursor();
		if (yych != 'e') goto yy30;
		yych = *++source->cursor();
		if (yych != 'l') goto yy30;
		++source->cursor();
#line 200 "bcplus/parser/detail/Scanner.1.re2c"
		{ ret = T_LABEL;						goto re2c_finish;					}
#line 923 "<stdout>"
yy234:
		yych = *++source->cursor();
		if (yych == 'c') goto yy252;
		if (yych == 'e') goto yy253;
		goto yy30;
yy235:
		yych = *++source->cursor();
		if (yych == 'p') goto yy243;
		goto yy30;
yy236:
		yyaccept = 2;
		yych = *(source->marker() = ++source->cursor());
		if (yych == 'c') goto yy238;
yy237:
#line 194 "bcplus/parser/detail/Scanner.1.re2c"
		{ ret = T_IF;							goto re2c_finish;					}
#line 940 "<stdout>"
yy238:
		yych = *++source->cursor();
		if (yych != 'o') goto yy30;
		yych = *++source->cursor();
		if (yych != 'n') goto yy30;
		yych = *++source->cursor();
		if (yych != 's') goto yy30;
		++source->cursor();
#line 195 "bcplus/parser/detail/Scanner.1.re2c"
		{ ret = T_IFCONS;						goto re2c_finish;					}
#line 951 "<stdout>"
yy243:
		yych = *++source->cursor();
		if (yych != 'o') goto yy30;
		yych = *++source->cursor();
		if (yych != 's') goto yy30;
		yych = *++source->cursor();
		if (yych != 's') goto yy30;
		yych = *++source->cursor();
		if (yych != 'i') goto yy30;
		yych = *++source->cursor();
		if (yych != 'b') goto yy30;
		yych = *++source->cursor();
		if (yych != 'l') goto yy30;
		yych = *++source->cursor();
		if (yych != 'e') goto yy30;
		++source->cursor();
#line 196 "bcplus/parser/detail/Scanner.1.re2c"
		{ ret = T_IMPOSSIBLE;					goto re2c_finish;					}
#line 970 "<stdout>"
yy252:
		yych = *++source->cursor();
		if (yych == 'l') goto yy268;
		if (yych == 'r') goto yy267;
		goto yy30;
yy253:
		yych = *++source->cursor();
		if (yych != 'r') goto yy30;
		yych = *++source->cursor();
		if (yych != 't') goto yy30;
		yych = *++source->cursor();
		if (yych != 'i') goto yy30;
		yych = *++source->cursor();
		if (yych != 'a') goto yy30;
		yych = *++source->cursor();
		if (yych != 'l') goto yy30;
		yyaccept = 3;
		yych = *(source->marker() = ++source->cursor());
		if (yych == 'F') goto yy260;
yy259:
#line 198 "bcplus/parser/detail/Scanner.1.re2c"
		{ ret = T_INERTIAL;						goto re2c_finish;					}
#line 993 "<stdout>"
yy260:
		yych = *++source->cursor();
		if (yych != 'l') goto yy30;
		yych = *++source->cursor();
		if (yych != 'u') goto yy30;
		yych = *++source->cursor();
		if (yych != 'e') goto yy30;
		yych = *++source->cursor();
		if (yych != 'n') goto yy30;
		yych = *++source->cursor();
		if (yych != 't') goto yy30;
		++source->cursor();
#line 199 "bcplus/parser/detail/Scanner.1.re2c"
		{ ret = T_INERTIALFLUENT;				goto re2c_finish;					}
#line 1008 "<stdout>"
yy267:
		yych = *++source->cursor();
		if (yych == 'e') goto yy273;
		goto yy30;
yy268:
		yych = *++source->cursor();
		if (yych != 'u') goto yy30;
		yych = *++source->cursor();
		if (yych != 'd') goto yy30;
		yych = *++source->cursor();
		if (yych != 'e') goto yy30;
		++source->cursor();
#line 167 "bcplus/parser/detail/Scanner.1.re2c"
		{ ret = T_INCLUDE;						goto re2c_finish;					}
#line 1023 "<stdout>"
yy273:
		yych = *++source->cursor();
		if (yych != 'm') goto yy30;
		yych = *++source->cursor();
		if (yych != 'e') goto yy30;
		yych = *++source->cursor();
		if (yych != 'n') goto yy30;
		yych = *++source->cursor();
		if (yych != 't') goto yy30;
		yych = *++source->cursor();
		if (yych != 's') goto yy30;
		++source->cursor();
#line 197 "bcplus/parser/detail/Scanner.1.re2c"
		{ ret = T_INCREMENTS;					goto re2c_finish;					}
#line 1038 "<stdout>"
yy280:
		yych = *++source->cursor();
		if (yych != 'l') goto yy30;
		yych = *++source->cursor();
		if (yych != 's') goto yy30;
		yych = *++source->cursor();
		if (yych != 'e') goto yy30;
		++source->cursor();
#line 221 "bcplus/parser/detail/Scanner.1.re2c"
		{ ret = T_FALSE;						goto re2c_finish;					}
#line 1049 "<stdout>"
yy285:
		++source->cursor();
#line 220 "bcplus/parser/detail/Scanner.1.re2c"
		{ ret = T_EQ;							goto re2c_finish;					}
#line 1054 "<stdout>"
yy287:
		yych = *++source->cursor();
		if (yych == 'o') goto yy289;
		if (yych != 't') goto yy30;
		yych = *++source->cursor();
		if (yych == 'e') goto yy304;
		goto yy30;
yy289:
		yych = *++source->cursor();
		if (yych != 'g') goto yy30;
		yych = *++source->cursor();
		if (yych != 'e') goto yy30;
		yych = *++source->cursor();
		if (yych != 'n') goto yy30;
		yych = *++source->cursor();
		if (yych != 'o') goto yy30;
		yych = *++source->cursor();
		if (yych != 'u') goto yy30;
		yych = *++source->cursor();
		if (yych != 's') goto yy30;
		yyaccept = 4;
		yych = *(source->marker() = ++source->cursor());
		if (yych == 'A') goto yy297;
yy296:
#line 192 "bcplus/parser/detail/Scanner.1.re2c"
		{ ret = T_EXOGENOUS;					goto re2c_finish;					}
#line 1081 "<stdout>"
yy297:
		yych = *++source->cursor();
		if (yych != 'c') goto yy30;
		yych = *++source->cursor();
		if (yych != 't') goto yy30;
		yych = *++source->cursor();
		if (yych != 'i') goto yy30;
		yych = *++source->cursor();
		if (yych != 'o') goto yy30;
		yych = *++source->cursor();
		if (yych != 'n') goto yy30;
		++source->cursor();
#line 193 "bcplus/parser/detail/Scanner.1.re2c"
		{ ret = T_EXOGENOUSACTION;				goto re2c_finish;					}
#line 1096 "<stdout>"
yy304:
		yych = *++source->cursor();
		if (yych != 'r') goto yy30;
		yych = *++source->cursor();
		if (yych != 'n') goto yy30;
		yych = *++source->cursor();
		if (yych != 'a') goto yy30;
		yych = *++source->cursor();
		if (yych != 'l') goto yy30;
		yych = *++source->cursor();
		if (yych == 'A') goto yy309;
		if (yych == 'F') goto yy310;
		goto yy30;
yy309:
		yych = *++source->cursor();
		if (yych == 'c') goto yy317;
		goto yy30;
yy310:
		yych = *++source->cursor();
		if (yych != 'l') goto yy30;
		yych = *++source->cursor();
		if (yych != 'u') goto yy30;
		yych = *++source->cursor();
		if (yych != 'e') goto yy30;
		yych = *++source->cursor();
		if (yych != 'n') goto yy30;
		yych = *++source->cursor();
		if (yych != 't') goto yy30;
		++source->cursor();
#line 191 "bcplus/parser/detail/Scanner.1.re2c"
		{ ret = T_EXTERNALFLUENT;				goto re2c_finish;					}
#line 1128 "<stdout>"
yy317:
		yych = *++source->cursor();
		if (yych != 't') goto yy30;
		yych = *++source->cursor();
		if (yych != 'i') goto yy30;
		yych = *++source->cursor();
		if (yych != 'o') goto yy30;
		yych = *++source->cursor();
		if (yych != 'n') goto yy30;
		++source->cursor();
#line 190 "bcplus/parser/detail/Scanner.1.re2c"
		{ ret = T_EXTERNALACTION;				goto re2c_finish;					}
#line 1141 "<stdout>"
yy323:
		yych = *++source->cursor();
		if (yych == 'c') goto yy324;
		if (yych == 'f') goto yy325;
		goto yy30;
yy324:
		yych = *++source->cursor();
		if (yych == 'r') goto yy331;
		goto yy30;
yy325:
		yych = *++source->cursor();
		if (yych != 'a') goto yy30;
		yych = *++source->cursor();
		if (yych != 'u') goto yy30;
		yych = *++source->cursor();
		if (yych != 'l') goto yy30;
		yych = *++source->cursor();
		if (yych != 't') goto yy30;
		++source->cursor();
#line 189 "bcplus/parser/detail/Scanner.1.re2c"
		{ ret = T_DEFAULT;						goto re2c_finish;					}
#line 1163 "<stdout>"
yy331:
		yych = *++source->cursor();
		if (yych != 'e') goto yy30;
		yych = *++source->cursor();
		if (yych != 'm') goto yy30;
		yych = *++source->cursor();
		if (yych != 'e') goto yy30;
		yych = *++source->cursor();
		if (yych != 'n') goto yy30;
		yych = *++source->cursor();
		if (yych != 't') goto yy30;
		yych = *++source->cursor();
		if (yych != 's') goto yy30;
		++source->cursor();
#line 188 "bcplus/parser/detail/Scanner.1.re2c"
		{ ret = T_DECREMENTS;					goto re2c_finish;					}
#line 1180 "<stdout>"
yy339:
		yych = *++source->cursor();
		if (yych == 'n') goto yy348;
		goto yy30;
yy340:
		yych = *++source->cursor();
		if (yych != 'u') goto yy30;
		yych = *++source->cursor();
		if (yych != 's') goto yy30;
		yych = *++source->cursor();
		if (yych != 'e') goto yy30;
		yych = *++source->cursor();
		if (yych == 'd') goto yy346;
		if (yych != 's') goto yy30;
		++source->cursor();
#line 185 "bcplus/parser/detail/Scanner.1.re2c"
		{ ret = T_CAUSES;						goto re2c_finish;					}
#line 1198 "<stdout>"
yy346:
		++source->cursor();
#line 184 "bcplus/parser/detail/Scanner.1.re2c"
		{ ret = T_CAUSED;						goto re2c_finish;					}
#line 1203 "<stdout>"
yy348:
		yych = *++source->cursor();
		if (yych != 's') goto yy30;
		yych = *++source->cursor();
		if (yych != 't') goto yy30;
		yych = *++source->cursor();
		if (yych == 'a') goto yy352;
		if (yych != 'r') goto yy30;
		yych = *++source->cursor();
		if (yych == 'a') goto yy357;
		goto yy30;
yy352:
		yych = *++source->cursor();
		if (yych != 'n') goto yy30;
		yych = *++source->cursor();
		if (yych != 't') goto yy30;
		yych = *++source->cursor();
		if (yych != 's') goto yy30;
		++source->cursor();
#line 186 "bcplus/parser/detail/Scanner.1.re2c"
		{ ret = T_CONSTANTS;					goto re2c_finish;					}
#line 1225 "<stdout>"
yy357:
		yych = *++source->cursor();
		if (yych != 'i') goto yy30;
		yych = *++source->cursor();
		if (yych != 'n') goto yy30;
		yych = *++source->cursor();
		if (yych != 't') goto yy30;
		++source->cursor();
#line 187 "bcplus/parser/detail/Scanner.1.re2c"
		{ ret = T_CONSTRAINT;					goto re2c_finish;					}
#line 1236 "<stdout>"
yy362:
		++source->cursor();
#line 183 "bcplus/parser/detail/Scanner.1.re2c"
		{ ret = T_BY;							goto re2c_finish;					}
#line 1241 "<stdout>"
yy364:
		yych = *++source->cursor();
		if (yych == 'A') goto yy422;
		if (yych == 's') goto yy423;
		goto yy30;
yy365:
		yych = *++source->cursor();
		if (yych == 'l') goto yy416;
		if (yych == 'w') goto yy415;
		goto yy30;
yy366:
		yych = *++source->cursor();
		if (yych == 't') goto yy407;
		goto yy30;
yy367:
		yych = *++source->cursor();
		if (yych == 's') goto yy400;
		goto yy30;
yy368:
		yych = *++source->cursor();
		if (yych == 't') goto yy396;
		goto yy30;
yy369:
		yych = *++source->cursor();
		if (yych == 'd') goto yy376;
		goto yy30;
yy370:
		yych = *++source->cursor();
		if (yych != 't') goto yy30;
		yych = *++source->cursor();
		if (yych != 'i') goto yy30;
		yych = *++source->cursor();
		if (yych != 'o') goto yy30;
		yych = *++source->cursor();
		if (yych != 'n') goto yy30;
		++source->cursor();
#line 175 "bcplus/parser/detail/Scanner.1.re2c"
		{ ret = T_ACTION;						goto re2c_finish;					}
#line 1280 "<stdout>"
yy376:
		yych = *++source->cursor();
		if (yych != 'i') goto yy30;
		yych = *++source->cursor();
		if (yych != 't') goto yy30;
		yych = *++source->cursor();
		if (yych != 'i') goto yy30;
		yych = *++source->cursor();
		if (yych != 'v') goto yy30;
		yych = *++source->cursor();
		if (yych != 'e') goto yy30;
		yych = *++source->cursor();
		if (yych == 'A') goto yy382;
		if (yych == 'F') goto yy383;
		goto yy30;
yy382:
		yych = *++source->cursor();
		if (yych == 'c') goto yy390;
		goto yy30;
yy383:
		yych = *++source->cursor();
		if (yych != 'l') goto yy30;
		yych = *++source->cursor();
		if (yych != 'u') goto yy30;
		yych = *++source->cursor();
		if (yych != 'e') goto yy30;
		yych = *++source->cursor();
		if (yych != 'n') goto yy30;
		yych = *++source->cursor();
		if (yych != 't') goto yy30;
		++source->cursor();
#line 177 "bcplus/parser/detail/Scanner.1.re2c"
		{ ret = T_ADDITIVEFLUENT;				goto re2c_finish;					}
#line 1314 "<stdout>"
yy390:
		yych = *++source->cursor();
		if (yych != 't') goto yy30;
		yych = *++source->cursor();
		if (yych != 'i') goto yy30;
		yych = *++source->cursor();
		if (yych != 'o') goto yy30;
		yych = *++source->cursor();
		if (yych != 'n') goto yy30;
		++source->cursor();
#line 176 "bcplus/parser/detail/Scanner.1.re2c"
		{ ret = T_ADDITIVEACTION;				goto re2c_finish;					}
#line 1327 "<stdout>"
yy396:
		yych = *++source->cursor();
		if (yych != 'e') goto yy30;
		yych = *++source->cursor();
		if (yych != 'r') goto yy30;
		++source->cursor();
#line 178 "bcplus/parser/detail/Scanner.1.re2c"
		{ ret = T_AFTER;						goto re2c_finish;					}
#line 1336 "<stdout>"
yy400:
		yych = *++source->cursor();
		if (yych != 'u') goto yy30;
		yych = *++source->cursor();
		if (yych != 'm') goto yy30;
		yych = *++source->cursor();
		if (yych != 'i') goto yy30;
		yych = *++source->cursor();
		if (yych != 'n') goto yy30;
		yych = *++source->cursor();
		if (yych != 'g') goto yy30;
		++source->cursor();
#line 180 "bcplus/parser/detail/Scanner.1.re2c"
		{ ret = T_ASSUMING;						goto re2c_finish;					}
#line 1351 "<stdout>"
yy407:
		yych = *++source->cursor();
		if (yych != 'r') goto yy30;
		yych = *++source->cursor();
		if (yych != 'i') goto yy30;
		yych = *++source->cursor();
		if (yych != 'b') goto yy30;
		yych = *++source->cursor();
		if (yych != 'u') goto yy30;
		yych = *++source->cursor();
		if (yych != 't') goto yy30;
		yych = *++source->cursor();
		if (yych != 'e') goto yy30;
		++source->cursor();
#line 181 "bcplus/parser/detail/Scanner.1.re2c"
		{ ret = T_ATTRIBUTE;					goto re2c_finish;					}
#line 1368 "<stdout>"
yy415:
		yych = *++source->cursor();
		if (yych == 'a') goto yy418;
		goto yy30;
yy416:
		++source->cursor();
#line 182 "bcplus/parser/detail/Scanner.1.re2c"
		{ ret = T_ALL;							goto re2c_finish;					}
#line 1377 "<stdout>"
yy418:
		yych = *++source->cursor();
		if (yych != 'y') goto yy30;
		yych = *++source->cursor();
		if (yych != 's') goto yy30;
		++source->cursor();
#line 179 "bcplus/parser/detail/Scanner.1.re2c"
		{ ret = T_ALWAYS;						goto re2c_finish;					}
#line 1386 "<stdout>"
yy422:
		yych = *++source->cursor();
		if (yych == 'c') goto yy425;
		goto yy30;
yy423:
		++source->cursor();
#line 219 "bcplus/parser/detail/Scanner.1.re2c"
		{ ret = T_ABS;							goto re2c_finish;					}
#line 1395 "<stdout>"
yy425:
		yych = *++source->cursor();
		if (yych != 't') goto yy30;
		yych = *++source->cursor();
		if (yych != 'i') goto yy30;
		yych = *++source->cursor();
		if (yych != 'o') goto yy30;
		yych = *++source->cursor();
		if (yych != 'n') goto yy30;
		++source->cursor();
#line 174 "bcplus/parser/detail/Scanner.1.re2c"
		{ ret = T_ABACTION;						goto re2c_finish;					}
#line 1408 "<stdout>"
	}
}
#line 230 "bcplus/parser/detail/Scanner.1.re2c"

	}
re2c_notkw:
	source->cursor() = source->token();
	return tokenize_notkw(source);

re2c_finish:
	u::ref_ptr<ReferencedString> str = new ReferencedString();
	if (ret != T_EOF) {
		str->assign(source->token(), (size_t)(source->cursor() - source->token()));
	} else {
		str->assign("<EOF>");
	}

	return new Token(ret, str, begin, source->loc());
}

void Scanner::close() {
	_sources.clear();
}



}}}
