/* Generated by re2c 0.13.6 on Wed Apr 23 22:22:08 2014 */
#line 1 "bcplus/parser/detail/Scanner.3.re2c"

#include <sstream>

#include <boost/filesystem.hpp>
#include <boost/filesystem/fstream.hpp>

#include "bcplus/parser/detail/Scanner.h"
#include "bcplus/parser/detail/lemon_parser.h"

#include "bcplus/Location.h"
#include "bcplus/parser/Token.h"

#include "bcplus/parser/detail/ScannerSource.h"
#include "bcplus/parser/detail/ScannerRawSource.h"
#include "bcplus/parser/detail/ScannerTokenSource.h"
#include "bcplus/parser/detail/ScannerFileSource.h"
#include "bcplus/parser/detail/ScannerBufferSource.h"

namespace u = babb::utils; 
namespace fs = boost::filesystem;

namespace bcplus {
namespace parser {
namespace detail {


#define BLK_INIT(s) \
	blk.str(s); \
	use_blk = true; \
	source->token() = source->cursor() + 1;

#define BLK_LINE \
	source->newline(); \
    blk.write(source->token(), (size_t)(source->cursor() - source->token())); \
	source->token() = source->cursor() + 1;		

#define BLK_FINISH(sz) \
	blk.write(source->token(), (size_t)(source->cursor() - source->token() - sz));

Token* Scanner::tokenize_3(ScannerRawSource* source) {
	if (source->eof()) return new Token(T_EOF, new ReferencedString("<EOF>"), source->loc(), source->loc());
	else if (!source->good()) return new Token(T_ERR_IO, new ReferencedString("<IO ERROR>"), source->loc(), source->loc());


	std::stringstream blk;
	int ret;
	Location begin;
	bool use_blk = false;
	size_t preskip = 0;
	size_t postskip = 0;

	int parens = 0;
	bool dbl_quote = false;
	bool sgl_quote = false;

	char const* marker;

re2c_start:
	marker = source->token() = source->cursor();
	begin = source->loc();

	
#line 66 "<stdout>"
{
	char yych;
	unsigned int yyaccept = 0;
	if (_cond < 6) {
		if (_cond < 3) {
			if (_cond < 1) {
				goto yyc_NORMAL;
			} else {
				if (_cond < 2) {
					goto yyc_DBL_STRING;
				} else {
					goto yyc_SGL_STRING;
				}
			}
		} else {
			if (_cond < 4) {
				goto yyc_COMMENT;
			} else {
				if (_cond < 5) {
					goto yyc_BLK_COMMENT;
				} else {
					goto yyc_ASP_GR;
				}
			}
		}
	} else {
		if (_cond < 9) {
			if (_cond < 7) {
				goto yyc_ASP_CP;
			} else {
				if (_cond < 8) {
					goto yyc_LUA_GR;
				} else {
					goto yyc_LUA_CP;
				}
			}
		} else {
			if (_cond < 11) {
				if (_cond < 10) {
					goto yyc_F2LP_GR;
				} else {
					goto yyc_F2LP_CP;
				}
			} else {
				if (_cond < 12) {
					goto yyc_ARG;
				} else {
					goto yyc_MACRO;
				}
			}
		}
	}
/* *********************************** */
yyc_ARG:
	if ((source->limit() - source->cursor()) < 2) source->fill(2);
	yych = *source->cursor();
	if (yych <= '&') {
		if (yych <= '\n') {
			if (yych <= 0x00) goto yyy4;
			if (yych <= '\t') goto yyy6;
		} else {
			if (yych == '"') goto yyy8;
			goto yyy6;
		}
	} else {
		if (yych <= ')') {
			if (yych <= '\'') goto yyy10;
			if (yych <= '(') goto yyy12;
			goto yyy14;
		} else {
			if (yych == ',') goto yyy16;
			goto yyy6;
		}
	}
yyy4:
	marker = source->cursor() + 1;
	++source->cursor();
	if ((yych = *source->cursor()) == ')') goto yyy18;
	if (yych == ',') goto yyy18;
#line 468 "bcplus/parser/detail/Scanner.3.re2c"
	{
													// Figure out why we're still here...
													if (parens > 0 ) {
														_cond = yycNORMAL;
														ret = T_ERR_PAREN_MISMATCH;
													} else if (sgl_quote || dbl_quote) {
														_cond = yycNORMAL;
														ret = T_ERR_UNTERMINATED_STRING;
													}else {
														_cond = yycNORMAL;
														ret = T_ERR_SYNTAX;
													}
													goto re2c_finish;
												}
#line 161 "<stdout>"
yyy6:
	marker = source->cursor() + 1;
	++source->cursor();
	if ((yych = *source->cursor()) == ')') goto yyy18;
	if (yych == ',') goto yyy18;
#line 482 "bcplus/parser/detail/Scanner.3.re2c"
	{												goto yyc_ARG;						}
#line 169 "<stdout>"
yyy8:
	marker = source->cursor() + 1;
	++source->cursor();
	if ((yych = *source->cursor()) == ')') goto yyy26;
	if (yych == ',') goto yyy26;
#line 454 "bcplus/parser/detail/Scanner.3.re2c"
	{ if (!sgl_quote) dbl_quote = !dbl_quote;		goto yyc_ARG;						}
#line 177 "<stdout>"
yyy10:
	marker = source->cursor() + 1;
	++source->cursor();
	if ((yych = *source->cursor()) == ')') goto yyy24;
	if (yych == ',') goto yyy24;
#line 455 "bcplus/parser/detail/Scanner.3.re2c"
	{ if (!dbl_quote) sgl_quote = !sgl_quote;		goto yyc_ARG;						}
#line 185 "<stdout>"
yyy12:
	marker = source->cursor() + 1;
	++source->cursor();
	if ((yych = *source->cursor()) == ')') goto yyy22;
	if (yych == ',') goto yyy22;
#line 420 "bcplus/parser/detail/Scanner.3.re2c"
	{ 
												  if (sgl_quote || dbl_quote) goto yyc_ARG;
												  if (!parens++) {
												  	ret = T_PAREN_L;						
													goto re2c_finish;
												  } else goto yyc_ARG;
												}
#line 199 "<stdout>"
yyy14:
	marker = source->cursor() + 1;
	++source->cursor();
	if ((yych = *source->cursor()) == ')') goto yyy20;
	if (yych == ',') goto yyy20;
#line 427 "bcplus/parser/detail/Scanner.3.re2c"
	{
												  if (sgl_quote || dbl_quote) goto yyc_ARG;
												  if (--parens <= 0) {
												    ret = T_PAREN_R;
													_cond = yycNORMAL;
													goto re2c_finish;
												  } else goto yyc_ARG;
												}
#line 214 "<stdout>"
yyy16:
	marker = source->cursor() + 1;
	++source->cursor();
	if ((yych = *source->cursor()) == ')') goto yyy18;
	if (yych == ',') goto yyy18;
#line 456 "bcplus/parser/detail/Scanner.3.re2c"
	{ 
												  if (!dbl_quote && !sgl_quote && !parens) {
													ret = T_COMMA;
													goto re2c_finish;
												  } else goto yyc_ARG;
												}
#line 227 "<stdout>"
yyy18:
	++source->cursor();
	source->cursor() = marker;
#line 462 "bcplus/parser/detail/Scanner.3.re2c"
	{ 
												  if (!parens && !sgl_quote && !dbl_quote) {
													ret = T_ARG;
												    goto re2c_finish;
												  } else goto yyc_ARG;
												}
#line 238 "<stdout>"
yyy20:
	++source->cursor();
	source->cursor() = marker;
#line 412 "bcplus/parser/detail/Scanner.3.re2c"
	{
												  if (sgl_quote || dbl_quote) goto yyc_ARG;
												  if (--parens <= 0) {
												    ret = T_PAREN_R;
													_cond = yycNORMAL;
													goto re2c_finish;
												  }
												}
#line 251 "<stdout>"
yyy22:
	++source->cursor();
	source->cursor() = marker;
#line 405 "bcplus/parser/detail/Scanner.3.re2c"
	{ 
												  if (sgl_quote || dbl_quote) goto yyc_ARG;
												  if (!parens++) {
												  	ret = T_PAREN_L;						
													goto re2c_finish;
												  } else goto yyc_ARG;
												}
#line 263 "<stdout>"
yyy24:
	++source->cursor();
	source->cursor() = marker;
#line 445 "bcplus/parser/detail/Scanner.3.re2c"
	{
												  if (!dbl_quote) { 
													sgl_quote = !sgl_quote;
													if (!sgl_quote) {
														ret = T_ARG;
												    	goto re2c_finish;
													} else goto yyc_ARG;
												  } else goto yyc_ARG;
												}
#line 277 "<stdout>"
yyy26:
	++source->cursor();
	source->cursor() = marker;
#line 436 "bcplus/parser/detail/Scanner.3.re2c"
	{
												  if (!sgl_quote) { 
													dbl_quote = !dbl_quote;
													if (!dbl_quote) {
														ret = T_ARG;
												    	goto re2c_finish;
													} else goto yyc_ARG;
												  } else goto yyc_ARG;
												}
#line 291 "<stdout>"
/* *********************************** */
yyc_ASP_CP:
	{
		static const unsigned char yybm[] = {
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0, 128,   0, 128, 128,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			128,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
		};
		if ((source->limit() - source->cursor()) < 2) source->fill(2);
		yych = *source->cursor();
		if (yych <= '\n') {
			if (yych <= 0x00) goto yyy30;
			if (yych <= '\t') goto yyy32;
			goto yyy35;
		} else {
			if (yych == ':') goto yyy34;
			goto yyy32;
		}
yyy30:
		++source->cursor();
#line 314 "bcplus/parser/detail/Scanner.3.re2c"
		{ 
												  BLK_FINISH(1);
												  ret = T_ERR_UNTERMINATED_ASP;			
												  _cond = yycNORMAL;
												  source->cursor()--;
												  goto re2c_finish;					
												}
#line 349 "<stdout>"
yyy32:
		++source->cursor();
yyy33:
#line 321 "bcplus/parser/detail/Scanner.3.re2c"
		{												goto yyc_ASP_CP;					}
#line 355 "<stdout>"
yyy34:
		yyaccept = 0;
		yych = *(source->marker() = ++source->cursor());
		if (yych == '-') goto yyy37;
		goto yyy33;
yyy35:
		++source->cursor();
#line 301 "bcplus/parser/detail/Scanner.3.re2c"
		{ BLK_LINE;										goto yyc_ASP_CP;					}
#line 365 "<stdout>"
yyy37:
		++source->cursor();
		if ((source->limit() - source->cursor()) < 7) source->fill(7);
		yych = *source->cursor();
		if (yybm[0+yych] & 128) {
			goto yyy37;
		}
		if (yych == 'e') goto yyy40;
yyy39:
		source->cursor() = source->marker();
		goto yyy33;
yyy40:
		yych = *++source->cursor();
		if (yych != 'n') goto yyy39;
		yych = *++source->cursor();
		if (yych != 'd') goto yyy39;
		yych = *++source->cursor();
		if (yych == '_') goto yyy45;
		if (yych == 'a') goto yyy39;
		goto yyy44;
yyy43:
		++source->cursor();
		if ((source->limit() - source->cursor()) < 3) source->fill(3);
		yych = *source->cursor();
yyy44:
		if (yych <= '\f') {
			if (yych == '\t') goto yyy43;
			if (yych <= '\n') goto yyy39;
			goto yyy43;
		} else {
			if (yych <= ' ') {
				if (yych <= 0x1F) goto yyy39;
				goto yyy43;
			} else {
				if (yych == 'a') goto yyy52;
				goto yyy39;
			}
		}
yyy45:
		yych = *++source->cursor();
		if (yych != 'a') goto yyy39;
		yych = *++source->cursor();
		if (yych != 's') goto yyy39;
		yych = *++source->cursor();
		if (yych != 'p') goto yyy39;
yyy48:
		++source->cursor();
		if (source->limit() <= source->cursor()) source->fill(1);
		yych = *source->cursor();
		if (yych <= '\f') {
			if (yych == '\t') goto yyy48;
			if (yych <= '\n') goto yyy39;
			goto yyy48;
		} else {
			if (yych <= ' ') {
				if (yych <= 0x1F) goto yyy39;
				goto yyy48;
			} else {
				if (yych != '.') goto yyy39;
			}
		}
		++source->cursor();
#line 303 "bcplus/parser/detail/Scanner.3.re2c"
		{ 
												  _cond = yycNORMAL; 
												  ret = T_ASP_CP; 
												  goto re2c_finish;					
												}
#line 434 "<stdout>"
yyy52:
		yych = *++source->cursor();
		if (yych != 's') goto yyy39;
		yych = *++source->cursor();
		if (yych != 'p') goto yyy39;
yyy54:
		++source->cursor();
		if (source->limit() <= source->cursor()) source->fill(1);
		yych = *source->cursor();
		if (yych <= '\f') {
			if (yych == '\t') goto yyy54;
			if (yych <= '\n') goto yyy39;
			goto yyy54;
		} else {
			if (yych <= ' ') {
				if (yych <= 0x1F) goto yyy39;
				goto yyy54;
			} else {
				if (yych != '.') goto yyy39;
			}
		}
		++source->cursor();
#line 309 "bcplus/parser/detail/Scanner.3.re2c"
		{ 
												  _cond = yycNORMAL; 
												  ret = T_ASP_CP; 
												  goto re2c_finish;					
												}
#line 463 "<stdout>"
	}
/* *********************************** */
yyc_ASP_GR:
	{
		static const unsigned char yybm[] = {
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0, 128,   0, 128, 128,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			128,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
		};
		if ((source->limit() - source->cursor()) < 8) source->fill(8);
		yych = *source->cursor();
		if (yych <= '\n') {
			if (yych <= 0x00) goto yyy60;
			if (yych <= '\t') goto yyy62;
			goto yyy65;
		} else {
			if (yych == '#') goto yyy64;
			goto yyy62;
		}
yyy60:
		++source->cursor();
#line 292 "bcplus/parser/detail/Scanner.3.re2c"
		{ 
												  BLK_FINISH(1);
												  ret = T_ERR_UNTERMINATED_ASP;			
												  _cond = yycNORMAL;
												  source->cursor()--;
												  goto re2c_finish;					
												}
#line 522 "<stdout>"
yyy62:
		++source->cursor();
yyy63:
#line 299 "bcplus/parser/detail/Scanner.3.re2c"
		{												goto yyc_ASP_GR;					}
#line 528 "<stdout>"
yyy64:
		yyaccept = 0;
		yych = *(source->marker() = ++source->cursor());
		if (yych == 'e') goto yyy67;
		goto yyy63;
yyy65:
		++source->cursor();
#line 283 "bcplus/parser/detail/Scanner.3.re2c"
		{ 
									 			  BLK_LINE;
												  goto yyc_ASP_GR;				
												}
#line 541 "<stdout>"
yyy67:
		yych = *++source->cursor();
		if (yych == 'n') goto yyy69;
yyy68:
		source->cursor() = source->marker();
		goto yyy63;
yyy69:
		yych = *++source->cursor();
		if (yych != 'd') goto yyy68;
		yych = *++source->cursor();
		if (yych != '_') goto yyy68;
		yych = *++source->cursor();
		if (yych != 'a') goto yyy68;
		yych = *++source->cursor();
		if (yych != 's') goto yyy68;
		yych = *++source->cursor();
		if (yych != 'p') goto yyy68;
yyy74:
		++source->cursor();
		if (source->limit() <= source->cursor()) source->fill(1);
		yych = *source->cursor();
		if (yybm[0+yych] & 128) {
			goto yyy74;
		}
		if (yych != '.') goto yyy68;
		++source->cursor();
#line 287 "bcplus/parser/detail/Scanner.3.re2c"
		{ 
										 		  _cond = yycNORMAL; 
										 		  ret = T_ASP_GR; 
										 		  goto re2c_finish;					
												}
#line 574 "<stdout>"
	}
/* *********************************** */
yyc_BLK_COMMENT:
	if ((source->limit() - source->cursor()) < 2) source->fill(2);
	yych = *source->cursor();
	if (yych <= '\n') {
		if (yych <= 0x00) goto yyy80;
		if (yych <= '\t') goto yyy82;
		goto yyy85;
	} else {
		if (yych == '*') goto yyy84;
		goto yyy82;
	}
yyy80:
	++source->cursor();
#line 274 "bcplus/parser/detail/Scanner.3.re2c"
	{ 
												  BLK_FINISH(1);
												  ret = T_ERR_UNTERMINATED_BLK_COMMENT;			
												  _cond = yycNORMAL;
												  source->cursor()--;
												  goto re2c_finish;					
												}
#line 598 "<stdout>"
yyy82:
	++source->cursor();
yyy83:
#line 281 "bcplus/parser/detail/Scanner.3.re2c"
	{												goto yyc_BLK_COMMENT;				}
#line 604 "<stdout>"
yyy84:
	yych = *++source->cursor();
	if (yych == '/') goto yyy87;
	goto yyy83;
yyy85:
	++source->cursor();
#line 263 "bcplus/parser/detail/Scanner.3.re2c"
	{ 
												  BLK_LINE;
												  blk << "% "; 
												  goto yyc_BLK_COMMENT;				
												}
#line 617 "<stdout>"
yyy87:
	++source->cursor();
#line 268 "bcplus/parser/detail/Scanner.3.re2c"
	{ 
												  BLK_FINISH(2);
												  _cond = yycNORMAL; 
												  ret = T_COMMENT; 
												  goto re2c_finish;					
												}
#line 627 "<stdout>"
/* *********************************** */
yyc_COMMENT:
	{
		static const unsigned char yybm[] = {
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128,   0, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
		};
		if ((source->limit() - source->cursor()) < 2) source->fill(2);
		yych = *source->cursor();
		if (yych <= 0x00) goto yyy91;
		if (yych == '\n') goto yyy94;
		goto yyy93;
yyy91:
		++source->cursor();
		yych = *source->cursor();
		goto yyy97;
yyy92:
#line 255 "bcplus/parser/detail/Scanner.3.re2c"
		{ 												goto yyc_COMMENT;					}
#line 677 "<stdout>"
yyy93:
		yych = *++source->cursor();
		goto yyy97;
yyy94:
		++source->cursor();
#line 249 "bcplus/parser/detail/Scanner.3.re2c"
		{ 
												  source->cursor()--; 
												  _cond = yycNORMAL; 
												  ret = T_COMMENT;			
												  goto re2c_finish;
												}
#line 690 "<stdout>"
yyy96:
		++source->cursor();
		if (source->limit() <= source->cursor()) source->fill(1);
		yych = *source->cursor();
yyy97:
		if (yybm[0+yych] & 128) {
			goto yyy96;
		}
		goto yyy92;
	}
/* *********************************** */
yyc_DBL_STRING:
	if ((source->limit() - source->cursor()) < 2) source->fill(2);
	yych = *source->cursor();
	if (yych <= '!') {
		if (yych <= 0x00) goto yyy100;
		if (yych == '\n') goto yyy106;
		goto yyy102;
	} else {
		if (yych <= '"') goto yyy103;
		if (yych == '\\') goto yyy105;
		goto yyy102;
	}
yyy100:
	++source->cursor();
yyy101:
#line 225 "bcplus/parser/detail/Scanner.3.re2c"
	{												goto yyc_DBL_STRING;				}
#line 719 "<stdout>"
yyy102:
	yych = *++source->cursor();
	goto yyy101;
yyy103:
	++source->cursor();
#line 219 "bcplus/parser/detail/Scanner.3.re2c"
	{ 
												  _cond = yycNORMAL; 
												  ret = T_STRING_LITERAL;	
												  postskip = 1;
												  goto re2c_finish;					
												}
#line 732 "<stdout>"
yyy105:
	yych = *++source->cursor();
	if (yych == '"') goto yyy108;
	goto yyy101;
yyy106:
	++source->cursor();
#line 217 "bcplus/parser/detail/Scanner.3.re2c"
	{ source->newline();				 			goto yyc_DBL_STRING; 				}
#line 741 "<stdout>"
yyy108:
	++source->cursor();
#line 218 "bcplus/parser/detail/Scanner.3.re2c"
	{ 												goto yyc_DBL_STRING; 				}
#line 746 "<stdout>"
/* *********************************** */
yyc_F2LP_CP:
	{
		static const unsigned char yybm[] = {
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0, 128,   0, 128, 128,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			128,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
		};
		if ((source->limit() - source->cursor()) < 2) source->fill(2);
		yych = *source->cursor();
		if (yych <= '\n') {
			if (yych <= 0x00) goto yyy112;
			if (yych <= '\t') goto yyy114;
			goto yyy117;
		} else {
			if (yych == ':') goto yyy116;
			goto yyy114;
		}
yyy112:
		++source->cursor();
#line 396 "bcplus/parser/detail/Scanner.3.re2c"
		{ 
												  BLK_FINISH(1);
												  ret = T_ERR_UNTERMINATED_F2LP;			
												  _cond = yycNORMAL;
												  source->cursor()--;
												  goto re2c_finish;					
												}
#line 804 "<stdout>"
yyy114:
		++source->cursor();
yyy115:
#line 403 "bcplus/parser/detail/Scanner.3.re2c"
		{												goto yyc_F2LP_CP;					}
#line 810 "<stdout>"
yyy116:
		yyaccept = 0;
		yych = *(source->marker() = ++source->cursor());
		if (yych == '-') goto yyy119;
		goto yyy115;
yyy117:
		++source->cursor();
#line 383 "bcplus/parser/detail/Scanner.3.re2c"
		{ BLK_LINE;										goto yyc_F2LP_CP;					}
#line 820 "<stdout>"
yyy119:
		++source->cursor();
		if ((source->limit() - source->cursor()) < 8) source->fill(8);
		yych = *source->cursor();
		if (yybm[0+yych] & 128) {
			goto yyy119;
		}
		if (yych == 'e') goto yyy122;
yyy121:
		source->cursor() = source->marker();
		goto yyy115;
yyy122:
		yych = *++source->cursor();
		if (yych != 'n') goto yyy121;
		yych = *++source->cursor();
		if (yych != 'd') goto yyy121;
		yych = *++source->cursor();
		if (yych == '_') goto yyy127;
		if (yych == 'f') goto yyy121;
		goto yyy126;
yyy125:
		++source->cursor();
		if ((source->limit() - source->cursor()) < 4) source->fill(4);
		yych = *source->cursor();
yyy126:
		if (yych <= '\f') {
			if (yych == '\t') goto yyy125;
			if (yych <= '\n') goto yyy121;
			goto yyy125;
		} else {
			if (yych <= ' ') {
				if (yych <= 0x1F) goto yyy121;
				goto yyy125;
			} else {
				if (yych == 'f') goto yyy135;
				goto yyy121;
			}
		}
yyy127:
		yych = *++source->cursor();
		if (yych != 'f') goto yyy121;
		yych = *++source->cursor();
		if (yych != '2') goto yyy121;
		yych = *++source->cursor();
		if (yych != 'l') goto yyy121;
		yych = *++source->cursor();
		if (yych != 'p') goto yyy121;
yyy131:
		++source->cursor();
		if (source->limit() <= source->cursor()) source->fill(1);
		yych = *source->cursor();
		if (yych <= '\f') {
			if (yych == '\t') goto yyy131;
			if (yych <= '\n') goto yyy121;
			goto yyy131;
		} else {
			if (yych <= ' ') {
				if (yych <= 0x1F) goto yyy121;
				goto yyy131;
			} else {
				if (yych != '.') goto yyy121;
			}
		}
		++source->cursor();
#line 385 "bcplus/parser/detail/Scanner.3.re2c"
		{ 
												  _cond = yycNORMAL; 
												  ret = T_F2LP_CP; 
												  goto re2c_finish;					
												}
#line 891 "<stdout>"
yyy135:
		yych = *++source->cursor();
		if (yych != '2') goto yyy121;
		yych = *++source->cursor();
		if (yych != 'l') goto yyy121;
		yych = *++source->cursor();
		if (yych != 'p') goto yyy121;
yyy138:
		++source->cursor();
		if (source->limit() <= source->cursor()) source->fill(1);
		yych = *source->cursor();
		if (yych <= '\f') {
			if (yych == '\t') goto yyy138;
			if (yych <= '\n') goto yyy121;
			goto yyy138;
		} else {
			if (yych <= ' ') {
				if (yych <= 0x1F) goto yyy121;
				goto yyy138;
			} else {
				if (yych != '.') goto yyy121;
			}
		}
		++source->cursor();
#line 391 "bcplus/parser/detail/Scanner.3.re2c"
		{ 
												  _cond = yycNORMAL; 
												  ret = T_F2LP_CP; 
												  goto re2c_finish;					
												}
#line 922 "<stdout>"
	}
/* *********************************** */
yyc_F2LP_GR:
	{
		static const unsigned char yybm[] = {
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0, 128,   0, 128, 128,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			128,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
		};
		if ((source->limit() - source->cursor()) < 9) source->fill(9);
		yych = *source->cursor();
		if (yych <= '\n') {
			if (yych <= 0x00) goto yyy144;
			if (yych <= '\t') goto yyy146;
			goto yyy149;
		} else {
			if (yych == '#') goto yyy148;
			goto yyy146;
		}
yyy144:
		++source->cursor();
#line 374 "bcplus/parser/detail/Scanner.3.re2c"
		{ 
												  BLK_FINISH(1);
												  ret = T_ERR_UNTERMINATED_F2LP;			
												  _cond = yycNORMAL;
												  source->cursor()--;
												  goto re2c_finish;					
												}
#line 981 "<stdout>"
yyy146:
		++source->cursor();
yyy147:
#line 381 "bcplus/parser/detail/Scanner.3.re2c"
		{												goto yyc_F2LP_GR;					}
#line 987 "<stdout>"
yyy148:
		yyaccept = 0;
		yych = *(source->marker() = ++source->cursor());
		if (yych == 'e') goto yyy151;
		goto yyy147;
yyy149:
		++source->cursor();
#line 365 "bcplus/parser/detail/Scanner.3.re2c"
		{ 
												  BLK_LINE;
												  goto yyc_F2LP_GR;				
												}
#line 1000 "<stdout>"
yyy151:
		yych = *++source->cursor();
		if (yych == 'n') goto yyy153;
yyy152:
		source->cursor() = source->marker();
		goto yyy147;
yyy153:
		yych = *++source->cursor();
		if (yych != 'd') goto yyy152;
		yych = *++source->cursor();
		if (yych != '_') goto yyy152;
		yych = *++source->cursor();
		if (yych != 'f') goto yyy152;
		yych = *++source->cursor();
		if (yych != '2') goto yyy152;
		yych = *++source->cursor();
		if (yych != 'l') goto yyy152;
		yych = *++source->cursor();
		if (yych != 'p') goto yyy152;
yyy159:
		++source->cursor();
		if (source->limit() <= source->cursor()) source->fill(1);
		yych = *source->cursor();
		if (yybm[0+yych] & 128) {
			goto yyy159;
		}
		if (yych != '.') goto yyy152;
		++source->cursor();
#line 369 "bcplus/parser/detail/Scanner.3.re2c"
		{ 
												  _cond = yycNORMAL; 
												  ret = T_F2LP_GR; 
												  goto re2c_finish;					
												}
#line 1035 "<stdout>"
	}
/* *********************************** */
yyc_LUA_CP:
	{
		static const unsigned char yybm[] = {
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0, 128,   0, 128, 128,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			128,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
		};
		if ((source->limit() - source->cursor()) < 2) source->fill(2);
		yych = *source->cursor();
		if (yych <= '\n') {
			if (yych <= 0x00) goto yyy165;
			if (yych <= '\t') goto yyy167;
			goto yyy170;
		} else {
			if (yych == ':') goto yyy169;
			goto yyy167;
		}
yyy165:
		++source->cursor();
#line 355 "bcplus/parser/detail/Scanner.3.re2c"
		{ 
												  BLK_FINISH(1);
												  ret = T_ERR_UNTERMINATED_LUA;			
												  _cond = yycNORMAL;
												  source->cursor()--;
												  goto re2c_finish;					
												}
#line 1094 "<stdout>"
yyy167:
		++source->cursor();
yyy168:
#line 362 "bcplus/parser/detail/Scanner.3.re2c"
		{												goto yyc_LUA_CP;					}
#line 1100 "<stdout>"
yyy169:
		yyaccept = 0;
		yych = *(source->marker() = ++source->cursor());
		if (yych == '-') goto yyy172;
		goto yyy168;
yyy170:
		++source->cursor();
#line 342 "bcplus/parser/detail/Scanner.3.re2c"
		{ BLK_LINE;										goto yyc_LUA_CP;					}
#line 1110 "<stdout>"
yyy172:
		++source->cursor();
		if ((source->limit() - source->cursor()) < 7) source->fill(7);
		yych = *source->cursor();
		if (yybm[0+yych] & 128) {
			goto yyy172;
		}
		if (yych == 'e') goto yyy175;
yyy174:
		source->cursor() = source->marker();
		goto yyy168;
yyy175:
		yych = *++source->cursor();
		if (yych != 'n') goto yyy174;
		yych = *++source->cursor();
		if (yych != 'd') goto yyy174;
		yych = *++source->cursor();
		if (yych == '_') goto yyy180;
		if (yych == 'l') goto yyy174;
		goto yyy179;
yyy178:
		++source->cursor();
		if ((source->limit() - source->cursor()) < 3) source->fill(3);
		yych = *source->cursor();
yyy179:
		if (yych <= '\f') {
			if (yych == '\t') goto yyy178;
			if (yych <= '\n') goto yyy174;
			goto yyy178;
		} else {
			if (yych <= ' ') {
				if (yych <= 0x1F) goto yyy174;
				goto yyy178;
			} else {
				if (yych == 'l') goto yyy187;
				goto yyy174;
			}
		}
yyy180:
		yych = *++source->cursor();
		if (yych != 'l') goto yyy174;
		yych = *++source->cursor();
		if (yych != 'u') goto yyy174;
		yych = *++source->cursor();
		if (yych != 'a') goto yyy174;
yyy183:
		++source->cursor();
		if (source->limit() <= source->cursor()) source->fill(1);
		yych = *source->cursor();
		if (yych <= '\f') {
			if (yych == '\t') goto yyy183;
			if (yych <= '\n') goto yyy174;
			goto yyy183;
		} else {
			if (yych <= ' ') {
				if (yych <= 0x1F) goto yyy174;
				goto yyy183;
			} else {
				if (yych != '.') goto yyy174;
			}
		}
		++source->cursor();
#line 344 "bcplus/parser/detail/Scanner.3.re2c"
		{ 
												  _cond = yycNORMAL; 
												  ret = T_LUA_CP; 
												  goto re2c_finish;					
												}
#line 1179 "<stdout>"
yyy187:
		yych = *++source->cursor();
		if (yych != 'u') goto yyy174;
		yych = *++source->cursor();
		if (yych != 'a') goto yyy174;
yyy189:
		++source->cursor();
		if (source->limit() <= source->cursor()) source->fill(1);
		yych = *source->cursor();
		if (yych <= '\f') {
			if (yych == '\t') goto yyy189;
			if (yych <= '\n') goto yyy174;
			goto yyy189;
		} else {
			if (yych <= ' ') {
				if (yych <= 0x1F) goto yyy174;
				goto yyy189;
			} else {
				if (yych != '.') goto yyy174;
			}
		}
		++source->cursor();
#line 350 "bcplus/parser/detail/Scanner.3.re2c"
		{ 
												  _cond = yycNORMAL; 
												  ret = T_LUA_CP; 
												  goto re2c_finish;					
												}
#line 1208 "<stdout>"
	}
/* *********************************** */
yyc_LUA_GR:
	{
		static const unsigned char yybm[] = {
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0, 128,   0, 128, 128,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			128,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
		};
		if ((source->limit() - source->cursor()) < 8) source->fill(8);
		yych = *source->cursor();
		if (yych <= '\n') {
			if (yych <= 0x00) goto yyy195;
			if (yych <= '\t') goto yyy197;
			goto yyy200;
		} else {
			if (yych == '#') goto yyy199;
			goto yyy197;
		}
yyy195:
		++source->cursor();
#line 333 "bcplus/parser/detail/Scanner.3.re2c"
		{ 
												  BLK_FINISH(1);
												  ret = T_ERR_UNTERMINATED_LUA;			
												  _cond = yycNORMAL;
												  source->cursor()--;
												  goto re2c_finish;					
												}
#line 1267 "<stdout>"
yyy197:
		++source->cursor();
yyy198:
#line 340 "bcplus/parser/detail/Scanner.3.re2c"
		{												goto yyc_LUA_GR;					}
#line 1273 "<stdout>"
yyy199:
		yyaccept = 0;
		yych = *(source->marker() = ++source->cursor());
		if (yych == 'e') goto yyy202;
		goto yyy198;
yyy200:
		++source->cursor();
#line 324 "bcplus/parser/detail/Scanner.3.re2c"
		{ 
												  BLK_LINE;
												  goto yyc_LUA_GR;				
												}
#line 1286 "<stdout>"
yyy202:
		yych = *++source->cursor();
		if (yych == 'n') goto yyy204;
yyy203:
		source->cursor() = source->marker();
		goto yyy198;
yyy204:
		yych = *++source->cursor();
		if (yych != 'd') goto yyy203;
		yych = *++source->cursor();
		if (yych != '_') goto yyy203;
		yych = *++source->cursor();
		if (yych != 'l') goto yyy203;
		yych = *++source->cursor();
		if (yych != 'u') goto yyy203;
		yych = *++source->cursor();
		if (yych != 'a') goto yyy203;
yyy209:
		++source->cursor();
		if (source->limit() <= source->cursor()) source->fill(1);
		yych = *source->cursor();
		if (yybm[0+yych] & 128) {
			goto yyy209;
		}
		if (yych != '.') goto yyy203;
		++source->cursor();
#line 328 "bcplus/parser/detail/Scanner.3.re2c"
		{ 
												  _cond = yycNORMAL; 
												  ret = T_LUA_GR; 
												  goto re2c_finish;					
												}
#line 1319 "<stdout>"
	}
/* *********************************** */
yyc_MACRO:
	if ((source->limit() - source->cursor()) < 2) source->fill(2);
	yych = *source->cursor();
	if (yych <= '!') {
		if (yych <= 0x00) goto yyy216;
		if (yych != '\n') goto yyy218;
	} else {
		if (yych <= '"') goto yyy220;
		if (yych == '\'') goto yyy222;
		goto yyy218;
	}
yyy216:
	marker = source->cursor() + 1;
	++source->cursor();
	if ((yych = *source->cursor()) == '.') goto yyy228;
	if (yych == ';') goto yyy228;
#line 513 "bcplus/parser/detail/Scanner.3.re2c"
	{
													if (sgl_quote || dbl_quote) {
														_cond = yycNORMAL;
														ret = T_ERR_UNTERMINATED_STRING;
													} else {
														_cond = yycNORMAL;
														ret = T_ERR_SYNTAX;
													} goto re2c_finish;
												}
#line 1348 "<stdout>"
yyy218:
	marker = source->cursor() + 1;
	++source->cursor();
	if ((yych = *source->cursor()) == '.') goto yyy228;
	if (yych == ';') goto yyy228;
#line 522 "bcplus/parser/detail/Scanner.3.re2c"
	{ 												goto yyc_MACRO;						}
#line 1356 "<stdout>"
yyy220:
	marker = source->cursor() + 1;
	++source->cursor();
	if ((yych = *source->cursor()) == '.') goto yyy226;
	if (yych == ';') goto yyy226;
#line 504 "bcplus/parser/detail/Scanner.3.re2c"
	{ if (!sgl_quote) { dbl_quote = !dbl_quote; }	goto yyc_MACRO;						}
#line 1364 "<stdout>"
yyy222:
	marker = source->cursor() + 1;
	++source->cursor();
	if ((yych = *source->cursor()) == '.') goto yyy224;
	if (yych == ';') goto yyy224;
#line 505 "bcplus/parser/detail/Scanner.3.re2c"
	{ if (!dbl_quote) { sgl_quote = !sgl_quote; }	goto yyc_MACRO;						}
#line 1372 "<stdout>"
yyy224:
	++source->cursor();
	source->cursor() = marker;
#line 494 "bcplus/parser/detail/Scanner.3.re2c"
	{
												  if (!dbl_quote) { 
													sgl_quote = !sgl_quote;
													if (!sgl_quote) {
														_cond = yycNORMAL;
														ret = T_MACRO_STRING;
												    	goto re2c_finish;
													} else goto yyc_MACRO;
												  } else goto yyc_MACRO;
												}
#line 1387 "<stdout>"
yyy226:
	++source->cursor();
	source->cursor() = marker;
#line 484 "bcplus/parser/detail/Scanner.3.re2c"
	{
												  if (!sgl_quote) { 
													dbl_quote = !dbl_quote;
													if (!dbl_quote) {
														_cond = yycNORMAL;
														ret = T_MACRO_STRING;
												    	goto re2c_finish;
													} else goto yyc_MACRO;
												  } else goto yyc_MACRO;
												}
#line 1402 "<stdout>"
yyy228:
	++source->cursor();
	source->cursor() = marker;
#line 506 "bcplus/parser/detail/Scanner.3.re2c"
	{
												  if (!sgl_quote && !dbl_quote) {
													_cond = yycNORMAL;
													ret = T_MACRO_STRING;
												    goto re2c_finish;
										 	 	  } else goto yyc_MACRO;
												}
#line 1414 "<stdout>"
/* *********************************** */
yyc_NORMAL:
	{
		static const unsigned char yybm[] = {
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,  64,   0,  64,  64,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			 64,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			160, 160, 160, 160, 160, 160, 160, 160, 
			160, 160,   0,   0,   0,   0,   0,   0, 
			  0,  32,  32,  32,  32,  32,  32,  32, 
			 32,  32,  32,  32,  32,  32,  32,  32, 
			 32,  32,  32,  32,  32,  32,  32,  32, 
			 32,  32,  32,   0,   0,   0,   0,  32, 
			  0,  32,  32,  32,  32,  32,  32,  32, 
			 32,  32,  32,  32,  32,  32,  32,  32, 
			 32,  32,  32,  32,  32,  32,  32,  32, 
			 32,  32,  32,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
		};
		if ((source->limit() - source->cursor()) < 12) source->fill(12);
		yych = *source->cursor();
		if (yych <= '.') {
			if (yych <= '#') {
				if (yych <= '\f') {
					if (yych <= 0x08) {
						if (yych >= 0x01) goto yyy234;
					} else {
						if (yych == '\n') goto yyy294;
						goto yyy236;
					}
				} else {
					if (yych <= ' ') {
						if (yych <= 0x1F) goto yyy234;
						goto yyy236;
					} else {
						if (yych <= '!') goto yyy234;
						if (yych <= '"') goto yyy238;
						goto yyy240;
					}
				}
			} else {
				if (yych <= '(') {
					if (yych <= '%') {
						if (yych <= '$') goto yyy234;
						goto yyy242;
					} else {
						if (yych <= '&') goto yyy244;
						if (yych <= '\'') goto yyy246;
						goto yyy248;
					}
				} else {
					if (yych <= '+') {
						if (yych <= ')') goto yyy250;
						if (yych <= '*') goto yyy252;
						goto yyy254;
					} else {
						if (yych <= ',') goto yyy256;
						if (yych <= '-') goto yyy258;
						goto yyy260;
					}
				}
			}
		} else {
			if (yych <= '[') {
				if (yych <= '<') {
					if (yych <= '9') {
						if (yych <= '/') goto yyy262;
						goto yyy263;
					} else {
						if (yych <= ':') goto yyy265;
						if (yych <= ';') goto yyy267;
						goto yyy269;
					}
				} else {
					if (yych <= '?') {
						if (yych <= '=') goto yyy271;
						if (yych <= '>') goto yyy273;
						goto yyy234;
					} else {
						if (yych <= '@') goto yyy275;
						if (yych <= 'Z') goto yyy277;
						goto yyy279;
					}
				}
			} else {
				if (yych <= '`') {
					if (yych <= ']') {
						if (yych <= '\\') goto yyy281;
						goto yyy282;
					} else {
						if (yych <= '^') goto yyy284;
						if (yych <= '_') goto yyy277;
						goto yyy234;
					}
				} else {
					if (yych <= '|') {
						if (yych <= 'z') goto yyy277;
						if (yych <= '{') goto yyy286;
						goto yyy288;
					} else {
						if (yych <= '}') goto yyy290;
						if (yych <= '~') goto yyy292;
						goto yyy234;
					}
				}
			}
		}
		++source->cursor();
#line 87 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_EOF; 							goto re2c_finish; 					}
#line 1543 "<stdout>"
yyy234:
		++source->cursor();
yyy235:
#line 525 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_ERR_UNKNOWN_SYMBOL;					goto re2c_finish;					}
#line 1549 "<stdout>"
yyy236:
		++source->cursor();
#line 86 "bcplus/parser/detail/Scanner.3.re2c"
		{ 										goto re2c_start; 					}
#line 1554 "<stdout>"
yyy238:
		++source->cursor();
#line 139 "bcplus/parser/detail/Scanner.3.re2c"
		{ _cond = yycDBL_STRING;	preskip = 1;		goto yyc_DBL_STRING;				}
#line 1559 "<stdout>"
yyy240:
		++source->cursor();
		if ((yych = *source->cursor()) <= '^') {
			if (yych <= '9') {
				if (yych >= '0') goto yyy411;
			} else {
				if (yych <= '@') goto yyy241;
				if (yych <= 'Z') goto yyy414;
			}
		} else {
			if (yych <= 'a') {
				if (yych != '`') goto yyy414;
			} else {
				if (yych <= 'b') goto yyy417;
				if (yych <= 'z') goto yyy414;
			}
		}
yyy241:
#line 127 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_POUND;						goto re2c_finish;					}
#line 1580 "<stdout>"
yyy242:
		++source->cursor();
#line 143 "bcplus/parser/detail/Scanner.3.re2c"
		{ _cond = yycCOMMENT; 							goto yyc_COMMENT;	 				}
#line 1585 "<stdout>"
yyy244:
		++source->cursor();
		if ((yych = *source->cursor()) == '&') goto yyy409;
#line 115 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_AMP;							goto re2c_finish;					}
#line 1591 "<stdout>"
yyy246:
		++source->cursor();
#line 140 "bcplus/parser/detail/Scanner.3.re2c"
		{ _cond = yycSGL_STRING; 	preskip = 1;		goto yyc_SGL_STRING;				}
#line 1596 "<stdout>"
yyy248:
		++source->cursor();
#line 135 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_PAREN_L;						goto re2c_finish;					}
#line 1601 "<stdout>"
yyy250:
		++source->cursor();
#line 136 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_PAREN_R;						goto re2c_finish;					}
#line 1606 "<stdout>"
yyy252:
		++source->cursor();
#line 128 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_STAR;							goto re2c_finish;					}
#line 1611 "<stdout>"
yyy254:
		++source->cursor();
		if ((yych = *source->cursor()) == '+') goto yyy407;
#line 117 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_PLUS;							goto re2c_finish;					}
#line 1617 "<stdout>"
yyy256:
		++source->cursor();
#line 124 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_COMMA;						goto re2c_finish;					}
#line 1622 "<stdout>"
yyy258:
		++source->cursor();
		if ((yych = *source->cursor()) == '>') goto yyy403;
#line 95 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_DASH;							goto re2c_finish;					}
#line 1628 "<stdout>"
yyy260:
		++source->cursor();
		if ((yych = *source->cursor()) == '.') goto yyy401;
#line 119 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_PERIOD; _in_macro = false;	goto re2c_finish;					}
#line 1634 "<stdout>"
yyy262:
		yych = *++source->cursor();
		if (yych <= '.') {
			if (yych == '*') goto yyy395;
			goto yyy235;
		} else {
			if (yych <= '/') goto yyy399;
			if (yych == '\\') goto yyy397;
			goto yyy235;
		}
yyy263:
		++source->cursor();
		yych = *source->cursor();
		goto yyy394;
yyy264:
#line 211 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_INTEGER;						goto re2c_finish;					}
#line 1652 "<stdout>"
yyy265:
		++source->cursor();
		if ((yych = *source->cursor()) == '-') goto yyy341;
		if (yych == ':') goto yyy343;
#line 92 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_COLON;						goto re2c_finish;					}
#line 1659 "<stdout>"
yyy267:
		++source->cursor();
#line 125 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_SEMICOLON;					goto re2c_finish;					}
#line 1664 "<stdout>"
yyy269:
		++source->cursor();
		if ((yych = *source->cursor()) <= '<') {
			if (yych == '-') goto yyy337;
		} else {
			if (yych <= '=') goto yyy333;
			if (yych <= '>') goto yyy335;
		}
#line 99 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_LTHAN;						goto re2c_finish;					}
#line 1675 "<stdout>"
yyy271:
		++source->cursor();
		if ((yych = *source->cursor()) <= ';') goto yyy272;
		if (yych <= '<') goto yyy331;
		if (yych <= '=') goto yyy327;
		if (yych <= '>') goto yyy329;
yyy272:
#line 113 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_EQ;							goto re2c_finish;					}
#line 1685 "<stdout>"
yyy273:
		++source->cursor();
		if ((yych = *source->cursor()) <= '<') goto yyy274;
		if (yych <= '=') goto yyy325;
		if (yych <= '>') goto yyy323;
yyy274:
#line 101 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_GTHAN;						goto re2c_finish;					}
#line 1694 "<stdout>"
yyy275:
		yyaccept = 0;
		yych = *(source->marker() = ++source->cursor());
		if (yych <= '@') {
			if (yych <= '<') {
				if (yych >= '<') goto yyy313;
			} else {
				if (yych <= '=') goto yyy310;
				if (yych <= '>') goto yyy311;
			}
		} else {
			if (yych <= '_') {
				if (yych <= 'Z') goto yyy307;
				if (yych >= '_') goto yyy307;
			} else {
				if (yych <= '`') goto yyy276;
				if (yych <= 'z') goto yyy307;
			}
		}
yyy276:
#line 130 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_AT;							goto re2c_finish;					}
#line 1717 "<stdout>"
yyy277:
		marker = source->cursor() + 1;
		yyaccept = 1;
		yych = *(source->marker() = ++source->cursor());
		if (yybm[0+yych] & 64) {
			goto yyy302;
		}
		if (yych <= '@') {
			if (yych <= '(') {
				if (yych >= '(') goto yyy305;
			} else {
				if (yych <= '/') goto yyy278;
				if (yych <= '9') goto yyy300;
			}
		} else {
			if (yych <= '_') {
				if (yych <= 'Z') goto yyy300;
				if (yych >= '_') goto yyy300;
			} else {
				if (yych <= '`') goto yyy278;
				if (yych <= 'z') goto yyy300;
			}
		}
yyy278:
#line 212 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_IDENTIFIER;					goto re2c_finish;					}
#line 1744 "<stdout>"
yyy279:
		++source->cursor();
#line 131 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_BRACKET_L;					goto re2c_finish;					}
#line 1749 "<stdout>"
yyy281:
		yych = *++source->cursor();
		if (yych == '/') goto yyy296;
		if (yych == '=') goto yyy298;
		goto yyy235;
yyy282:
		++source->cursor();
#line 132 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_BRACKET_R;					goto re2c_finish;					}
#line 1759 "<stdout>"
yyy284:
		++source->cursor();
#line 129 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_CARROT;						goto re2c_finish;					}
#line 1764 "<stdout>"
yyy286:
		++source->cursor();
#line 133 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_CBRACKET_L;					goto re2c_finish;					}
#line 1769 "<stdout>"
yyy288:
		++source->cursor();
#line 126 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_PIPE;							goto re2c_finish;					}
#line 1774 "<stdout>"
yyy290:
		++source->cursor();
#line 134 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_CBRACKET_R;					goto re2c_finish;					}
#line 1779 "<stdout>"
yyy292:
		++source->cursor();
#line 93 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_TILDE;						goto re2c_finish;					}
#line 1784 "<stdout>"
yyy294:
		++source->cursor();
#line 85 "bcplus/parser/detail/Scanner.3.re2c"
		{ source->newline();		 			goto re2c_start; 					}
#line 1789 "<stdout>"
yyy296:
		++source->cursor();
#line 121 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_BIG_DISJ;						goto re2c_finish;					}
#line 1794 "<stdout>"
yyy298:
		++source->cursor();
#line 120 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_NEQ;							goto re2c_finish;					}
#line 1799 "<stdout>"
yyy300:
		marker = source->cursor() + 1;
		yyaccept = 1;
		source->marker() = ++source->cursor();
		if (source->limit() <= source->cursor()) source->fill(1);
		yych = *source->cursor();
		if (yybm[0+yych] & 64) {
			goto yyy302;
		}
		if (yych <= '@') {
			if (yych <= '(') {
				if (yych <= '\'') goto yyy278;
				goto yyy305;
			} else {
				if (yych <= '/') goto yyy278;
				if (yych <= '9') goto yyy300;
				goto yyy278;
			}
		} else {
			if (yych <= '_') {
				if (yych <= 'Z') goto yyy300;
				if (yych <= '^') goto yyy278;
				goto yyy300;
			} else {
				if (yych <= '`') goto yyy278;
				if (yych <= 'z') goto yyy300;
				goto yyy278;
			}
		}
yyy302:
		++source->cursor();
		if (source->limit() <= source->cursor()) source->fill(1);
		yych = *source->cursor();
		if (yybm[0+yych] & 64) {
			goto yyy302;
		}
		if (yych == '(') goto yyy305;
yyy304:
		source->cursor() = source->marker();
		if (yyaccept <= 1) {
			if (yyaccept == 0) {
				goto yyy276;
			} else {
				goto yyy278;
			}
		} else {
			goto yyy342;
		}
yyy305:
		++source->cursor();
		source->cursor() = marker;
#line 200 "bcplus/parser/detail/Scanner.3.re2c"
		{ 
												  ret = T_IDENTIFIER;
												  _cond = yycARG;
												  goto re2c_finish;					
												}
#line 1857 "<stdout>"
yyy307:
		++source->cursor();
		if (source->limit() <= source->cursor()) source->fill(1);
		yych = *source->cursor();
		if (yych <= 'Z') {
			if (yych <= '/') goto yyy309;
			if (yych <= '9') goto yyy307;
			if (yych >= 'A') goto yyy307;
		} else {
			if (yych <= '_') {
				if (yych >= '_') goto yyy307;
			} else {
				if (yych <= '`') goto yyy309;
				if (yych <= 'z') goto yyy307;
			}
		}
yyy309:
#line 215 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_AT_IDENTIFIER;				goto re2c_finish;					}
#line 1877 "<stdout>"
yyy310:
		yych = *++source->cursor();
		if (yych == '<') goto yyy319;
		if (yych == '>') goto yyy321;
		goto yyy304;
yyy311:
		++source->cursor();
		if ((yych = *source->cursor()) == '=') goto yyy317;
#line 105 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_GTHAN;						goto re2c_finish;					}
#line 1888 "<stdout>"
yyy313:
		++source->cursor();
		if ((yych = *source->cursor()) == '=') goto yyy315;
#line 104 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_LTHAN;						goto re2c_finish;					}
#line 1894 "<stdout>"
yyy315:
		++source->cursor();
#line 106 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_LTHAN_EQ;						goto re2c_finish;					}
#line 1899 "<stdout>"
yyy317:
		++source->cursor();
#line 107 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_GTHAN_EQ;						goto re2c_finish;					}
#line 1904 "<stdout>"
yyy319:
		++source->cursor();
#line 108 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_LTHAN_EQ;						goto re2c_finish;					}
#line 1909 "<stdout>"
yyy321:
		++source->cursor();
#line 109 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_GTHAN_EQ;						goto re2c_finish;					}
#line 1914 "<stdout>"
yyy323:
		++source->cursor();
#line 103 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_DBL_GTHAN;					goto re2c_finish;					}
#line 1919 "<stdout>"
yyy325:
		++source->cursor();
#line 102 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_GTHAN_EQ;						goto re2c_finish;					}
#line 1924 "<stdout>"
yyy327:
		++source->cursor();
#line 112 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_DBL_EQ;						goto re2c_finish;					}
#line 1929 "<stdout>"
yyy329:
		++source->cursor();
#line 111 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_GTHAN_EQ;						goto re2c_finish;					}
#line 1934 "<stdout>"
yyy331:
		++source->cursor();
#line 110 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_LTHAN_EQ;						goto re2c_finish;					}
#line 1939 "<stdout>"
yyy333:
		++source->cursor();
#line 100 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_LTHAN_EQ;						goto re2c_finish;					}
#line 1944 "<stdout>"
yyy335:
		++source->cursor();
#line 98 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_NEQ;							goto re2c_finish;					}
#line 1949 "<stdout>"
yyy337:
		++source->cursor();
		if ((yych = *source->cursor()) == '>') goto yyy339;
#line 97 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_ARROW_LDASH;					goto re2c_finish;					}
#line 1955 "<stdout>"
yyy339:
		++source->cursor();
#line 96 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_EQUIV;						goto re2c_finish;					}
#line 1960 "<stdout>"
yyy341:
		yyaccept = 2;
		yych = *(source->marker() = ++source->cursor());
		if (yych <= '\f') {
			if (yych == '\t') goto yyy345;
			if (yych >= '\v') goto yyy345;
		} else {
			if (yych <= ' ') {
				if (yych >= ' ') goto yyy345;
			} else {
				if (yych == 'b') goto yyy347;
			}
		}
yyy342:
#line 90 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_COLON_DASH;					goto re2c_finish;					}
#line 1977 "<stdout>"
yyy343:
		++source->cursor();
#line 91 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_DBL_COLON;					goto re2c_finish;					}
#line 1982 "<stdout>"
yyy345:
		++source->cursor();
		if ((source->limit() - source->cursor()) < 10) source->fill(10);
		yych = *source->cursor();
		if (yych <= '\f') {
			if (yych == '\t') goto yyy345;
			if (yych <= '\n') goto yyy304;
			goto yyy345;
		} else {
			if (yych <= ' ') {
				if (yych <= 0x1F) goto yyy304;
				goto yyy345;
			} else {
				if (yych != 'b') goto yyy304;
			}
		}
yyy347:
		yych = *++source->cursor();
		if (yych != 'e') goto yyy304;
		yych = *++source->cursor();
		if (yych != 'g') goto yyy304;
		yych = *++source->cursor();
		if (yych != 'i') goto yyy304;
		yych = *++source->cursor();
		if (yych != 'n') goto yyy304;
		yych = *++source->cursor();
		if (yych <= '\f') {
			if (yych == '\t') goto yyy352;
			if (yych <= '\n') goto yyy304;
		} else {
			if (yych <= ' ') {
				if (yych <= 0x1F) goto yyy304;
			} else {
				if (yych == '_') goto yyy354;
				goto yyy304;
			}
		}
yyy352:
		++source->cursor();
		if ((source->limit() - source->cursor()) < 4) source->fill(4);
		yych = *source->cursor();
		if (yych <= ' ') {
			if (yych <= '\n') {
				if (yych == '\t') goto yyy352;
				goto yyy304;
			} else {
				if (yych <= '\f') goto yyy352;
				if (yych <= 0x1F) goto yyy304;
				goto yyy352;
			}
		} else {
			if (yych <= 'e') {
				if (yych == 'a') goto yyy374;
				goto yyy304;
			} else {
				if (yych <= 'f') goto yyy376;
				if (yych == 'l') goto yyy375;
				goto yyy304;
			}
		}
yyy354:
		yych = *++source->cursor();
		if (yych <= 'e') {
			if (yych != 'a') goto yyy304;
		} else {
			if (yych <= 'f') goto yyy357;
			if (yych == 'l') goto yyy356;
			goto yyy304;
		}
		yych = *++source->cursor();
		if (yych == 's') goto yyy369;
		goto yyy304;
yyy356:
		yych = *++source->cursor();
		if (yych == 'u') goto yyy364;
		goto yyy304;
yyy357:
		yych = *++source->cursor();
		if (yych != '2') goto yyy304;
		yych = *++source->cursor();
		if (yych != 'l') goto yyy304;
		yych = *++source->cursor();
		if (yych != 'p') goto yyy304;
yyy360:
		++source->cursor();
		if (source->limit() <= source->cursor()) source->fill(1);
		yych = *source->cursor();
		if (yych <= '\f') {
			if (yych == '\t') goto yyy360;
			if (yych <= '\n') goto yyy304;
			goto yyy360;
		} else {
			if (yych <= ' ') {
				if (yych <= 0x1F) goto yyy304;
				goto yyy360;
			} else {
				if (yych != '.') goto yyy304;
			}
		}
		++source->cursor();
#line 184 "bcplus/parser/detail/Scanner.3.re2c"
		{
												  _cond = yycF2LP_CP;
												  BLK_INIT("");
												  goto yyc_F2LP_CP;
												}
#line 2089 "<stdout>"
yyy364:
		yych = *++source->cursor();
		if (yych != 'a') goto yyy304;
yyy365:
		++source->cursor();
		if (source->limit() <= source->cursor()) source->fill(1);
		yych = *source->cursor();
		if (yych <= '\f') {
			if (yych == '\t') goto yyy365;
			if (yych <= '\n') goto yyy304;
			goto yyy365;
		} else {
			if (yych <= ' ') {
				if (yych <= 0x1F) goto yyy304;
				goto yyy365;
			} else {
				if (yych != '.') goto yyy304;
			}
		}
		++source->cursor();
#line 167 "bcplus/parser/detail/Scanner.3.re2c"
		{
												  _cond = yycLUA_CP;
												  BLK_INIT("");
												  goto yyc_LUA_CP;
												}
#line 2116 "<stdout>"
yyy369:
		yych = *++source->cursor();
		if (yych != 'p') goto yyy304;
yyy370:
		++source->cursor();
		if (source->limit() <= source->cursor()) source->fill(1);
		yych = *source->cursor();
		if (yych <= '\f') {
			if (yych == '\t') goto yyy370;
			if (yych <= '\n') goto yyy304;
			goto yyy370;
		} else {
			if (yych <= ' ') {
				if (yych <= 0x1F) goto yyy304;
				goto yyy370;
			} else {
				if (yych != '.') goto yyy304;
			}
		}
		++source->cursor();
#line 150 "bcplus/parser/detail/Scanner.3.re2c"
		{
												  _cond = yycASP_CP;
												  BLK_INIT("");
												  goto yyc_ASP_CP;
												}
#line 2143 "<stdout>"
yyy374:
		yych = *++source->cursor();
		if (yych == 's') goto yyy388;
		goto yyy304;
yyy375:
		yych = *++source->cursor();
		if (yych == 'u') goto yyy383;
		goto yyy304;
yyy376:
		yych = *++source->cursor();
		if (yych != '2') goto yyy304;
		yych = *++source->cursor();
		if (yych != 'l') goto yyy304;
		yych = *++source->cursor();
		if (yych != 'p') goto yyy304;
yyy379:
		++source->cursor();
		if (source->limit() <= source->cursor()) source->fill(1);
		yych = *source->cursor();
		if (yych <= '\f') {
			if (yych == '\t') goto yyy379;
			if (yych <= '\n') goto yyy304;
			goto yyy379;
		} else {
			if (yych <= ' ') {
				if (yych <= 0x1F) goto yyy304;
				goto yyy379;
			} else {
				if (yych != '.') goto yyy304;
			}
		}
		++source->cursor();
#line 190 "bcplus/parser/detail/Scanner.3.re2c"
		{
												  _cond = yycF2LP_CP;
												  BLK_INIT("");
												  goto yyc_F2LP_CP;
												}
#line 2182 "<stdout>"
yyy383:
		yych = *++source->cursor();
		if (yych != 'a') goto yyy304;
yyy384:
		++source->cursor();
		if (source->limit() <= source->cursor()) source->fill(1);
		yych = *source->cursor();
		if (yych <= '\f') {
			if (yych == '\t') goto yyy384;
			if (yych <= '\n') goto yyy304;
			goto yyy384;
		} else {
			if (yych <= ' ') {
				if (yych <= 0x1F) goto yyy304;
				goto yyy384;
			} else {
				if (yych != '.') goto yyy304;
			}
		}
		++source->cursor();
#line 173 "bcplus/parser/detail/Scanner.3.re2c"
		{
												  _cond = yycLUA_CP;
												  BLK_INIT("");
												  goto yyc_LUA_CP;
												}
#line 2209 "<stdout>"
yyy388:
		yych = *++source->cursor();
		if (yych != 'p') goto yyy304;
yyy389:
		++source->cursor();
		if (source->limit() <= source->cursor()) source->fill(1);
		yych = *source->cursor();
		if (yych <= '\f') {
			if (yych == '\t') goto yyy389;
			if (yych <= '\n') goto yyy304;
			goto yyy389;
		} else {
			if (yych <= ' ') {
				if (yych <= 0x1F) goto yyy304;
				goto yyy389;
			} else {
				if (yych != '.') goto yyy304;
			}
		}
		++source->cursor();
#line 156 "bcplus/parser/detail/Scanner.3.re2c"
		{
												  _cond = yycASP_CP;
												  BLK_INIT("");
												  goto yyc_ASP_CP;
												}
#line 2236 "<stdout>"
yyy393:
		++source->cursor();
		if (source->limit() <= source->cursor()) source->fill(1);
		yych = *source->cursor();
yyy394:
		if (yybm[0+yych] & 128) {
			goto yyy393;
		}
		goto yyy264;
yyy395:
		++source->cursor();
#line 144 "bcplus/parser/detail/Scanner.3.re2c"
		{ 
												  _cond = yycBLK_COMMENT; 
												  BLK_INIT("% ");
												  goto yyc_BLK_COMMENT; 				
												}
#line 2254 "<stdout>"
yyy397:
		++source->cursor();
#line 123 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_BIG_CONJ;						goto re2c_finish;					}
#line 2259 "<stdout>"
yyy399:
		++source->cursor();
#line 122 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_INT_DIV;						goto re2c_finish;					}
#line 2264 "<stdout>"
yyy401:
		++source->cursor();
#line 118 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_DBL_PERIOD;					goto re2c_finish;					}
#line 2269 "<stdout>"
yyy403:
		++source->cursor();
		if ((yych = *source->cursor()) == '>') goto yyy405;
#line 205 "bcplus/parser/detail/Scanner.3.re2c"
		{ 
												  ret = T_ARROW_RDASH; 
												  if (_in_macro) _cond = yycMACRO;		
												  goto re2c_finish;	
												}
#line 2279 "<stdout>"
yyy405:
		++source->cursor();
#line 94 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_IMPL;							goto re2c_finish;					}
#line 2284 "<stdout>"
yyy407:
		++source->cursor();
#line 116 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_DBL_PLUS;						goto re2c_finish;					}
#line 2289 "<stdout>"
yyy409:
		++source->cursor();
#line 114 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_DBL_AMP;						goto re2c_finish;					}
#line 2294 "<stdout>"
yyy411:
		++source->cursor();
		if (source->limit() <= source->cursor()) source->fill(1);
		yych = *source->cursor();
		if (yych <= '/') goto yyy413;
		if (yych <= '9') goto yyy411;
yyy413:
#line 214 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_POUND_INTEGER;				goto re2c_finish;					}
#line 2304 "<stdout>"
yyy414:
		++source->cursor();
		if (source->limit() <= source->cursor()) source->fill(1);
		yych = *source->cursor();
yyy415:
		if (yych <= 'Z') {
			if (yych <= '/') goto yyy416;
			if (yych <= '9') goto yyy414;
			if (yych >= 'A') goto yyy414;
		} else {
			if (yych <= '_') {
				if (yych >= '_') goto yyy414;
			} else {
				if (yych <= '`') goto yyy416;
				if (yych <= 'z') goto yyy414;
			}
		}
yyy416:
#line 213 "bcplus/parser/detail/Scanner.3.re2c"
		{ ret = T_POUND_IDENTIFIER;				goto re2c_finish;					}
#line 2325 "<stdout>"
yyy417:
		yych = *++source->cursor();
		if (yych != 'e') goto yyy415;
		yych = *++source->cursor();
		if (yych != 'g') goto yyy415;
		yych = *++source->cursor();
		if (yych != 'i') goto yyy415;
		yych = *++source->cursor();
		if (yych != 'n') goto yyy415;
		yych = *++source->cursor();
		if (yych != '_') goto yyy415;
		yych = *++source->cursor();
		if (yych <= 'e') {
			if (yych != 'a') goto yyy415;
		} else {
			if (yych <= 'f') goto yyy424;
			if (yych == 'l') goto yyy425;
			goto yyy415;
		}
		yych = *++source->cursor();
		if (yych == 's') goto yyy439;
		goto yyy415;
yyy424:
		yych = *++source->cursor();
		if (yych == '2') goto yyy432;
		goto yyy415;
yyy425:
		yych = *++source->cursor();
		if (yych != 'u') goto yyy415;
		yych = *++source->cursor();
		if (yych != 'a') goto yyy415;
		++source->cursor();
		if ((yych = *source->cursor()) <= 'Z') {
			if (yych <= '/') goto yyy430;
			if (yych <= '9') goto yyy414;
			if (yych <= '@') goto yyy430;
			goto yyy414;
		} else {
			if (yych <= '_') {
				if (yych <= '^') goto yyy430;
				goto yyy414;
			} else {
				if (yych <= '`') goto yyy430;
				if (yych <= 'z') goto yyy414;
				goto yyy430;
			}
		}
yyy428:
#line 178 "bcplus/parser/detail/Scanner.3.re2c"
		{
												  _cond = yycLUA_GR;
												  BLK_INIT("");
												  goto yyc_LUA_GR;
												}
#line 2380 "<stdout>"
yyy429:
		++source->cursor();
		if (source->limit() <= source->cursor()) source->fill(1);
		yych = *source->cursor();
yyy430:
		if (yych <= '\f') {
			if (yych == '\t') goto yyy429;
			if (yych <= '\n') goto yyy428;
			goto yyy429;
		} else {
			if (yych <= ' ') {
				if (yych <= 0x1F) goto yyy428;
				goto yyy429;
			} else {
				if (yych != '.') goto yyy428;
			}
		}
		yych = *++source->cursor();
		goto yyy428;
yyy432:
		yych = *++source->cursor();
		if (yych != 'l') goto yyy415;
		yych = *++source->cursor();
		if (yych != 'p') goto yyy415;
		++source->cursor();
		if ((yych = *source->cursor()) <= 'Z') {
			if (yych <= '/') goto yyy437;
			if (yych <= '9') goto yyy414;
			if (yych <= '@') goto yyy437;
			goto yyy414;
		} else {
			if (yych <= '_') {
				if (yych <= '^') goto yyy437;
				goto yyy414;
			} else {
				if (yych <= '`') goto yyy437;
				if (yych <= 'z') goto yyy414;
				goto yyy437;
			}
		}
yyy435:
#line 195 "bcplus/parser/detail/Scanner.3.re2c"
		{
												  _cond = yycF2LP_GR;
												  BLK_INIT("");
												  goto yyc_F2LP_GR;
												}
#line 2428 "<stdout>"
yyy436:
		++source->cursor();
		if (source->limit() <= source->cursor()) source->fill(1);
		yych = *source->cursor();
yyy437:
		if (yych <= '\f') {
			if (yych == '\t') goto yyy436;
			if (yych <= '\n') goto yyy435;
			goto yyy436;
		} else {
			if (yych <= ' ') {
				if (yych <= 0x1F) goto yyy435;
				goto yyy436;
			} else {
				if (yych != '.') goto yyy435;
			}
		}
		yych = *++source->cursor();
		goto yyy435;
yyy439:
		yych = *++source->cursor();
		if (yych != 'p') goto yyy415;
		++source->cursor();
		if ((yych = *source->cursor()) <= 'Z') {
			if (yych <= '/') goto yyy443;
			if (yych <= '9') goto yyy414;
			if (yych <= '@') goto yyy443;
			goto yyy414;
		} else {
			if (yych <= '_') {
				if (yych <= '^') goto yyy443;
				goto yyy414;
			} else {
				if (yych <= '`') goto yyy443;
				if (yych <= 'z') goto yyy414;
				goto yyy443;
			}
		}
yyy441:
#line 161 "bcplus/parser/detail/Scanner.3.re2c"
		{
												  _cond = yycASP_GR;
												  BLK_INIT("");
												  goto yyc_ASP_GR;
												}
#line 2474 "<stdout>"
yyy442:
		++source->cursor();
		if (source->limit() <= source->cursor()) source->fill(1);
		yych = *source->cursor();
yyy443:
		if (yych <= '\f') {
			if (yych == '\t') goto yyy442;
			if (yych <= '\n') goto yyy441;
			goto yyy442;
		} else {
			if (yych <= ' ') {
				if (yych <= 0x1F) goto yyy441;
				goto yyy442;
			} else {
				if (yych != '.') goto yyy441;
			}
		}
		++source->cursor();
		yych = *source->cursor();
		goto yyy441;
	}
/* *********************************** */
yyc_SGL_STRING:
	if ((source->limit() - source->cursor()) < 2) source->fill(2);
	yych = *source->cursor();
	if (yych <= '&') {
		if (yych <= 0x00) goto yyy447;
		if (yych == '\n') goto yyy453;
		goto yyy449;
	} else {
		if (yych <= '\'') goto yyy450;
		if (yych == '\\') goto yyy452;
		goto yyy449;
	}
yyy447:
	++source->cursor();
yyy448:
#line 241 "bcplus/parser/detail/Scanner.3.re2c"
	{												goto yyc_SGL_STRING;				}
#line 2514 "<stdout>"
yyy449:
	yych = *++source->cursor();
	goto yyy448;
yyy450:
	++source->cursor();
#line 235 "bcplus/parser/detail/Scanner.3.re2c"
	{ 
												  _cond = yycNORMAL; 
												  ret = T_STRING_LITERAL;	
												  postskip = 1;
												  goto re2c_finish;					
												}
#line 2527 "<stdout>"
yyy452:
	yych = *++source->cursor();
	if (yych == '\'') goto yyy455;
	goto yyy448;
yyy453:
	++source->cursor();
#line 233 "bcplus/parser/detail/Scanner.3.re2c"
	{ source->newline();				 			goto yyc_SGL_STRING; 				}
#line 2536 "<stdout>"
yyy455:
	++source->cursor();
#line 234 "bcplus/parser/detail/Scanner.3.re2c"
	{ 												goto yyc_SGL_STRING; 				}
#line 2541 "<stdout>"
}
#line 527 "bcplus/parser/detail/Scanner.3.re2c"

re2c_finish:
	u::ref_ptr<ReferencedString> str = new ReferencedString();
	if (ret != T_EOF) {
		if (use_blk)
			str->assign(blk.str());
		else
			str->assign(source->token() + preskip, (size_t)(source->cursor() - source->token() - preskip - postskip));
	} else {
		str->assign("<EOF>");
	}

	return new Token(ret, str, begin, source->loc());
}

}}}
