/* Generated by re2c 0.13.6 on Tue Aug 26 22:13:01 2014 */
#line 1 "bcplus/parser/detail/Scanner.2.re2c"

#include <sstream>

#include <boost/filesystem.hpp>
#include <boost/filesystem/fstream.hpp>

#include "bcplus/parser/detail/Scanner.h"
#include "bcplus/parser/detail/lemon_parser.h"

#include "bcplus/Location.h"
#include "bcplus/parser/Token.h"

#include "bcplus/parser/detail/ScannerSource.h"
#include "bcplus/parser/detail/ScannerRawSource.h"
#include "bcplus/parser/detail/ScannerTokenSource.h"
#include "bcplus/parser/detail/ScannerFileSource.h"
#include "bcplus/parser/detail/ScannerBufferSource.h"

namespace u = babb::utils; 
namespace fs = boost::filesystem;

namespace bcplus {
namespace parser {
namespace detail {

Token* Scanner::tokenize_2(ScannerRawSource* source) {
	if (source->eof()) return new Token(T_EOF, new ReferencedString("<EOF>"), source->loc(), source->loc());
	else if (!source->good()) return new Token(T_ERR_IO, new ReferencedString("<IO ERROR>"), source->loc(), source->loc());


	int ret;
	Location begin;

	begin = source->loc();
	source->token() = source->cursor();



	if (_cond == yycNORMAL) {
			
#line 44 "<stdout>"
{
	char yych;
	goto yyc_NORMAL;
/* *********************************** */
yyc_NORMAL:
	{
		static const unsigned char yybm[] = {
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0, 128,   0, 128, 128,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			128,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
		};
		if ((source->limit() - source->cursor()) < 21) source->fill(21);
		yych = *source->cursor();
		if (yych <= 'k') {
			if (yych <= 'c') {
				if (yych <= '`') {
					if (yych != '\n') goto yy2_4;
				} else {
					if (yych <= 'a') goto yy2_6;
					if (yych <= 'b') goto yy2_7;
					goto yy2_8;
				}
			} else {
				if (yych <= 'f') {
					if (yych <= 'd') goto yy2_9;
					if (yych <= 'e') goto yy2_10;
					goto yy2_11;
				} else {
					if (yych <= 'g') goto yy2_4;
					if (yych <= 'h') goto yy2_12;
					if (yych <= 'i') goto yy2_13;
					goto yy2_4;
				}
			}
		} else {
			if (yych <= 'q') {
				if (yych <= 'n') {
					if (yych <= 'l') goto yy2_14;
					if (yych <= 'm') goto yy2_15;
					goto yy2_16;
				} else {
					if (yych <= 'o') goto yy2_17;
					if (yych <= 'p') goto yy2_18;
					goto yy2_19;
				}
			} else {
				if (yych <= 't') {
					if (yych <= 'r') goto yy2_20;
					if (yych <= 's') goto yy2_21;
					goto yy2_22;
				} else {
					if (yych <= 'u') goto yy2_23;
					if (yych <= 'v') goto yy2_24;
					if (yych <= 'w') goto yy2_25;
					goto yy2_4;
				}
			}
		}
yy2_3:
		source->cursor() = source->marker();
		goto yy2_5;
yy2_4:
		++source->cursor();
yy2_5:
#line 123 "bcplus/parser/detail/Scanner.2.re2c"
		{ goto re2c_notkw; }
#line 140 "<stdout>"
yy2_6:
		yych = *(source->marker() = ++source->cursor());
		switch (yych) {
		case 'b':	goto yy2_419;
		case 'c':	goto yy2_425;
		case 'd':	goto yy2_424;
		case 'f':	goto yy2_423;
		case 'l':	goto yy2_421;
		case 's':	goto yy2_422;
		case 't':	goto yy2_420;
		default:	goto yy2_5;
		}
yy2_7:
		yych = *(source->marker() = ++source->cursor());
		if (yych == 'y') goto yy2_416;
		goto yy2_5;
yy2_8:
		yych = *(source->marker() = ++source->cursor());
		if (yych == 'a') goto yy2_390;
		if (yych == 'o') goto yy2_389;
		goto yy2_5;
yy2_9:
		yych = *(source->marker() = ++source->cursor());
		if (yych == 'e') goto yy2_371;
		goto yy2_5;
yy2_10:
		yych = *(source->marker() = ++source->cursor());
		if (yych == 'q') goto yy2_328;
		if (yych == 'x') goto yy2_329;
		goto yy2_5;
yy2_11:
		yych = *(source->marker() = ++source->cursor());
		if (yych == 'a') goto yy2_322;
		goto yy2_5;
yy2_12:
		yych = *(source->marker() = ++source->cursor());
		if (yych == 'i') goto yy2_317;
		goto yy2_5;
yy2_13:
		yych = *(source->marker() = ++source->cursor());
		if (yych <= 'l') {
			if (yych == 'f') goto yy2_266;
			goto yy2_5;
		} else {
			if (yych <= 'm') goto yy2_265;
			if (yych <= 'n') goto yy2_264;
			goto yy2_5;
		}
yy2_14:
		yych = *(source->marker() = ++source->cursor());
		if (yych == 'a') goto yy2_258;
		goto yy2_5;
yy2_15:
		yych = *(source->marker() = ++source->cursor());
		if (yych == 'a') goto yy2_213;
		if (yych == 'o') goto yy2_212;
		goto yy2_5;
yy2_16:
		yych = *(source->marker() = ++source->cursor());
		if (yych == 'e') goto yy2_174;
		if (yych == 'o') goto yy2_173;
		goto yy2_5;
yy2_17:
		yych = *(source->marker() = ++source->cursor());
		if (yych == 'b') goto yy2_155;
		if (yych == 'f') goto yy2_154;
		goto yy2_5;
yy2_18:
		yych = *(source->marker() = ++source->cursor());
		if (yych == 'o') goto yy2_137;
		goto yy2_5;
yy2_19:
		yych = *(source->marker() = ++source->cursor());
		if (yych == 'u') goto yy2_131;
		goto yy2_5;
yy2_20:
		yych = *(source->marker() = ++source->cursor());
		if (yych == 'i') goto yy2_125;
		goto yy2_5;
yy2_21:
		yych = *(source->marker() = ++source->cursor());
		switch (yych) {
		case 'd':	goto yy2_56;
		case 'h':	goto yy2_58;
		case 'i':	goto yy2_55;
		case 'o':	goto yy2_57;
		case 't':	goto yy2_54;
		default:	goto yy2_5;
		}
yy2_22:
		yych = *(source->marker() = ++source->cursor());
		if (yych == 'r') goto yy2_49;
		goto yy2_5;
yy2_23:
		yych = *(source->marker() = ++source->cursor());
		if (yych == 'n') goto yy2_42;
		goto yy2_5;
yy2_24:
		yych = *(source->marker() = ++source->cursor());
		if (yych == 'a') goto yy2_32;
		goto yy2_5;
yy2_25:
		yych = *(source->marker() = ++source->cursor());
		if (yych != 'h') goto yy2_5;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'r') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		source->ctxmarker() = source->cursor() + 1;
		yych = *++source->cursor();
		if (yych <= '@') goto yy2_30;
		if (yych <= 'Z') goto yy2_3;
		if (yych <= '`') goto yy2_30;
		if (yych <= 'z') goto yy2_3;
yy2_30:
		++source->cursor();
		source->cursor() = source->ctxmarker();
#line 112 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_WHERE;						goto re2c_finish;					}
#line 262 "<stdout>"
yy2_32:
		yych = *++source->cursor();
		if (yych != 'r') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'i') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'a') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'b') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'l') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 's') goto yy2_3;
		source->ctxmarker() = source->cursor() + 1;
		yych = *++source->cursor();
		if (yych <= '@') goto yy2_40;
		if (yych <= 'Z') goto yy2_3;
		if (yych <= '`') goto yy2_40;
		if (yych <= 'z') goto yy2_3;
yy2_40:
		++source->cursor();
		source->cursor() = source->ctxmarker();
#line 65 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_VARIABLES;					goto re2c_finish;					}
#line 289 "<stdout>"
yy2_42:
		yych = *++source->cursor();
		if (yych != 'l') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 's') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 's') goto yy2_3;
		source->ctxmarker() = source->cursor() + 1;
		yych = *++source->cursor();
		if (yych <= '@') goto yy2_47;
		if (yych <= 'Z') goto yy2_3;
		if (yych <= '`') goto yy2_47;
		if (yych <= 'z') goto yy2_3;
yy2_47:
		++source->cursor();
		source->cursor() = source->ctxmarker();
#line 111 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_UNLESS;						goto re2c_finish;					}
#line 310 "<stdout>"
yy2_49:
		yych = *++source->cursor();
		if (yych != 'u') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		source->ctxmarker() = source->cursor() + 1;
		yych = *++source->cursor();
		if (yych <= '@') goto yy2_52;
		if (yych <= 'Z') goto yy2_3;
		if (yych <= '`') goto yy2_52;
		if (yych <= 'z') goto yy2_3;
yy2_52:
		++source->cursor();
		source->cursor() = source->ctxmarker();
#line 119 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_TRUE;							goto re2c_finish;					}
#line 327 "<stdout>"
yy2_54:
		yych = *++source->cursor();
		if (yych == 'r') goto yy2_88;
		goto yy2_3;
yy2_55:
		yych = *++source->cursor();
		if (yych == 'm') goto yy2_76;
		goto yy2_3;
yy2_56:
		yych = *++source->cursor();
		if (yych == 'F') goto yy2_68;
		goto yy2_3;
yy2_57:
		yych = *++source->cursor();
		if (yych == 'r') goto yy2_63;
		goto yy2_3;
yy2_58:
		yych = *++source->cursor();
		if (yych != 'o') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'w') goto yy2_3;
		source->ctxmarker() = source->cursor() + 1;
		yych = *++source->cursor();
		if (yych <= '@') goto yy2_61;
		if (yych <= 'Z') goto yy2_3;
		if (yych <= '`') goto yy2_61;
		if (yych <= 'z') goto yy2_3;
yy2_61:
		++source->cursor();
		source->cursor() = source->ctxmarker();
#line 62 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_SHOW;							goto re2c_finish;					}
#line 360 "<stdout>"
yy2_63:
		yych = *++source->cursor();
		if (yych != 't') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 's') goto yy2_3;
		source->ctxmarker() = source->cursor() + 1;
		yych = *++source->cursor();
		if (yych <= '@') goto yy2_66;
		if (yych <= 'Z') goto yy2_3;
		if (yych <= '`') goto yy2_66;
		if (yych <= 'z') goto yy2_3;
yy2_66:
		++source->cursor();
		source->cursor() = source->ctxmarker();
#line 64 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_SORTS;						goto re2c_finish;					}
#line 377 "<stdout>"
yy2_68:
		yych = *++source->cursor();
		if (yych != 'l') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'u') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 't') goto yy2_3;
		source->ctxmarker() = source->cursor() + 1;
		yych = *++source->cursor();
		if (yych <= '@') goto yy2_74;
		if (yych <= 'Z') goto yy2_3;
		if (yych <= '`') goto yy2_74;
		if (yych <= 'z') goto yy2_3;
yy2_74:
		++source->cursor();
		source->cursor() = source->ctxmarker();
#line 105 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_SDFLUENT;						goto re2c_finish;					}
#line 400 "<stdout>"
yy2_76:
		yych = *++source->cursor();
		if (yych != 'p') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'l') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'F') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'l') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'u') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 't') goto yy2_3;
		source->ctxmarker() = source->cursor() + 1;
		yych = *++source->cursor();
		if (yych <= '@') goto yy2_86;
		if (yych <= 'Z') goto yy2_3;
		if (yych <= '`') goto yy2_86;
		if (yych <= 'z') goto yy2_3;
yy2_86:
		++source->cursor();
		source->cursor() = source->ctxmarker();
#line 106 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_SIMPLEFLUENT;					goto re2c_finish;					}
#line 431 "<stdout>"
yy2_88:
		yych = *++source->cursor();
		if (yych != 'o') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'g') goto yy2_3;
		yych = *++source->cursor();
		if (yych == '_') goto yy2_94;
		if (yych == 'n') goto yy2_3;
		goto yy2_93;
yy2_92:
		++source->cursor();
		if ((source->limit() - source->cursor()) < 14) source->fill(14);
		yych = *source->cursor();
yy2_93:
		if (yybm[0+yych] & 128) {
			goto yy2_92;
		}
		if (yych == 'n') goto yy2_110;
		goto yy2_3;
yy2_94:
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'o') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'c') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'o') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'c') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'u') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'r') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'r') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'c') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'y') goto yy2_3;
		source->ctxmarker() = source->cursor() + 1;
		yych = *++source->cursor();
		if (yych <= '@') goto yy2_108;
		if (yych <= 'Z') goto yy2_3;
		if (yych <= '`') goto yy2_108;
		if (yych <= 'z') goto yy2_3;
yy2_108:
		++source->cursor();
		source->cursor() = source->ctxmarker();
#line 108 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_STRONG_NOCONCURRENCY;			goto re2c_finish;					}
#line 491 "<stdout>"
yy2_110:
		yych = *++source->cursor();
		if (yych != 'o') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'c') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'o') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'c') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'u') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'r') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'r') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'c') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'y') goto yy2_3;
		source->ctxmarker() = source->cursor() + 1;
		yych = *++source->cursor();
		if (yych <= '@') goto yy2_123;
		if (yych <= 'Z') goto yy2_3;
		if (yych <= '`') goto yy2_123;
		if (yych <= 'z') goto yy2_3;
yy2_123:
		++source->cursor();
		source->cursor() = source->ctxmarker();
#line 107 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_STRONG_NOCONCURRENCY;			goto re2c_finish;					}
#line 528 "<stdout>"
yy2_125:
		yych = *++source->cursor();
		if (yych != 'g') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'i') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'd') goto yy2_3;
		source->ctxmarker() = source->cursor() + 1;
		yych = *++source->cursor();
		if (yych <= '@') goto yy2_129;
		if (yych <= 'Z') goto yy2_3;
		if (yych <= '`') goto yy2_129;
		if (yych <= 'z') goto yy2_3;
yy2_129:
		++source->cursor();
		source->cursor() = source->ctxmarker();
#line 104 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_RIGID;						goto re2c_finish;					}
#line 547 "<stdout>"
yy2_131:
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'r') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'y') goto yy2_3;
		source->ctxmarker() = source->cursor() + 1;
		yych = *++source->cursor();
		if (yych <= '@') goto yy2_135;
		if (yych <= 'Z') goto yy2_3;
		if (yych <= '`') goto yy2_135;
		if (yych <= 'z') goto yy2_3;
yy2_135:
		++source->cursor();
		source->cursor() = source->ctxmarker();
#line 61 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_QUERY;						goto re2c_finish;					}
#line 566 "<stdout>"
yy2_137:
		yych = *++source->cursor();
		if (yych != 's') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 's') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'i') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'b') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'l') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'y') goto yy2_3;
		yych = *++source->cursor();
		if (yych == 'c') goto yy2_3;
		goto yy2_145;
yy2_144:
		++source->cursor();
		if ((source->limit() - source->cursor()) < 7) source->fill(7);
		yych = *source->cursor();
yy2_145:
		if (yych <= '\f') {
			if (yych == '\t') goto yy2_144;
			if (yych <= '\n') goto yy2_3;
			goto yy2_144;
		} else {
			if (yych <= ' ') {
				if (yych <= 0x1F) goto yy2_3;
				goto yy2_144;
			} else {
				if (yych != 'c') goto yy2_3;
			}
		}
		yych = *++source->cursor();
		if (yych != 'a') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'u') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 's') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'd') goto yy2_3;
		source->ctxmarker() = source->cursor() + 1;
		yych = *++source->cursor();
		if (yych <= '@') goto yy2_152;
		if (yych <= 'Z') goto yy2_3;
		if (yych <= '`') goto yy2_152;
		if (yych <= 'z') goto yy2_3;
yy2_152:
		++source->cursor();
		source->cursor() = source->ctxmarker();
#line 103 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_POSSIBLY_CAUSED;				goto re2c_finish;					}
#line 621 "<stdout>"
yy2_154:
		source->ctxmarker() = source->cursor() + 1;
		yych = *++source->cursor();
		if (yych <= '@') goto yy2_171;
		if (yych <= 'Z') goto yy2_3;
		if (yych <= '`') goto yy2_171;
		if (yych <= 'z') goto yy2_3;
		goto yy2_171;
yy2_155:
		yych = *++source->cursor();
		if (yych == 'j') goto yy2_156;
		if (yych == 's') goto yy2_157;
		goto yy2_3;
yy2_156:
		yych = *++source->cursor();
		if (yych == 'e') goto yy2_165;
		goto yy2_3;
yy2_157:
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'r') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'v') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'd') goto yy2_3;
		source->ctxmarker() = source->cursor() + 1;
		yych = *++source->cursor();
		if (yych <= '@') goto yy2_163;
		if (yych <= 'Z') goto yy2_3;
		if (yych <= '`') goto yy2_163;
		if (yych <= 'z') goto yy2_3;
yy2_163:
		++source->cursor();
		source->cursor() = source->ctxmarker();
#line 102 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_OBSERVED;						goto re2c_finish;					}
#line 661 "<stdout>"
yy2_165:
		yych = *++source->cursor();
		if (yych != 'c') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 't') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 's') goto yy2_3;
		source->ctxmarker() = source->cursor() + 1;
		yych = *++source->cursor();
		if (yych <= '@') goto yy2_169;
		if (yych <= 'Z') goto yy2_3;
		if (yych <= '`') goto yy2_169;
		if (yych <= 'z') goto yy2_3;
yy2_169:
		++source->cursor();
		source->cursor() = source->ctxmarker();
#line 60 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_OBJECTS;						goto re2c_finish;					}
#line 680 "<stdout>"
yy2_171:
		++source->cursor();
		source->cursor() = source->ctxmarker();
#line 101 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_OF;							goto re2c_finish;					}
#line 686 "<stdout>"
yy2_173:
		yych = *++source->cursor();
		if (yych <= 'm') {
			if (yych == 'c') goto yy2_183;
			goto yy2_3;
		} else {
			if (yych <= 'n') goto yy2_184;
			if (yych == 't') goto yy2_185;
			goto yy2_3;
		}
yy2_174:
		yych = *++source->cursor();
		if (yych == 'q') goto yy2_176;
		if (yych != 'v') goto yy2_3;
		yych = *++source->cursor();
		if (yych == 'e') goto yy2_179;
		goto yy2_3;
yy2_176:
		source->ctxmarker() = source->cursor() + 1;
		yych = *++source->cursor();
		if (yych <= '@') goto yy2_177;
		if (yych <= 'Z') goto yy2_3;
		if (yych <= '`') goto yy2_177;
		if (yych <= 'z') goto yy2_3;
yy2_177:
		++source->cursor();
		source->cursor() = source->ctxmarker();
#line 117 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_NEQ;							goto re2c_finish;					}
#line 716 "<stdout>"
yy2_179:
		yych = *++source->cursor();
		if (yych != 'r') goto yy2_3;
		source->ctxmarker() = source->cursor() + 1;
		yych = *++source->cursor();
		if (yych <= '@') goto yy2_181;
		if (yych <= 'Z') goto yy2_3;
		if (yych <= '`') goto yy2_181;
		if (yych <= 'z') goto yy2_3;
yy2_181:
		++source->cursor();
		source->cursor() = source->ctxmarker();
#line 98 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_NEVER;						goto re2c_finish;					}
#line 731 "<stdout>"
yy2_183:
		yych = *++source->cursor();
		if (yych == 'o') goto yy2_200;
		goto yy2_3;
yy2_184:
		yych = *++source->cursor();
		if (yych == 'e') goto yy2_188;
		goto yy2_3;
yy2_185:
		source->ctxmarker() = source->cursor() + 1;
		yych = *++source->cursor();
		if (yych <= '@') goto yy2_186;
		if (yych <= 'Z') goto yy2_3;
		if (yych <= '`') goto yy2_186;
		if (yych <= 'z') goto yy2_3;
yy2_186:
		++source->cursor();
		source->cursor() = source->ctxmarker();
#line 118 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_NOT;							goto re2c_finish;					}
#line 752 "<stdout>"
yy2_188:
		yych = *++source->cursor();
		if (yych != 'x') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'c') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'u') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 't') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'a') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'b') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'l') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		source->ctxmarker() = source->cursor() + 1;
		yych = *++source->cursor();
		if (yych <= '@') goto yy2_198;
		if (yych <= 'Z') goto yy2_3;
		if (yych <= '`') goto yy2_198;
		if (yych <= 'z') goto yy2_3;
yy2_198:
		++source->cursor();
		source->cursor() = source->ctxmarker();
#line 100 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_NONEXECUTABLE;				goto re2c_finish;					}
#line 783 "<stdout>"
yy2_200:
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'c') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'u') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'r') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'r') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'c') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'y') goto yy2_3;
		source->ctxmarker() = source->cursor() + 1;
		yych = *++source->cursor();
		if (yych <= '@') goto yy2_210;
		if (yych <= 'Z') goto yy2_3;
		if (yych <= '`') goto yy2_210;
		if (yych <= 'z') goto yy2_3;
yy2_210:
		++source->cursor();
		source->cursor() = source->ctxmarker();
#line 99 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_NOCONCURRENCY;				goto re2c_finish;					}
#line 814 "<stdout>"
yy2_212:
		yych = *++source->cursor();
		if (yych == 'd') goto yy2_255;
		goto yy2_3;
yy2_213:
		yych = *++source->cursor();
		if (yych <= 'w') {
			if (yych != 'c') goto yy2_3;
		} else {
			if (yych <= 'x') goto yy2_216;
			if (yych <= 'y') goto yy2_215;
			goto yy2_3;
		}
		yych = *++source->cursor();
		if (yych == 'r') goto yy2_250;
		goto yy2_3;
yy2_215:
		yych = *++source->cursor();
		if (yych == 'c') goto yy2_3;
		goto yy2_242;
yy2_216:
		yych = *++source->cursor();
		if (yych == 'A') goto yy2_218;
		if (yych != 's') goto yy2_3;
		yych = *++source->cursor();
		if (yych == 't') goto yy2_236;
		goto yy2_3;
yy2_218:
		yych = *++source->cursor();
		if (yych == 'F') goto yy2_220;
		if (yych != 'd') goto yy2_3;
		yych = *++source->cursor();
		if (yych == 'd') goto yy2_228;
		goto yy2_3;
yy2_220:
		yych = *++source->cursor();
		if (yych != 'V') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'a') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'l') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'u') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		source->ctxmarker() = source->cursor() + 1;
		yych = *++source->cursor();
		if (yych <= '@') goto yy2_226;
		if (yych <= 'Z') goto yy2_3;
		if (yych <= '`') goto yy2_226;
		if (yych <= 'z') goto yy2_3;
yy2_226:
		++source->cursor();
		source->cursor() = source->ctxmarker();
#line 96 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_MAXAFVALUE;					goto re2c_finish;					}
#line 871 "<stdout>"
yy2_228:
		yych = *++source->cursor();
		if (yych != 'i') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 't') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'i') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'v') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		source->ctxmarker() = source->cursor() + 1;
		yych = *++source->cursor();
		if (yych <= '@') goto yy2_234;
		if (yych <= 'Z') goto yy2_3;
		if (yych <= '`') goto yy2_234;
		if (yych <= 'z') goto yy2_3;
yy2_234:
		++source->cursor();
		source->cursor() = source->ctxmarker();
#line 95 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_MAXADDITIVE;					goto re2c_finish;					}
#line 894 "<stdout>"
yy2_236:
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'p') goto yy2_3;
		source->ctxmarker() = source->cursor() + 1;
		yych = *++source->cursor();
		if (yych <= '@') goto yy2_239;
		if (yych <= 'Z') goto yy2_3;
		if (yych <= '`') goto yy2_239;
		if (yych <= 'z') goto yy2_3;
yy2_239:
		++source->cursor();
		source->cursor() = source->ctxmarker();
#line 97 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_MAXSTEP;						goto re2c_finish;					}
#line 911 "<stdout>"
yy2_241:
		++source->cursor();
		if ((source->limit() - source->cursor()) < 6) source->fill(6);
		yych = *source->cursor();
yy2_242:
		if (yych <= '\f') {
			if (yych == '\t') goto yy2_241;
			if (yych <= '\n') goto yy2_3;
			goto yy2_241;
		} else {
			if (yych <= ' ') {
				if (yych <= 0x1F) goto yy2_3;
				goto yy2_241;
			} else {
				if (yych != 'c') goto yy2_3;
			}
		}
		yych = *++source->cursor();
		if (yych != 'a') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'u') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 's') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		source->ctxmarker() = source->cursor() + 1;
		yych = *++source->cursor();
		if (yych <= '@') goto yy2_248;
		if (yych <= 'Z') goto yy2_3;
		if (yych <= '`') goto yy2_248;
		if (yych <= 'z') goto yy2_3;
yy2_248:
		++source->cursor();
		source->cursor() = source->ctxmarker();
#line 94 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_MAY_CAUSE;					goto re2c_finish;					}
#line 948 "<stdout>"
yy2_250:
		yych = *++source->cursor();
		if (yych != 'o') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 's') goto yy2_3;
		source->ctxmarker() = source->cursor() + 1;
		yych = *++source->cursor();
		if (yych <= '@') goto yy2_253;
		if (yych <= 'Z') goto yy2_3;
		if (yych <= '`') goto yy2_253;
		if (yych <= 'z') goto yy2_3;
yy2_253:
		++source->cursor();
		source->cursor() = source->ctxmarker();
#line 59 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_MACROS; _in_macro = true;		goto re2c_finish;					}
#line 965 "<stdout>"
yy2_255:
		source->ctxmarker() = source->cursor() + 1;
		yych = *++source->cursor();
		if (yych <= '@') goto yy2_256;
		if (yych <= 'Z') goto yy2_3;
		if (yych <= '`') goto yy2_256;
		if (yych <= 'z') goto yy2_3;
yy2_256:
		++source->cursor();
		source->cursor() = source->ctxmarker();
#line 116 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_MOD;							goto re2c_finish;					}
#line 978 "<stdout>"
yy2_258:
		yych = *++source->cursor();
		if (yych != 'b') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'l') goto yy2_3;
		source->ctxmarker() = source->cursor() + 1;
		yych = *++source->cursor();
		if (yych <= '@') goto yy2_262;
		if (yych <= 'Z') goto yy2_3;
		if (yych <= '`') goto yy2_262;
		if (yych <= 'z') goto yy2_3;
yy2_262:
		++source->cursor();
		source->cursor() = source->ctxmarker();
#line 93 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_LABEL;						goto re2c_finish;					}
#line 997 "<stdout>"
yy2_264:
		yych = *++source->cursor();
		if (yych == 'c') goto yy2_285;
		if (yych == 'e') goto yy2_286;
		goto yy2_3;
yy2_265:
		yych = *++source->cursor();
		if (yych == 'p') goto yy2_275;
		goto yy2_3;
yy2_266:
		source->ctxmarker() = source->cursor() + 1;
		yych = *++source->cursor();
		if (yych <= '`') {
			if (yych <= '@') goto yy2_267;
			if (yych <= 'Z') goto yy2_3;
		} else {
			if (yych == 'c') goto yy2_269;
			if (yych <= 'z') goto yy2_3;
		}
yy2_267:
		++source->cursor();
		source->cursor() = source->ctxmarker();
#line 87 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_IF;							goto re2c_finish;					}
#line 1022 "<stdout>"
yy2_269:
		yych = *++source->cursor();
		if (yych != 'o') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 's') goto yy2_3;
		source->ctxmarker() = source->cursor() + 1;
		yych = *++source->cursor();
		if (yych <= '@') goto yy2_273;
		if (yych <= 'Z') goto yy2_3;
		if (yych <= '`') goto yy2_273;
		if (yych <= 'z') goto yy2_3;
yy2_273:
		++source->cursor();
		source->cursor() = source->ctxmarker();
#line 88 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_IFCONS;						goto re2c_finish;					}
#line 1041 "<stdout>"
yy2_275:
		yych = *++source->cursor();
		if (yych != 'o') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 's') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 's') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'i') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'b') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'l') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		source->ctxmarker() = source->cursor() + 1;
		yych = *++source->cursor();
		if (yych <= '@') goto yy2_283;
		if (yych <= 'Z') goto yy2_3;
		if (yych <= '`') goto yy2_283;
		if (yych <= 'z') goto yy2_3;
yy2_283:
		++source->cursor();
		source->cursor() = source->ctxmarker();
#line 89 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_IMPOSSIBLE;					goto re2c_finish;					}
#line 1068 "<stdout>"
yy2_285:
		yych = *++source->cursor();
		if (yych == 'l') goto yy2_303;
		if (yych == 'r') goto yy2_302;
		goto yy2_3;
yy2_286:
		yych = *++source->cursor();
		if (yych != 'r') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 't') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'i') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'a') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'l') goto yy2_3;
		source->ctxmarker() = source->cursor() + 1;
		yych = *++source->cursor();
		if (yych <= 'F') {
			if (yych <= '@') goto yy2_292;
			if (yych <= 'E') goto yy2_3;
			goto yy2_294;
		} else {
			if (yych <= 'Z') goto yy2_3;
			if (yych <= '`') goto yy2_292;
			if (yych <= 'z') goto yy2_3;
		}
yy2_292:
		++source->cursor();
		source->cursor() = source->ctxmarker();
#line 91 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_INERTIAL;						goto re2c_finish;					}
#line 1101 "<stdout>"
yy2_294:
		yych = *++source->cursor();
		if (yych != 'l') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'u') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 't') goto yy2_3;
		source->ctxmarker() = source->cursor() + 1;
		yych = *++source->cursor();
		if (yych <= '@') goto yy2_300;
		if (yych <= 'Z') goto yy2_3;
		if (yych <= '`') goto yy2_300;
		if (yych <= 'z') goto yy2_3;
yy2_300:
		++source->cursor();
		source->cursor() = source->ctxmarker();
#line 92 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_INERTIALFLUENT;				goto re2c_finish;					}
#line 1124 "<stdout>"
yy2_302:
		yych = *++source->cursor();
		if (yych == 'e') goto yy2_309;
		goto yy2_3;
yy2_303:
		yych = *++source->cursor();
		if (yych != 'u') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'd') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		source->ctxmarker() = source->cursor() + 1;
		yych = *++source->cursor();
		if (yych <= '@') goto yy2_307;
		if (yych <= 'Z') goto yy2_3;
		if (yych <= '`') goto yy2_307;
		if (yych <= 'z') goto yy2_3;
yy2_307:
		++source->cursor();
		source->cursor() = source->ctxmarker();
#line 58 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_INCLUDE;						goto re2c_finish;					}
#line 1147 "<stdout>"
yy2_309:
		yych = *++source->cursor();
		if (yych != 'm') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 't') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 's') goto yy2_3;
		source->ctxmarker() = source->cursor() + 1;
		yych = *++source->cursor();
		if (yych <= '@') goto yy2_315;
		if (yych <= 'Z') goto yy2_3;
		if (yych <= '`') goto yy2_315;
		if (yych <= 'z') goto yy2_3;
yy2_315:
		++source->cursor();
		source->cursor() = source->ctxmarker();
#line 90 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_INCREMENTS;					goto re2c_finish;					}
#line 1170 "<stdout>"
yy2_317:
		yych = *++source->cursor();
		if (yych != 'd') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		source->ctxmarker() = source->cursor() + 1;
		yych = *++source->cursor();
		if (yych <= '@') goto yy2_320;
		if (yych <= 'Z') goto yy2_3;
		if (yych <= '`') goto yy2_320;
		if (yych <= 'z') goto yy2_3;
yy2_320:
		++source->cursor();
		source->cursor() = source->ctxmarker();
#line 63 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_HIDE;							goto re2c_finish;					}
#line 1187 "<stdout>"
yy2_322:
		yych = *++source->cursor();
		if (yych != 'l') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 's') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		source->ctxmarker() = source->cursor() + 1;
		yych = *++source->cursor();
		if (yych <= '@') goto yy2_326;
		if (yych <= 'Z') goto yy2_3;
		if (yych <= '`') goto yy2_326;
		if (yych <= 'z') goto yy2_3;
yy2_326:
		++source->cursor();
		source->cursor() = source->ctxmarker();
#line 115 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_FALSE;						goto re2c_finish;					}
#line 1206 "<stdout>"
yy2_328:
		source->ctxmarker() = source->cursor() + 1;
		yych = *++source->cursor();
		if (yych <= '@') goto yy2_369;
		if (yych <= 'Z') goto yy2_3;
		if (yych <= '`') goto yy2_369;
		if (yych <= 'z') goto yy2_3;
		goto yy2_369;
yy2_329:
		yych = *++source->cursor();
		if (yych == 'o') goto yy2_331;
		if (yych != 't') goto yy2_3;
		yych = *++source->cursor();
		if (yych == 'e') goto yy2_348;
		goto yy2_3;
yy2_331:
		yych = *++source->cursor();
		if (yych != 'g') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'o') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'u') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 's') goto yy2_3;
		source->ctxmarker() = source->cursor() + 1;
		yych = *++source->cursor();
		if (yych <= 'Z') {
			if (yych <= '@') goto yy2_339;
			if (yych >= 'B') goto yy2_3;
		} else {
			if (yych <= '`') goto yy2_339;
			if (yych <= 'z') goto yy2_3;
			goto yy2_339;
		}
		yych = *++source->cursor();
		if (yych == 'c') goto yy2_341;
		goto yy2_3;
yy2_339:
		++source->cursor();
		source->cursor() = source->ctxmarker();
#line 85 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_EXOGENOUS;					goto re2c_finish;					}
#line 1253 "<stdout>"
yy2_341:
		yych = *++source->cursor();
		if (yych != 't') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'i') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'o') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		source->ctxmarker() = source->cursor() + 1;
		yych = *++source->cursor();
		if (yych <= '@') goto yy2_346;
		if (yych <= 'Z') goto yy2_3;
		if (yych <= '`') goto yy2_346;
		if (yych <= 'z') goto yy2_3;
yy2_346:
		++source->cursor();
		source->cursor() = source->ctxmarker();
#line 86 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_EXOGENOUSACTION;				goto re2c_finish;					}
#line 1274 "<stdout>"
yy2_348:
		yych = *++source->cursor();
		if (yych != 'r') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'a') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'l') goto yy2_3;
		yych = *++source->cursor();
		if (yych == 'A') goto yy2_353;
		if (yych == 'F') goto yy2_354;
		goto yy2_3;
yy2_353:
		yych = *++source->cursor();
		if (yych == 'c') goto yy2_362;
		goto yy2_3;
yy2_354:
		yych = *++source->cursor();
		if (yych != 'l') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'u') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 't') goto yy2_3;
		source->ctxmarker() = source->cursor() + 1;
		yych = *++source->cursor();
		if (yych <= '@') goto yy2_360;
		if (yych <= 'Z') goto yy2_3;
		if (yych <= '`') goto yy2_360;
		if (yych <= 'z') goto yy2_3;
yy2_360:
		++source->cursor();
		source->cursor() = source->ctxmarker();
#line 84 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_EXTERNALFLUENT;				goto re2c_finish;					}
#line 1314 "<stdout>"
yy2_362:
		yych = *++source->cursor();
		if (yych != 't') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'i') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'o') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		source->ctxmarker() = source->cursor() + 1;
		yych = *++source->cursor();
		if (yych <= '@') goto yy2_367;
		if (yych <= 'Z') goto yy2_3;
		if (yych <= '`') goto yy2_367;
		if (yych <= 'z') goto yy2_3;
yy2_367:
		++source->cursor();
		source->cursor() = source->ctxmarker();
#line 83 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_EXTERNALACTION;				goto re2c_finish;					}
#line 1335 "<stdout>"
yy2_369:
		++source->cursor();
		source->cursor() = source->ctxmarker();
#line 114 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_EQ;							goto re2c_finish;					}
#line 1341 "<stdout>"
yy2_371:
		yych = *++source->cursor();
		if (yych == 'c') goto yy2_372;
		if (yych == 'f') goto yy2_373;
		goto yy2_3;
yy2_372:
		yych = *++source->cursor();
		if (yych == 'r') goto yy2_380;
		goto yy2_3;
yy2_373:
		yych = *++source->cursor();
		if (yych != 'a') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'u') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'l') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 't') goto yy2_3;
		source->ctxmarker() = source->cursor() + 1;
		yych = *++source->cursor();
		if (yych <= '@') goto yy2_378;
		if (yych <= 'Z') goto yy2_3;
		if (yych <= '`') goto yy2_378;
		if (yych <= 'z') goto yy2_3;
yy2_378:
		++source->cursor();
		source->cursor() = source->ctxmarker();
#line 82 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_DEFAULT;						goto re2c_finish;					}
#line 1371 "<stdout>"
yy2_380:
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'm') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 't') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 's') goto yy2_3;
		source->ctxmarker() = source->cursor() + 1;
		yych = *++source->cursor();
		if (yych <= '@') goto yy2_387;
		if (yych <= 'Z') goto yy2_3;
		if (yych <= '`') goto yy2_387;
		if (yych <= 'z') goto yy2_3;
yy2_387:
		++source->cursor();
		source->cursor() = source->ctxmarker();
#line 81 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_DECREMENTS;					goto re2c_finish;					}
#line 1396 "<stdout>"
yy2_389:
		yych = *++source->cursor();
		if (yych == 'n') goto yy2_400;
		goto yy2_3;
yy2_390:
		yych = *++source->cursor();
		if (yych != 'u') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 's') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		yych = *++source->cursor();
		if (yych == 'd') goto yy2_395;
		if (yych != 's') goto yy2_3;
		source->ctxmarker() = source->cursor() + 1;
		yych = *++source->cursor();
		if (yych <= '@') goto yy2_398;
		if (yych <= 'Z') goto yy2_3;
		if (yych <= '`') goto yy2_398;
		if (yych <= 'z') goto yy2_3;
		goto yy2_398;
yy2_395:
		source->ctxmarker() = source->cursor() + 1;
		yych = *++source->cursor();
		if (yych <= '@') goto yy2_396;
		if (yych <= 'Z') goto yy2_3;
		if (yych <= '`') goto yy2_396;
		if (yych <= 'z') goto yy2_3;
yy2_396:
		++source->cursor();
		source->cursor() = source->ctxmarker();
#line 77 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_CAUSED;						goto re2c_finish;					}
#line 1430 "<stdout>"
yy2_398:
		++source->cursor();
		source->cursor() = source->ctxmarker();
#line 78 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_CAUSES;						goto re2c_finish;					}
#line 1436 "<stdout>"
yy2_400:
		yych = *++source->cursor();
		if (yych != 's') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 't') goto yy2_3;
		yych = *++source->cursor();
		if (yych == 'a') goto yy2_404;
		if (yych != 'r') goto yy2_3;
		yych = *++source->cursor();
		if (yych == 'a') goto yy2_410;
		goto yy2_3;
yy2_404:
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 't') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 's') goto yy2_3;
		source->ctxmarker() = source->cursor() + 1;
		yych = *++source->cursor();
		if (yych <= '@') goto yy2_408;
		if (yych <= 'Z') goto yy2_3;
		if (yych <= '`') goto yy2_408;
		if (yych <= 'z') goto yy2_3;
yy2_408:
		++source->cursor();
		source->cursor() = source->ctxmarker();
#line 79 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_CONSTANTS;					goto re2c_finish;					}
#line 1466 "<stdout>"
yy2_410:
		yych = *++source->cursor();
		if (yych != 'i') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 't') goto yy2_3;
		source->ctxmarker() = source->cursor() + 1;
		yych = *++source->cursor();
		if (yych <= '@') goto yy2_414;
		if (yych <= 'Z') goto yy2_3;
		if (yych <= '`') goto yy2_414;
		if (yych <= 'z') goto yy2_3;
yy2_414:
		++source->cursor();
		source->cursor() = source->ctxmarker();
#line 80 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_CONSTRAINT;					goto re2c_finish;					}
#line 1485 "<stdout>"
yy2_416:
		source->ctxmarker() = source->cursor() + 1;
		yych = *++source->cursor();
		if (yych <= '@') goto yy2_417;
		if (yych <= 'Z') goto yy2_3;
		if (yych <= '`') goto yy2_417;
		if (yych <= 'z') goto yy2_3;
yy2_417:
		++source->cursor();
		source->cursor() = source->ctxmarker();
#line 76 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_BY;							goto re2c_finish;					}
#line 1498 "<stdout>"
yy2_419:
		yych = *++source->cursor();
		if (yych == 'A') goto yy2_487;
		if (yych == 's') goto yy2_488;
		goto yy2_3;
yy2_420:
		source->ctxmarker() = source->cursor() + 1;
		yych = *++source->cursor();
		if (yych <= '`') {
			if (yych <= '@') goto yy2_477;
			if (yych <= 'Z') goto yy2_3;
			goto yy2_477;
		} else {
			if (yych == 't') goto yy2_476;
			if (yych <= 'z') goto yy2_3;
			goto yy2_477;
		}
yy2_421:
		yych = *++source->cursor();
		if (yych == 'l') goto yy2_468;
		if (yych == 'w') goto yy2_467;
		goto yy2_3;
yy2_422:
		yych = *++source->cursor();
		if (yych == 's') goto yy2_459;
		goto yy2_3;
yy2_423:
		yych = *++source->cursor();
		if (yych == 't') goto yy2_454;
		goto yy2_3;
yy2_424:
		yych = *++source->cursor();
		if (yych == 'd') goto yy2_432;
		goto yy2_3;
yy2_425:
		yych = *++source->cursor();
		if (yych != 't') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'i') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'o') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		source->ctxmarker() = source->cursor() + 1;
		yych = *++source->cursor();
		if (yych <= '@') goto yy2_430;
		if (yych <= 'Z') goto yy2_3;
		if (yych <= '`') goto yy2_430;
		if (yych <= 'z') goto yy2_3;
yy2_430:
		++source->cursor();
		source->cursor() = source->ctxmarker();
#line 67 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_ACTION;						goto re2c_finish;					}
#line 1553 "<stdout>"
yy2_432:
		yych = *++source->cursor();
		if (yych != 'i') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 't') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'i') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'v') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		yych = *++source->cursor();
		if (yych == 'A') goto yy2_438;
		if (yych == 'F') goto yy2_439;
		goto yy2_3;
yy2_438:
		yych = *++source->cursor();
		if (yych == 'c') goto yy2_447;
		goto yy2_3;
yy2_439:
		yych = *++source->cursor();
		if (yych != 'l') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'u') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 't') goto yy2_3;
		source->ctxmarker() = source->cursor() + 1;
		yych = *++source->cursor();
		if (yych <= '@') goto yy2_445;
		if (yych <= 'Z') goto yy2_3;
		if (yych <= '`') goto yy2_445;
		if (yych <= 'z') goto yy2_3;
yy2_445:
		++source->cursor();
		source->cursor() = source->ctxmarker();
#line 69 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_ADDITIVEFLUENT;				goto re2c_finish;					}
#line 1595 "<stdout>"
yy2_447:
		yych = *++source->cursor();
		if (yych != 't') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'i') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'o') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		source->ctxmarker() = source->cursor() + 1;
		yych = *++source->cursor();
		if (yych <= '@') goto yy2_452;
		if (yych <= 'Z') goto yy2_3;
		if (yych <= '`') goto yy2_452;
		if (yych <= 'z') goto yy2_3;
yy2_452:
		++source->cursor();
		source->cursor() = source->ctxmarker();
#line 68 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_ADDITIVEACTION;				goto re2c_finish;					}
#line 1616 "<stdout>"
yy2_454:
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'r') goto yy2_3;
		source->ctxmarker() = source->cursor() + 1;
		yych = *++source->cursor();
		if (yych <= '@') goto yy2_457;
		if (yych <= 'Z') goto yy2_3;
		if (yych <= '`') goto yy2_457;
		if (yych <= 'z') goto yy2_3;
yy2_457:
		++source->cursor();
		source->cursor() = source->ctxmarker();
#line 70 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_AFTER;						goto re2c_finish;					}
#line 1633 "<stdout>"
yy2_459:
		yych = *++source->cursor();
		if (yych != 'u') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'm') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'i') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'g') goto yy2_3;
		source->ctxmarker() = source->cursor() + 1;
		yych = *++source->cursor();
		if (yych <= '@') goto yy2_465;
		if (yych <= 'Z') goto yy2_3;
		if (yych <= '`') goto yy2_465;
		if (yych <= 'z') goto yy2_3;
yy2_465:
		++source->cursor();
		source->cursor() = source->ctxmarker();
#line 72 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_ASSUMING;						goto re2c_finish;					}
#line 1656 "<stdout>"
yy2_467:
		yych = *++source->cursor();
		if (yych == 'a') goto yy2_471;
		goto yy2_3;
yy2_468:
		source->ctxmarker() = source->cursor() + 1;
		yych = *++source->cursor();
		if (yych <= '@') goto yy2_469;
		if (yych <= 'Z') goto yy2_3;
		if (yych <= '`') goto yy2_469;
		if (yych <= 'z') goto yy2_3;
yy2_469:
		++source->cursor();
		source->cursor() = source->ctxmarker();
#line 74 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_ALL;							goto re2c_finish;					}
#line 1673 "<stdout>"
yy2_471:
		yych = *++source->cursor();
		if (yych != 'y') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 's') goto yy2_3;
		source->ctxmarker() = source->cursor() + 1;
		yych = *++source->cursor();
		if (yych <= '@') goto yy2_474;
		if (yych <= 'Z') goto yy2_3;
		if (yych <= '`') goto yy2_474;
		if (yych <= 'z') goto yy2_3;
yy2_474:
		++source->cursor();
		source->cursor() = source->ctxmarker();
#line 71 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_ALWAYS;						goto re2c_finish;					}
#line 1690 "<stdout>"
yy2_476:
		yych = *++source->cursor();
		if (yych == 'r') goto yy2_479;
		goto yy2_3;
yy2_477:
		++source->cursor();
		source->cursor() = source->ctxmarker();
#line 75 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_AT;							goto re2c_finish;					}
#line 1700 "<stdout>"
yy2_479:
		yych = *++source->cursor();
		if (yych != 'i') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'b') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'u') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 't') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'e') goto yy2_3;
		source->ctxmarker() = source->cursor() + 1;
		yych = *++source->cursor();
		if (yych <= '@') goto yy2_485;
		if (yych <= 'Z') goto yy2_3;
		if (yych <= '`') goto yy2_485;
		if (yych <= 'z') goto yy2_3;
yy2_485:
		++source->cursor();
		source->cursor() = source->ctxmarker();
#line 73 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_ATTRIBUTE;					goto re2c_finish;					}
#line 1723 "<stdout>"
yy2_487:
		yych = *++source->cursor();
		if (yych == 'c') goto yy2_491;
		goto yy2_3;
yy2_488:
		source->ctxmarker() = source->cursor() + 1;
		yych = *++source->cursor();
		if (yych <= '@') goto yy2_489;
		if (yych <= 'Z') goto yy2_3;
		if (yych <= '`') goto yy2_489;
		if (yych <= 'z') goto yy2_3;
yy2_489:
		++source->cursor();
		source->cursor() = source->ctxmarker();
#line 113 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_ABS;							goto re2c_finish;					}
#line 1740 "<stdout>"
yy2_491:
		yych = *++source->cursor();
		if (yych != 't') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'i') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'o') goto yy2_3;
		yych = *++source->cursor();
		if (yych != 'n') goto yy2_3;
		source->ctxmarker() = source->cursor() + 1;
		yych = *++source->cursor();
		if (yych <= '@') goto yy2_496;
		if (yych <= 'Z') goto yy2_3;
		if (yych <= '`') goto yy2_496;
		if (yych <= 'z') goto yy2_3;
yy2_496:
		++source->cursor();
		source->cursor() = source->ctxmarker();
#line 66 "bcplus/parser/detail/Scanner.2.re2c"
		{ ret = T_ABACTION;						goto re2c_finish;					}
#line 1761 "<stdout>"
	}
}
#line 125 "bcplus/parser/detail/Scanner.2.re2c"

	}
re2c_notkw:
	source->cursor() = source->token();
	return tokenize_3(source);

re2c_finish:
	u::ref_ptr<ReferencedString> str = new ReferencedString();
	if (ret != T_EOF) {
		str->assign(source->token(), (size_t)(source->cursor() - source->token()));
	} else {
		str->assign("<EOF>");
	}

	return new Token(ret, str, begin, source->loc());
}

}}}
