#define T_ID                              1
#define T_STRING_LITERAL                  2
#define T_L_PAREN                         3
#define T_R_PAREN                         4
#define T_DOT                             5
#define T_COMMA                           6
#define T_COLON                           7
#define T_NUMBER                          8
#define T_FP_NUMBER                       9
#define T_ANSWER                         10
#define T_SATISFIABLE                    11
#define T_UNSATISFIABLE                  12
#define T_MODELS                         13
#define T_TIME                           14
#define T_PREPARE                        15
#define T_PREPRO_DOT                     16
#define T_SOLVING                        17
#define T_EOF                            18
#define T_ERR_UNTERMINATED_STRING        19
#define T_ERR_UNKNOWN_SYMBOL             20
